export interface BasicKanjiItem {
  character: string;
  readingsOnyomi: string[];
  readingsKunyomi: string[];
  strokeCount: number;
  meanings: string[];
  meaningsNepali: string[];
  formation: string;
  formationNepali: string;
}

export interface BasicVocabItem {
  word: string;
  romaji: string;
  meaning: string;
  meaningNepali: string;
}

export const BASIC_KANJI_100: BasicKanjiItem[] = [
  // Numbers
  { character: "一", readingsOnyomi: ["ICHI"], readingsKunyomi: ["hito-tsu"], strokeCount: 1, meanings: ["One"], meaningsNepali: ["एक"], formation: "A single horizontal line representing a single object or finger.", formationNepali: "एउटा वस्तु वा औंलालाई जनाउने एकल तेर्सो रेखा।" },
  { character: "二", readingsOnyomi: ["NI"], readingsKunyomi: ["futa-tsu"], strokeCount: 2, meanings: ["Two"], meaningsNepali: ["दुई"], formation: "Two horizontal lines representing two objects.", formationNepali: "दुईवटा वस्तुहरूलाई जनाउने दुईवटा तेर्सो रेखाहरू।" },
  { character: "三", readingsOnyomi: ["SAN"], readingsKunyomi: ["mit-tsu"], strokeCount: 3, meanings: ["Three"], meaningsNepali: ["तीन"], formation: "Three horizontal lines representing three items.", formationNepali: "तीनवटा वस्तुहरूलाई जनाउने तीनवटा तेर्सो रेखाहरू।" },
  { character: "四", readingsOnyomi: ["SHI"], readingsKunyomi: ["yon", "yot-tsu"], strokeCount: 5, meanings: ["Four"], meaningsNepali: ["चार"], formation: "A box enclosing legs or curtains, representing a split number.", formationNepali: "खुट्टा वा पर्दा घेरेको बाकस, विभाजित संख्याको संकेत।" },
  { character: "五", readingsOnyomi: ["GO"], readingsKunyomi: ["itsu-tsu"], strokeCount: 4, meanings: ["Five"], meaningsNepali: ["पाँच"], formation: "Originally represented crossing lines, now five strokes.", formationNepali: "सुरुमा क्रस गरिएका रेखाहरू जनाउँथ्यो, अहिले पाँचवटा कोरेका रेखाहरू।" },
  { character: "六", readingsOnyomi: ["ROKU"], readingsKunyomi: ["mut-tsu"], strokeCount: 4, meanings: ["Six"], meaningsNepali: ["छ"], formation: "Derived from an ancient drawing representing a house or shelter.", formationNepali: "घर वा आश्रयलाई जनाउने पुरानो चित्रबाट विकसित।" },
  { character: "七", readingsOnyomi: ["SHICHI"], readingsKunyomi: ["nana-tsu"], strokeCount: 2, meanings: ["Seven"], meaningsNepali: ["सात"], formation: "Originally a cross-shaped cut mark representing a slice.", formationNepali: "काटिएको चिन्ह जनाउने सुरुको क्रस आकारको कोरा।" },
  { character: "八", readingsOnyomi: ["HACHI"], readingsKunyomi: ["yat-tsu"], strokeCount: 2, meanings: ["Eight"], meaningsNepali: ["आठ"], formation: "Two bent lines parting from each other, representing division.", formationNepali: "एकअर्काबाट छुट्टिँदै गरेका दुईवटा बाङ्गा रेखाहरू, विभाजनको संकेत।" },
  { character: "九", readingsOnyomi: ["KYŪ"], readingsKunyomi: ["kokono-tsu"], strokeCount: 2, meanings: ["Nine"], meaningsNepali: ["नौ"], formation: "Depicts a bent arm or crook, signifying almost reaching ten.", formationNepali: "हात वा कुइनो दोब्रिएको चित्र, जसले लगभग १० पुग्न लागेको जनाउँछ।" },
  { character: "十", readingsOnyomi: ["JŪ"], readingsKunyomi: ["tō"], strokeCount: 2, meanings: ["Ten"], meaningsNepali: ["दश"], formation: "A vertical line intersecting a horizontal line, closing the set.", formationNepali: "तेर्सो रेखालाई काट्ने ठाडो रेखा, जसले पूरै समूहलाई बन्द गर्छ।" },
  { character: "百", readingsOnyomi: ["HYAKU"], readingsKunyomi: [], strokeCount: 6, meanings: ["Hundred"], meaningsNepali: ["सय"], formation: "Modification of 'white' character with a line on top to signify 100.", formationNepali: "'सेतो' अक्षरमा माथि एउटा रेखा थपेर १०० को संख्या बुझाइएको।" },
  { character: "千", readingsOnyomi: ["SEN"], readingsKunyomi: ["chi"], strokeCount: 3, meanings: ["Thousand"], meaningsNepali: ["हजार"], formation: "Modification of 'person' with a slash, representing many people.", formationNepali: "'मानिस' जनाउने अक्षरमा छड्के कोरा थपेर धेरै संख्या बुझाइएको।" },
  { character: "万", readingsOnyomi: ["MAN"], readingsKunyomi: [], strokeCount: 3, meanings: ["Ten Thousand"], meaningsNepali: ["दश हजार"], formation: "Originally depicted a scorpion (in large numbers), now ten thousand.", formationNepali: "सुरुमा एक बिच्छीको चित्र (ठूलो संख्यामा हुने) बाट बनेको, अहिले १० हजार।" },
  { character: "円", readingsOnyomi: ["EN"], readingsKunyomi: ["maru-i"], strokeCount: 4, meanings: ["Yen", "Circle"], meaningsNepali: ["येन", "गोलो"], formation: "Simplified drawing of a round coin inside a boundary.", formationNepali: "सीमा भित्र रहेको गोलो सिक्काको सरलीकृत चित्र।" },

  // Nature & Time
  { character: "日", readingsOnyomi: ["NICHI", "JITSU"], readingsKunyomi: ["hi", "bi"], strokeCount: 4, meanings: ["Sun", "Day"], meaningsNepali: ["घाम", "दिन"], formation: "A simple circle with a central dot, representing the sun.", formationNepali: "केन्द्रमा बिन्दु भएको गोलो घेरा, जसले सूर्यलाई बुझाउँछ।" },
  { character: "月", readingsOnyomi: ["GETSU", "GATSU"], readingsKunyomi: ["tsuki"], strokeCount: 4, meanings: ["Moon", "Month"], meaningsNepali: ["जुन", "महिना"], formation: "A crescent moon shape with clouds or lines passing through.", formationNepali: "बादल वा रेखाहरू बीचबाट देखिने अर्धचन्द्राकार जुनको आकृति।" },
  { character: "火", readingsOnyomi: ["KA"], readingsKunyomi: ["hi"], strokeCount: 4, meanings: ["Fire"], meaningsNepali: ["आगो"], formation: "A drawing of rising flames and sparks from a campfire.", formationNepali: "दन्किरहेको आगोको ज्वाला र झिल्काहरूको चित्र।" },
  { character: "水", readingsOnyomi: ["SUI"], readingsKunyomi: ["mizu"], strokeCount: 4, meanings: ["Water"], meaningsNepali: ["पानी"], formation: "Depicts water flowing down a central stream with ripples.", formationNepali: "केन्द्रीय धारबाट बगिरहेको पानी र छालहरूको चित्र।" },
  { character: "木", readingsOnyomi: ["MOKU"], readingsKunyomi: ["ki"], strokeCount: 4, meanings: ["Tree", "Wood"], meaningsNepali: ["रूख", "काठ"], formation: "A trunk with branches spreading out and roots spreading below.", formationNepali: "काठको ठुटो, हाङ्गाबिङ्गा र जमिन मुनिको जराको चित्र।" },
  { character: "金", readingsOnyomi: ["KIN"], readingsKunyomi: ["kane"], strokeCount: 8, meanings: ["Gold", "Money"], meaningsNepali: ["सुन", "पैसा"], formation: "Gold nuggets buried deep inside the earth underneath a roof.", formationNepali: "छानो मुनि पृथ्वी भित्र गाडिएका सुनका टुक्राहरू।" },
  { character: "土", readingsOnyomi: ["DO"], readingsKunyomi: ["tsuchi"], strokeCount: 3, meanings: ["Soil", "Earth"], meaningsNepali: ["माटो", "जमिन"], formation: "A plant sprout growing out of the flat ground level.", formationNepali: "समथर जमिनको सतहबाट उम्रेको बिरुवाको टुसा।" },
  { character: "年", readingsOnyomi: ["NEN"], readingsKunyomi: ["toshi"], strokeCount: 6, meanings: ["Year"], meaningsNepali: ["वर्ष"], formation: "Originally depicted a person carrying harvested grain on their back.", formationNepali: "सुरुमा मानिसले आफ्नो ढाडमा भित्र्याएको अन्न बोकेको चित्र।" },
  { character: "時", readingsOnyomi: ["JI"], readingsKunyomi: ["toki"], strokeCount: 10, meanings: ["Time", "Hour"], meaningsNepali: ["समय", "घण्टा"], formation: "Combination of 'Sun' (日) and 'Temple/Measure' (寺) to denote time.", formationNepali: "'सूर्य' (日) र 'मन्दिर/मापन' (寺) को संयोजन जसले समय जनाउँछ।" },
  { character: "分", readingsOnyomi: ["BUN", "FUN"], readingsKunyomi: ["wa-karu"], strokeCount: 4, meanings: ["Minute", "Divide", "Understand"], meaningsNepali: ["मिनेट", "बाँड्नु", "बुझ्नु"], formation: "A knife (刀) splitting something into two halves (八).", formationNepali: "चक्कुले (刀) कुनै कुरालाई दुई भागमा (八) काटेको चित्र।" },
  { character: "半", readingsOnyomi: ["HAN"], readingsKunyomi: [], strokeCount: 5, meanings: ["Half"], meaningsNepali: ["आधा"], formation: "Lines representing an object divided symmetrically down the center.", formationNepali: "वस्तुलाई बीचबाट ठ्याक्कै आधा पारेर दुवै तर्फ बराबर देखाउने रेखाहरू।" },
  { character: "今", readingsOnyomi: ["KON"], readingsKunyomi: ["ima"], strokeCount: 4, meanings: ["Now", "Present"], meaningsNepali: ["अहिले", "वर्तमान"], formation: "An enclosed lid representing containment of the present moment.", formationNepali: "वर्तमान क्षणलाई बन्द गरेर राखिएको ढक्कन जस्तो आकृति।" },
  { character: "週", readingsOnyomi: ["SHŪ"], readingsKunyomi: [], strokeCount: 11, meanings: ["Week"], meaningsNepali: ["हप्ता"], formation: "A road (road radical) wrapping around a full circle of days.", formationNepali: "सडकको बाटो जसले दिनहरूको पूर्ण चक्र फन्को मार्छ।" },
  { character: "朝", readingsOnyomi: ["CHŌ"], readingsKunyomi: ["asa"], strokeCount: 12, meanings: ["Morning"], meaningsNepali: ["बिहान"], formation: "The sun rising between grass while the moon is still visible.", formationNepali: "घाँसको बीचबाट उदाउँदै गरेको सूर्य र सँगै देखिने चन्द्रमा।" },
  { character: "昼", readingsOnyomi: ["CHŪ"], readingsKunyomi: ["hiru"], strokeCount: 9, meanings: ["Noon", "Daytime"], meaningsNepali: ["दिउँसो"], formation: "Represents the sun high in the sky during active work hours.", formationNepali: "काम गर्ने समयमा आकाशको बीचमा रहेको सूर्यको संकेत।" },
  { character: "夜", readingsOnyomi: ["YA"], readingsKunyomi: ["yoru"], strokeCount: 8, meanings: ["Night"], meaningsNepali: ["राति"], formation: "A person under the moon, resting after the sun goes down.", formationNepali: "सूर्य अस्ताएपछि चन्द्रमा मुनि आराम गरिरहेको मानिस।" },
  { character: "夕", readingsOnyomi: ["SEKI"], readingsKunyomi: ["yuu"], strokeCount: 3, meanings: ["Evening"], meaningsNepali: ["बेलुकी"], formation: "A crescent moon partially obscured by clouds at dusk.", formationNepali: "साँझपख बादलले आधा ढाकिएको अर्धचन्द्राकार चन्द्रमा।" },
  { character: "午", readingsOnyomi: ["GO"], readingsKunyomi: [], strokeCount: 4, meanings: ["Noon"], meaningsNepali: ["मध्यान्ह"], formation: "A pestle or signpost representing the middle point of day.", formationNepali: "दिनको मध्य भागलाई जनाउने खम्बा वा मन्थन लठ्ठी।" },
  { character: "前", readingsOnyomi: ["ZEN"], readingsKunyomi: ["mae"], strokeCount: 9, meanings: ["Before", "Front"], meaningsNepali: ["पहिले", "अगाडि"], formation: "Represents moving forward with scissors or cutting paths ahead.", formationNepali: "अगाडिको बाटो काट्दै वा कैंची चलाउँदै अघि बढेको संकेत।" },
  { character: "後", readingsOnyomi: ["GO", "KŌ"], readingsKunyomi: ["ushiro", "ato"], strokeCount: 9, meanings: ["Behind", "After"], meaningsNepali: ["पछाडि", "पछि"], formation: "A person walking with tied threads, lagging behind slowly.", formationNepali: "धागो बाँधिएर बिस्तारै हिँडिरहेको मानिस, जो पछाडि पर्छ।" },

  // People & Family
  { character: "人", readingsOnyomi: ["JIN", "NIN"], readingsKunyomi: ["hito"], strokeCount: 2, meanings: ["Person"], meaningsNepali: ["मानिस"], formation: "A side view of a person standing on two legs.", formationNepali: "दुई खुट्टामा उभिएको मानिसको side profile चित्र।" },
  { character: "口", readingsOnyomi: ["KŌ"], readingsKunyomi: ["kuchi"], strokeCount: 3, meanings: ["Mouth"], meaningsNepali: ["मुख"], formation: "An open mouth or entrance, drawn as a square box.", formationNepali: "खुला मुख वा प्रवेशद्वार, बाकस जस्तो आकारमा खिचिएको।" },
  { character: "目", readingsOnyomi: ["MOKU"], readingsKunyomi: ["me"], strokeCount: 5, meanings: ["Eye"], meaningsNepali: ["आँखा"], formation: "An eyeball showing the pupil inside, rotated vertically.", formationNepali: "भित्री नानी देखिने आँखाको चित्र, जसलाई ठाडो पारिएको छ।" },
  { character: "耳", readingsOnyomi: ["JI"], readingsKunyomi: ["mimi"], strokeCount: 6, meanings: ["Ear"], meaningsNepali: ["कान"], formation: "A drawing of an earlobe and outer ear structure.", formationNepali: "कानको लोती र बाहिरी भाग बुझाउने चित्र।" },
  { character: "手", readingsOnyomi: ["SHU"], readingsKunyomi: ["te"], strokeCount: 4, meanings: ["Hand"], meaningsNepali: ["हात"], formation: "A drawing of a palm with outstretched fingers.", formationNepali: "फैलिएका औंलाहरू सहितको हत्केलाको चित्र।" },
  { character: "足", readingsOnyomi: ["SOKU"], readingsKunyomi: ["ashi"], strokeCount: 7, meanings: ["Leg", "Foot"], meaningsNepali: ["खुट्टा"], formation: "A drawing of a knee, leg, and foot standing ground.", formationNepali: "घुँडा र भुइँमा टेकेको खुट्टाको भागको चित्र।" },
  { character: "子", readingsOnyomi: ["SHI"], readingsKunyomi: ["ko"], strokeCount: 3, meanings: ["Child"], meaningsNepali: ["बच्चा"], formation: "A baby in swaddling clothes waving its arms.", formationNepali: "कपडामा बेरिएको र हात हल्लाउँदै गरेको सानो बच्चा।" },
  { character: "女", readingsOnyomi: ["JO"], readingsKunyomi: ["onna"], strokeCount: 3, meanings: ["Woman"], meaningsNepali: ["महिला"], formation: "A woman kneeling down in a polite, respectful posture.", formationNepali: "विनम्र र आदरयुक्त मुद्रामा घुँडा टेकेकी महिला।" },
  { character: "男", readingsOnyomi: ["DAN"], readingsKunyomi: ["otoko"], strokeCount: 7, meanings: ["Man"], meaningsNepali: ["पुरुष"], formation: "Strength (力) used to work in the rice fields (田).", formationNepali: "धानखेतमा (田) शक्ति (力) लगाएर काम गरिरहेको मानिस।" },
  { character: "父", readingsOnyomi: ["FU"], readingsKunyomi: ["chichi"], strokeCount: 4, meanings: ["Father"], meaningsNepali: ["बुवा"], formation: "A hand holding a stone axe or stick, showing authority.", formationNepali: "हातमा बन्चरो वा लौरो समातेको आकृति, जसले अभिभावकत्व देखाउँछ।" },
  { character: "母", readingsOnyomi: ["BO"], readingsKunyomi: ["haha"], strokeCount: 5, meanings: ["Mother"], meaningsNepali: ["आमा"], formation: "A woman with breasts, nurturing and feeding a child.", formationNepali: "बच्चालाई दुग्धपान गराइरहेकी महिलाको छाती सहितको चित्र।" },
  { character: "友", readingsOnyomi: ["YŪ"], readingsKunyomi: ["tomo"], strokeCount: 4, meanings: ["Friend"], meaningsNepali: ["साथी"], formation: "Two hands clasped together in assistance and companion.", formationNepali: "सहयोग र मित्रताका लागि एकअर्कामा जोडिएका दुई हात।" },
  { character: "兄", readingsOnyomi: ["KYŌ"], readingsKunyomi: ["ani"], strokeCount: 5, meanings: ["Older Brother"], meaningsNepali: ["दाजु"], formation: "A big mouth (口) on top of walking legs, speaking guidance.", formationNepali: "हिँडिरहेको खुट्टा माथि ठूलो मुख (口), जसले सम्झाउने दाजु बुझाउँछ।" },
  { character: "弟", readingsOnyomi: ["TEI"], readingsKunyomi: ["otouto"], strokeCount: 7, meanings: ["Younger Brother"], meaningsNepali: ["भाई"], formation: "A leather strap wrapped around a wooden spindle.", formationNepali: "काठको कतुवा वा लठ्ठीमा बेरिएको छालाको फित्ता।" },
  { character: "姉", readingsOnyomi: ["SHI"], readingsKunyomi: ["ane"], strokeCount: 8, meanings: ["Older Sister"], meaningsNepali: ["दिदी"], formation: "A woman (女) who manages market stalls or cities (市).", formationNepali: "बजार वा घरको व्यवस्थापन गर्ने पाको महिला (女)।" },
  { character: "妹", readingsOnyomi: ["MAI"], readingsKunyomi: ["imōto"], strokeCount: 8, meanings: ["Younger Sister"], meaningsNepali: ["बहिनी"], formation: "A woman (女) who is not yet (未) fully grown.", formationNepali: "अझै पूर्ण रूपमा विकसित नभएकी (未) महिला (女)।" },
  { character: "自", readingsOnyomi: ["JI"], readingsKunyomi: ["mizu-kara"], strokeCount: 6, meanings: ["Self"], meaningsNepali: ["आफै"], formation: "Originally a drawing of a nose, which Japanese point to for 'self'.", formationNepali: "सुरुमा नाकको चित्र, जसलाई देखाएर मानिसले 'आफै' भन्ने बुझाउँछन्।" },
  { character: "己", readingsOnyomi: ["KO"], readingsKunyomi: ["onore"], strokeCount: 3, meanings: ["Self", "Individual"], meaningsNepali: ["आफ्नो"], formation: "A bent thread or wire, showing flexible boundary of self.", formationNepali: "दोब्रिएको धागो वा तार, जसले आफ्नो सीमा देखाउँछ।" },
  { character: "身", readingsOnyomi: ["SHIN"], readingsKunyomi: ["mi"], strokeCount: 7, meanings: ["Body", "Position"], meaningsNepali: ["शरीर"], formation: "A pregnant woman, representing the physical body and life.", formationNepali: "गर्भवती महिलाको कोख सहितको चित्र, जसले शरीर बुझाउँछ।" },

  // Nature & Directions
  { character: "山", readingsOnyomi: ["SAN"], readingsKunyomi: ["yama"], strokeCount: 3, meanings: ["Mountain"], meaningsNepali: ["पहाड"], formation: "Three rising peaks of a mountain range side by side.", formationNepali: "एकसाथ जोडिएका पहाडका तीनवटा अग्ला टाकुराहरू।" },
  { character: "川", readingsOnyomi: ["SEN"], readingsKunyomi: ["kawa"], strokeCount: 3, meanings: ["River"], meaningsNepali: ["नदी"], formation: "Flowing vertical lines representing a river bed.", formationNepali: "बगिरहेको पानीको बहाव देखाउने ठाडा रेखाहरू।" },
  { character: "田", readingsOnyomi: ["DEN"], readingsKunyomi: ["ta"], strokeCount: 5, meanings: ["Rice Field"], meaningsNepali: ["खेत"], formation: "A square plot divided into four small sections.", formationNepali: "चार भागमा विभाजित गरिएको धानखेतको गरा।" },
  { character: "天", readingsOnyomi: ["TEN"], readingsKunyomi: ["ame"], strokeCount: 4, meanings: ["Heaven", "Sky"], meaningsNepali: ["स्वर्ग"], formation: "A person with a massive head, indicating sky above.", formationNepali: "फैलिएको मानिसको टाउको माथिको विशाल आकाश।" },
  { character: "空", readingsOnyomi: ["KŪ"], readingsKunyomi: ["sora"], strokeCount: 8, meanings: ["Sky", "Empty"], meaningsNepali: ["आकाश", "खाली"], formation: "A roof cavity or hole representing open empty air.", formationNepali: "छाना मुनि रहेको खाली ठाउँ वा खुल्ला आकाश।" },
  { character: "気", readingsOnyomi: ["KI"], readingsKunyomi: [], strokeCount: 6, meanings: ["Spirit", "Air"], meaningsNepali: ["आत्मा", "हवा"], formation: "Steam rising from boiling rice, indicating energy.", formationNepali: "भात पकाउँदा逆सने बाफ, जसले शक्ति बुझाउँछ।" },
  { character: "雨", readingsOnyomi: ["U"], readingsKunyomi: ["ame"], strokeCount: 8, meanings: ["Rain"], meaningsNepali: ["पानी"], formation: "Water droplets falling down inside a window box sky.", formationNepali: "आकाशबाट झरिरहेका पानीका थोपाहरू।" },
  { character: "雪", readingsOnyomi: ["SETSU"], readingsKunyomi: ["yuki"], strokeCount: 11, meanings: ["Snow"], meaningsNepali: ["हिउँ"], formation: "Rain (雨) falling that can be swept or held with hand (ヨ).", formationNepali: "पानी (雨) जो चिसो भएर हातले (ヨ) जम्मा गर्न सकिन्छ।" },
  { character: "風", readingsOnyomi: ["FŪ"], readingsKunyomi: ["kaze"], strokeCount: 9, meanings: ["Wind"], meaningsNepali: ["हावा"], formation: "An insect moving inside a sail, showing wind movement.", formationNepali: "पाल भित्र किरा हल्लिएको चित्र, जसले हावा बगेको बुझाउँछ।" },
  { character: "花", readingsOnyomi: ["KA"], readingsKunyomi: ["hana"], strokeCount: 7, meanings: ["Flower"], meaningsNepali: ["फूल"], formation: "Plants (grass radical) that transform (化) into blooms.", formationNepali: "वनस्पति (घाँस) जो रूपान्तरण (化) भएर फुल्छन्।" },
  { character: "林", readingsOnyomi: ["RIN"], readingsKunyomi: ["hayashi"], strokeCount: 8, meanings: ["Grove", "Forest"], meaningsNepali: ["सानो वन"], formation: "Two trees (木) side by side, forming a small grove.", formationNepali: "सँगै रहेका दुईवटा रूखहरू (木), जसले सानो जङ्गल बुझाउँछ।" },
  { character: "森", readingsOnyomi: ["SHIN"], readingsKunyomi: ["mori"], strokeCount: 12, meanings: ["Forest"], meaningsNepali: ["जङ्गल"], formation: "Three trees (木) grouped together, showing deep forest.", formationNepali: "एकसाथ रहेका तीनवटा रूखहरू (木), जसले बाक्लो जङ्गल बुझाउँछ।" },
  { character: "石", readingsOnyomi: ["SEKI"], readingsKunyomi: ["ishi"], strokeCount: 5, meanings: ["Stone"], meaningsNepali: ["ढुङ्गा"], formation: "A cliff showing a rock tumble or mouth block under it.", formationNepali: "भिर मुनि खसेको ढुङ्गाको टुक्रा जस्तो आकृति।" },
  { character: "岩", readingsOnyomi: ["GAN"], readingsKunyomi: ["iwa"], strokeCount: 8, meanings: ["Boulder", "Rock"], meaningsNepali: ["चट्टान"], formation: "A stone (石) situated under a mountain peak (山).", formationNepali: "पहाडको (山) मुनि रहेको विशाल ढुङ्गा (石)।" },
  { character: "上", readingsOnyomi: ["JŌ"], readingsKunyomi: ["ue"], strokeCount: 3, meanings: ["Up", "Above"], meaningsNepali: ["माथि"], formation: "A horizontal boundary line with a vertical line pointing up.", formationNepali: "तेर्सो सतहको रेखा माथि उठेको अर्को सानो रेखा।" },
  { character: "下", readingsOnyomi: ["KA", "GE"], readingsKunyomi: ["shita"], strokeCount: 3, meanings: ["Down", "Below"], meaningsNepali: ["तल"], formation: "A horizontal boundary line with a vertical indicator pointing down.", formationNepali: "तेर्सो सतहको रेखा मुनि झरेको सानो रेखा।" },
  { character: "中", readingsOnyomi: ["CHŪ"], readingsKunyomi: ["naka"], strokeCount: 4, meanings: ["Middle", "Inside"], meaningsNepali: ["बीच", "भित्र"], formation: "A line passing right through the middle of a box.", formationNepali: "बाकसको ठीक बीच भागबाट काट्दै गएको ठाडो रेखा।" },
  { character: "左", readingsOnyomi: ["SA"], readingsKunyomi: ["hidari"], strokeCount: 5, meanings: ["Left"], meaningsNepali: ["बायाँ"], formation: "A hand holding a tool (工) to work on the left side.", formationNepali: "बायाँ हातले औजार (工) समातेर काम गरिरहेको चित्र।" },
  { character: "右", readingsOnyomi: ["YŪ"], readingsKunyomi: ["migi"], strokeCount: 5, meanings: ["Right"], meaningsNepali: ["दायाँ"], formation: "A hand coming down to feed the mouth (口) on the right side.", formationNepali: "दायाँ हातले मुखमा (口) खाना पुर्याउन लागेको चित्र।" },
  { character: "東", readingsOnyomi: ["TŌ"], readingsKunyomi: ["higashi"], strokeCount: 8, meanings: ["East"], meaningsNepali: ["पूर्व"], formation: "The sun (日) rising behind a tree trunk (木) in the east.", formationNepali: "पूर्व दिशामा रूखको (木) पछाडिबाट उदाउँदै गरेको सूर्य (日)।" },
  { character: "西", readingsOnyomi: ["SEI"], readingsKunyomi: ["nishi"], strokeCount: 6, meanings: ["West"], meaningsNepali: ["पश्चिम"], formation: "A bird returning to its nest to sleep as sun sets in west.", formationNepali: "बेलुका चरा आफ्नो गुँडमा फर्किरहेको चित्र, पश्चिम दिशा।" },
  { character: "南", readingsOnyomi: ["NAN"], readingsKunyomi: ["minami"], strokeCount: 9, meanings: ["South"], meaningsNepali: ["दक्षिण"], formation: "An ancient drawing of a musical bell or warm vegetation region.", formationNepali: "घण्टी जस्तो देखिने पुरानो चित्र, तातो दक्षिण दिशा।" },
  { character: "北", readingsOnyomi: ["HOKU"], readingsKunyomi: ["kita"], strokeCount: 5, meanings: ["North"], meaningsNepali: ["उत्तर"], formation: "Two people sitting back-to-back, facing away from warmth.", formationNepali: "एकअर्कातर्फ ढाड फर्काएर बसेका दुई मानिस, उत्तर दिशा।" },
  { character: "内", readingsOnyomi: ["NAI"], readingsKunyomi: ["uchi"], strokeCount: 4, meanings: ["Inside", "Within"], meaningsNepali: ["भित्र"], formation: "Entering (入) inside a gated border or shelter.", formationNepali: "घर वा घेरा भित्र (入) प्रवेश गरिरहेको आकृति।" },
  { character: "外", readingsOnyomi: ["GAI"], readingsKunyomi: ["soto"], strokeCount: 5, meanings: ["Outside"], meaningsNepali: ["बाहिर"], formation: "Divining bones cast outside under the evening (夕) moon.", formationNepali: "साँझपख (夕) बाहिर बसेर भविष्य हेर्नका लागि हड्डी फ्याँकेको चित्र।" },

  // Daily Concepts & Verbs
  { character: "本", readingsOnyomi: ["HON"], readingsKunyomi: ["moto"], strokeCount: 5, meanings: ["Book", "Origin"], meaningsNepali: ["किताब", "मूल"], formation: "A tree (木) with a mark at its root origin.", formationNepali: "रूखको (木) फेद वा जरामा तेर्सो चिन्ह लगाएर आधार देखाएको।" },
  { character: "何", readingsOnyomi: ["KA"], readingsKunyomi: ["nani", "nan"], strokeCount: 7, meanings: ["What"], meaningsNepali: ["के"], formation: "A person carrying a bag on shoulder, asking where/what.", formationNepali: "काँधमा भारी बोकेको मानिसले 'यो के हो' भनी सोधेको चित्र।" },
  { character: "先", readingsOnyomi: ["SEN"], readingsKunyomi: ["saki"], strokeCount: 6, meanings: ["Ahead", "Before"], meaningsNepali: ["पहिले", "अगाडि"], formation: "Footprints moving forward ahead of others.", formationNepali: "अरूभन्दा पहिले नै अघि बढिरहेका खुट्टाका पाइलाहरू।" },
  { character: "生", readingsOnyomi: ["SEI"], readingsKunyomi: ["i-kiru", "u-mu"], strokeCount: 5, meanings: ["Life", "Birth"], meaningsNepali: ["जीवन", "जन्म"], formation: "A green sprout breaking out of the earth ground.", formationNepali: "माटो चिरेर निस्किँदै गरेको हरियो बिरुवाको टुसा।" },
  { character: "学", readingsOnyomi: ["GAKU"], readingsKunyomi: ["mana-bu"], strokeCount: 8, meanings: ["Study", "Learn"], meaningsNepali: ["अध्ययन"], formation: "Hands helping a child learn under a roof canopy.", formationNepali: "छाना मुनि हात समाएर बच्चालाई सिकाउँदै गरेको चित्र।" },
  { character: "校", readingsOnyomi: ["KŌ"], readingsKunyomi: [], strokeCount: 10, meanings: ["School"], meaningsNepali: ["विद्यालय"], formation: "A wooden building (木) where students mix and gather.", formationNepali: "काठको (木) भवन जहाँ विद्यार्थीहरू जम्मा हुन्छन्।" },
  { character: "語", readingsOnyomi: ["GO"], readingsKunyomi: ["kata-ru"], strokeCount: 14, meanings: ["Language", "Talk"], meaningsNepali: ["भाषा"], formation: "Speech (言) combined with five mouths (吾) speaking.", formationNepali: "वाणी (言) र पाँचवटा मुखहरूले (吾) पालैपालो बोलेको चित्र।" },
  { character: "国", readingsOnyomi: ["KOKU"], readingsKunyomi: ["kuni"], strokeCount: 8, meanings: ["Country"], meaningsNepali: ["देश"], formation: "A jade treasure inside a secure border enclosure.", formationNepali: "सुरक्षित घेरिएको क्षेत्र भित्र रहेको बहुमूल्य वस्तु।" },
  { character: "名", readingsOnyomi: ["MEI"], readingsKunyomi: ["na"], strokeCount: 6, meanings: ["Name"], meaningsNepali: ["नाम"], formation: "Saying one's name through mouth (口) in evening (夕) dark.", formationNepali: "साँझपख (夕) अँध्यारोमा मुखले (口) बोलेर आफ्नो name चिनाएको।" },
  { character: "会", readingsOnyomi: ["KAI"], readingsKunyomi: ["a-u"], strokeCount: 6, meanings: ["Meeting", "Meet"], meaningsNepali: ["भेट्नु", "बैठक"], formation: "People gathered under a roof to meet and discuss.", formationNepali: "एउटै छाना मुनि मानिसहरू कुराकानीका लागि जम्मा भएको।" },
  { character: "社", readingsOnyomi: ["SHA"], readingsKunyomi: ["yashiro"], strokeCount: 7, meanings: ["Company", "Shrine"], meaningsNepali: ["कम्पनी", "मन्दिर"], formation: "Altar showing spirit presence near local land mound.", formationNepali: "जमिनको देवता पुजिने वेदी वा थानको चित्र।" },
  { character: "行", readingsOnyomi: ["KŌ", "GYŌ"], readingsKunyomi: ["i-ku"], strokeCount: 6, meanings: ["Go", "Conduct"], meaningsNepali: ["जानु"], formation: "A crossroad intersection showing a path to walk.", formationNepali: "हिँड्नका लागि बनाइएको चारबाटो वा चोकको चित्र।" },
  { character: "来", readingsOnyomi: ["RAI"], readingsKunyomi: ["ku-ru"], strokeCount: 7, meanings: ["Come"], meaningsNepali: ["आउनु"], formation: "Wheat or barley seed falling from heaven down to earth.", formationNepali: "आकाशबाट जमिनमा खसेको गहुँको गेडा, जो आउने फसल हो।" },
  { character: "出", readingsOnyomi: ["SHUTSU"], readingsKunyomi: ["de-ru"], strokeCount: 5, meanings: ["Exit", "Leave"], meaningsNepali: ["निस्कनु"], formation: "A foot leaving a container or growing out from base.", formationNepali: "भाँडो वा जगबाट बाहिर निस्किँदै गरेको पाइला।" },
  { character: "入", readingsOnyomi: ["NYŪ"], readingsKunyomi: ["hai-ru"], strokeCount: 2, meanings: ["Enter", "Insert"], meaningsNepali: ["पस्नु"], formation: "A person walking inside a doorway or boundary.", formationNepali: "ढोका वा घेरा भित्र हिँडेर पस्दै गरेको मानिस।" },
  { character: "立", readingsOnyomi: ["RITSU"], readingsKunyomi: ["ta-tsu"], strokeCount: 5, meanings: ["Stand"], meaningsNepali: ["उभिनु"], formation: "A person standing firmly with two feet on the ground.", formationNepali: "जमिनमा दुई खुट्टा टेकेर दह्रोसँग उभिएको मानिस।" },
  { character: "休", readingsOnyomi: ["KYŪ"], readingsKunyomi: ["yasu-mu"], strokeCount: 6, meanings: ["Rest", "Holiday"], meaningsNepali: ["आराम गर्नु"], formation: "A person (人) resting beside a shade tree (木).", formationNepali: "मानिस (人) रूखको (木) छहारीमा अढेस लागेर आराम गरेको।" },
  { character: "見", readingsOnyomi: ["KEN"], readingsKunyomi: ["mi-ru"], strokeCount: 7, meanings: ["See", "Look"], meaningsNepali: ["हेर्नु"], formation: "An eye (目) sitting on legs walking to look around.", formationNepali: "हिँडिरहेको खुट्टा माथि रहेको आँखा (目), जसले वरपर हेर्छ।" },
  { character: "聞", readingsOnyomi: ["BUN"], readingsKunyomi: ["ki-ku"], strokeCount: 14, meanings: ["Listen", "Hear"], meaningsNepali: ["सुन्नु"], formation: "An ear (耳) listening inside a doorway gate.", formationNepali: "ढोकाको चौकोस भित्र कान (耳) थापेर कुरा सुनेको चित्र।" },
  { character: "書", readingsOnyomi: ["SHO"], readingsKunyomi: ["ka-ku"], strokeCount: 10, meanings: ["Write", "Book"], meaningsNepali: ["लेख्नु"], formation: "A hand holding a brush ink pen over a tablet.", formationNepali: "हातमा मसीको ब्रस समातेर कापीमा लेखिरहेको आकृति।" },
  { character: "読", readingsOnyomi: ["DOKU"], readingsKunyomi: ["yo-mu"], strokeCount: 14, meanings: ["Read"], meaningsNepali: ["पढ्नु"], formation: "Speech (言) combined with selling/trading words.", formationNepali: "वाणी (言) लाई बुझेर मनन गर्ने वा पढ्ने कार्य।" },
  { character: "食", readingsOnyomi: ["SHOKU"], readingsKunyomi: ["ta-beru"], strokeCount: 9, meanings: ["Eat", "Food"], meaningsNepali: ["खानु"], formation: "A food bowl with a lid containing grains.", formationNepali: "ढक्कन लगाइएको भाँडो भित्र रहेको अन्न वा खाना।" },
  { character: "飲", readingsOnyomi: ["IN"], readingsKunyomi: ["no-mu"], strokeCount: 12, meanings: ["Drink"], meaningsNepali: ["पिउनु"], formation: "A person yawning or swallowing liquid from a jar.", formationNepali: "घैलाबाट रसास्वादन गर्न मुख खोलेको मानिसको चित्र।" },
  { character: "買", readingsOnyomi: ["BAI"], readingsKunyomi: ["ka-u"], strokeCount: 12, meanings: ["Buy"], meaningsNepali: ["किन्नु"], formation: "A shell (貝) used as ancient money underneath net.", formationNepali: "प्राचीन समयमा पैसाको रूपमा प्रयोग हुने कौडी (貝)।" },
  { character: "物", readingsOnyomi: ["BUTSU"], readingsKunyomi: ["mono"], strokeCount: 8, meanings: ["Thing", "Object"], meaningsNepali: ["वस्तु"], formation: "An ox (牛) that represents general physical matter.", formationNepali: "गाईवस्तु (牛) जसले भौतिक वस्तु वा सम्पत्ति बुझाउँथ्यो।" },
  { character: "犬", readingsOnyomi: ["KEN"], readingsKunyomi: ["inu"], strokeCount: 4, meanings: ["Dog"], meaningsNepali: ["कुकुर"], formation: "A dog with a dot representing its small ear or leash.", formationNepali: "कुकुर र उसको घाँटीमा बाँधिएको सानो चिन्ह।" },
  { character: "猫", readingsOnyomi: ["BYŌ"], readingsKunyomi: ["neko"], strokeCount: 11, meanings: ["Cat"], meaningsNepali: ["बिरालो"], formation: "A beast clawing at seedlings in agricultural field.", formationNepali: "खेतको बालीमा पञ्जा हान्ने सानो जनावर (बिरालो)।" },
  { character: "魚", readingsOnyomi: ["GYO"], readingsKunyomi: ["sakana"], strokeCount: 11, meanings: ["Fish"], meaningsNepali: ["माछा"], formation: "Head, scales, and tail of a swimming fish.", formationNepali: "पौडिरहेको माछाको टाउको, कत्ला र पुच्छरको चित्र।" },
  { character: "大", readingsOnyomi: ["DAI"], readingsKunyomi: ["ō-kii"], strokeCount: 3, meanings: ["Big", "Large"], meaningsNepali: ["ठूलो"], formation: "A person standing with arms and legs fully stretched out.", formationNepali: "हात र खुट्टा चौडा फैलाएर उभिएको मानिसको चित्र।" },
  { character: "小", readingsOnyomi: ["SHŌ"], readingsKunyomi: ["chii-sai"], strokeCount: 3, meanings: ["Small"], meaningsNepali: ["सानो"], formation: "Three small grains or droplets split down from center.", formationNepali: "बीचबाट विभाजित गरिएका तीनवटा साना कणहरू।" },
  { character: "長", readingsOnyomi: ["CHŌ"], readingsKunyomi: ["naga-i"], strokeCount: 8, meanings: ["Long", "Leader"], meaningsNepali: ["लामो", "प्रमुख"], formation: "A person with long flowing hair, representing old age.", formationNepali: "लामो कपाल फिँजाएको मानिस, जसले पाको प्रमुख बुझाउँछ।" },
  { character: "高", readingsOnyomi: ["KŌ"], readingsKunyomi: ["taka-i"], strokeCount: 10, meanings: ["High", "Expensive"], meaningsNepali: ["अग्लो", "महँगो"], formation: "A tall multistory observation tower castle building.", formationNepali: "अग्लो महल वा धरहराको बुर्जा जस्तो आकृति।" },
  { character: "安", readingsOnyomi: ["AN"], readingsKunyomi: ["yasu-i"], strokeCount: 6, meanings: ["Safe", "Cheap"], meaningsNepali: ["सुरक्षित", "सस्तो"], formation: "A woman (女) resting safely under a home roof canopy.", formationNepali: "घरको छाना मुनि सुरक्षित बसेकी महिला (女)।" },
  { character: "新", readingsOnyomi: ["SHIN"], readingsKunyomi: ["atara-shii"], strokeCount: 13, meanings: ["New"], meaningsNepali: ["नयाँ"], formation: "Cutting fresh hazelwood with an axe (斤).", formationNepali: "बन्चरोले (斤) नयाँ काठ काटेर ताजा फर्निचर बनाउने कार्य।" },
  { character: "古", readingsOnyomi: ["KO"], readingsKunyomi: ["furu-i"], strokeCount: 5, meanings: ["Old"], meaningsNepali: ["पुरानो"], formation: "A tomb shield marker passed through ten generations of mouths.", formationNepali: "दशौं पुस्तासम्म (十) मुखले (口) भन्दै आएको पुरानो कथा।" },
  { character: "多", readingsOnyomi: ["TA"], readingsKunyomi: ["ō-i"], strokeCount: 6, meanings: ["Many", "Much"], meaningsNepali: ["धेरै"], formation: "Two evening moons (夕) overlapping, showing abundance.", formationNepali: "एक माथि अर्को खप्टिएका दुई चन्द्रमा (夕), धेरैको संकेत।" },
  { character: "少", readingsOnyomi: ["SHŌ"], readingsKunyomi: ["suku-nai"], strokeCount: 4, meanings: ["Few", "Little"], meaningsNepali: ["कम"], formation: "Small grain (小) with a diagonal line indicating slice away.", formationNepali: "सानो धुलोको (小) कणलाई अझ काटेर कम पारेको चित्र।" }
];

export const BASIC_VOCAB_200: BasicVocabItem[] = [
  // Greetings & Essentials
  { word: "こんにちは", romaji: "konnichiwa", meaning: "Hello / Good afternoon", meaningNepali: "नमस्ते / नमस्कार" },
  { word: "ありがとう", romaji: "arigatou", meaning: "Thank you", meaningNepali: "धन्यवाद" },
  { word: "すみません", romaji: "sumimasen", meaning: "Excuse me / Sorry", meaningNepali: "माफ गर्नुहोस् / क्षमा गर्नुहोस्" },
  { word: "はい", romaji: "hai", meaning: "Yes", meaningNepali: "हजुर / हो" },
  { word: "いいえ", romaji: "iie", meaning: "No", meaningNepali: "होइन" },
  { word: "おはよう", romaji: "ohayou", meaning: "Good morning", meaningNepali: "शुभ प्रभात" },
  { word: "さようなら", romaji: "sayounara", meaning: "Goodbye", meaningNepali: "बिदा हुनुहोस्" },
  { word: "おやすみ", romaji: "oyasumi", meaning: "Good night", meaningNepali: "शुभ रात्रि" },
  { word: "おねがいします", romaji: "onegaishimasu", meaning: "Please (request)", meaningNepali: "कृपया" },
  { word: "どうぞ", romaji: "douzo", meaning: "Here you go / Please go ahead", meaningNepali: "लिनुहोस्" },
  { word: "いただきます", romaji: "itadakimasu", meaning: "Let's eat (grace)", meaningNepali: "खान सुरु गरौं" },
  { word: "ごちそうさま", romaji: "gochisousama", meaning: "Thank you for the meal", meaningNepali: "भोजनको लागि धन्यवाद" },
  { word: "はじめまして", romaji: "hajimemashite", meaning: "Nice to meet you", meaningNepali: "तपाईंसँग भेटेर खुसी लाग्यो" },
  { word: "douitashimashite", romaji: "douitashimashite", meaning: "You are welcome", meaningNepali: "स्वागत छ / केही छैन" },
  { word: "おげんきですか", romaji: "ogenki desu ka", meaning: "How are you?", meaningNepali: "तपाईंलाई कस्तो छ?" },
  { word: "げんきです", romaji: "genki desu", meaning: "I am fine", meaningNepali: "म ठीक छु" },
  { word: "だいじょうぶです", romaji: "daijoubu desu", meaning: "It is okay / I am fine", meaningNepali: "ठीकै छ / चिन्ता नगर्नुहोस्" },
  { word: "いってきます", romaji: "ittekimasu", meaning: "I am leaving (home)", meaningNepali: "म जान्छु" },
  { word: "いってらっしゃい", romaji: "itterasshai", meaning: "Please go and come back", meaningNepali: "सुरक्षित जानुहोस्" },
  { word: "ただいま", romaji: "tadaima", meaning: "I am home", meaningNepali: "म आइपुगें" },
  { word: "おかえりなさい", romaji: "okaerinasai", meaning: "Welcome home", meaningNepali: "स्वागत छ" },
  { word: "ごめんください", romaji: "gomen kudasai", meaning: "Excuse me, is anyone in?", meaningNepali: "कोही हुनुहुन्छ?" },
  { word: "しつれいします", romaji: "shitsurei shimasu", meaning: "Excuse me (entering/leaving)", meaningNepali: "माफ गर्नुहोला" },
  { word: "おめでとう", romaji: "omedetou", meaning: "Congratulations", meaningNepali: "बधाई छ" },
  { word: "がんばってください", romaji: "ganbatte kudasai", meaning: "Please do your best", meaningNepali: "राम्रो गर्नुहोस् / शुभकामना" },
  { word: "きをつけて", romaji: "ki wo tsukete", meaning: "Take care", meaningNepali: "आफ्नो ख्याल राख्नुहोस्" },
  { word: "またあした", romaji: "mata ashita", meaning: "See you tomorrow", meaningNepali: "भोलि भेटौंला" },
  { word: "もしもし", romaji: "moshimoshi", meaning: "Hello (on phone)", meaningNepali: "हेलो" },
  { word: "どうも", romaji: "doumo", meaning: "Thanks / Hi", meaningNepali: "धन्यवाद / नमस्ते" },
  { word: "すこし", romaji: "sukoshi", meaning: "A little", meaningNepali: "अलिकति" },

  // Quantity & Pronouns
  { word: "たくさん", romaji: "takusan", meaning: "A lot / Many", meaningNepali: "धेरै" },
  { word: "とても", romaji: "totemo", meaning: "Very", meaningNepali: "धेरै / असाध्यै" },
  { word: "よく", romaji: "yoku", meaning: "Well / Often", meaningNepali: "राम्रोसँग / अक्सर" },
  { word: "ゆっくり", romaji: "yukkuri", meaning: "Slowly", meaningNepali: "बिस्तारै" },
  { word: "すぐに", romaji: "sugu ni", meaning: "Immediately", meaningNepali: "तुरुन्तै" },
  { word: "はじめて", romaji: "hajimete", meaning: "For the first time", meaningNepali: "पहिलो पटक" },
  { word: "また", romaji: "mata", meaning: "Again", meaningNepali: "फेरि" },
  { word: "もっと", romaji: "motto", meaning: "More", meaningNepali: "अझ बढी" },
  { word: "いっしょに", romaji: "isshoni", meaning: "Together", meaningNepali: "सँगै" },
  { word: "ひとりで", romaji: "hitori de", meaning: "Alone", meaningNepali: "एक्लै" },
  { word: "ぜんぜん", romaji: "zenzen", meaning: "Not at all", meaningNepali: "बिल्कुलै होइन" },
  { word: "だいたい", romaji: "daitai", meaning: "Mostly / Generally", meaningNepali: "सामान्यतया" },
  { word: "ちょうど", romaji: "choudo", meaning: "Exactly", meaningNepali: "ठीक / दुरुस्तै" },
  { word: "いちばん", romaji: "ichiban", meaning: "Best / Number one", meaningNepali: "सबैभन्दा राम्रो" },
  { word: "どちら", romaji: "dochira", meaning: "Which way / Which one", meaningNepali: "कुन चाहिँ / कुन दिशा" },
  { word: "こっち", romaji: "kocchi", meaning: "This way", meaningNepali: "यतातिर" },
  { word: "そっち", romaji: "socchi", meaning: "That way", meaningNepali: "त्यतातिर" },
  { word: "あっち", romaji: "acchi", meaning: "That way (over there)", meaningNepali: "उतातिर" },
  { word: "どこ", romaji: "doko", meaning: "Where", meaningNepali: "कहाँ" },
  { word: "いつ", romaji: "itsu", meaning: "When", meaningNepali: "कहिले" },
  { word: "だれ", romaji: "dare", meaning: "Who", meaningNepali: "को" },
  { word: "なに", romaji: "nani", meaning: "What", meaningNepali: "के" },
  { word: "naze", romaji: "naze", meaning: "Why", meaningNepali: "किन" },
  { word: "いくら", romaji: "ikura", meaning: "How much (money)", meaningNepali: "कति" },
  { word: "いくつ", romaji: "ikutsu", meaning: "How many", meaningNepali: "कति वटा" },
  { word: "わたし", romaji: "watashi", meaning: "I / Me", meaningNepali: "म" },
  { word: "あなた", romaji: "anata", meaning: "You", meaningNepali: "तपाईं" },

  // People & Family
  { word: "ひと", romaji: "hito", meaning: "Person", meaningNepali: "मानिस" },
  { word: "ともだち", romaji: "tomodachi", meaning: "Friend", meaningNepali: "साथी" },
  { word: "こども", romaji: "kodomo", meaning: "Child", meaningNepali: "बच्चा" },
  { word: "おとこのこ", romaji: "otoko no ko", meaning: "Boy", meaningNepali: "केटा" },
  { word: "おんなのこ", romaji: "onna no ko", meaning: "Girl", meaningNepali: "केटी" },
  { word: "せんせい", romaji: "sensei", meaning: "Teacher", meaningNepali: "शिक्षक" },
  { word: "がくせい", romaji: "gakusei", meaning: "Student", meaningNepali: "विद्यार्थी" },
  { word: "かいしゃいん", romaji: "kaishayin", meaning: "Office employee", meaningNepali: "जागिरे" },
  { word: "いしゃ", romaji: "isha", meaning: "Doctor", meaningNepali: "डाक्टर" },
  { word: "けいさつかん", romaji: "keisatsukan", meaning: "Police officer", meaningNepali: "प्रहरी" },
  { word: "かぞく", romaji: "kazoku", meaning: "Family", meaningNepali: "परिवार" },
  { word: "ちち", romaji: "chichi", meaning: "Father", meaningNepali: "बुवा" },
  { word: "はは", romaji: "haha", meaning: "Mother", meaningNepali: "आमा" },
  { word: "おとうさん", romaji: "otousan", meaning: "Father (polite)", meaningNepali: "बुवा (आदरार्थी)" },
  { word: "おかあさん", romaji: "okaasan", meaning: "Mother (polite)", meaningNepali: "आमा (आदरार्थी)" },
  { word: "あに", romaji: "ani", meaning: "Older brother", meaningNepali: "दाजु" },
  { word: "あね", romaji: "ane", meaning: "Older sister", meaningNepali: "दिदी" },
  { word: "おとうと", romaji: "otouto", meaning: "Younger brother", meaningNepali: "भाई" },
  { word: "いもうと", romaji: "imouto", meaning: "Younger sister", meaningNepali: "बहिनी" },

  // Places & Infrastructure
  { word: "うち", romaji: "uchi", meaning: "Home / House", meaningNepali: "घर" },
  { word: "へや", romaji: "heya", meaning: "Room", meaningNepali: "कोठा" },
  { word: "がっこう", romaji: "gakkou", meaning: "School", meaningNepali: "विद्यालय" },
  { word: "きょうしつ", romaji: "kyoushitsu", meaning: "Classroom", meaningNepali: "कक्षाकोठा" },
  { word: "しょくどう", romaji: "shokudou", meaning: "Dining hall", meaningNepali: "चमेनागृह" },
  { word: "としょかん", romaji: "toshokan", meaning: "Library", meaningNepali: "पुस्तकालय" },
  { word: "びょういん", romaji: "byouin", meaning: "Hospital", meaningNepali: "अस्पताल" },
  { word: "えき", romaji: "eki", meaning: "Station", meaningNepali: "स्टेशन" },
  { word: "ぎんこう", romaji: "ginkou", meaning: "Bank", meaningNepali: "बैंक" },
  { word: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "Post office", meaningNepali: "हुलाक" },
  { word: "みせ", romaji: "mise", meaning: "Shop / Store", meaningNepali: "पसल" },
  { word: "レストラン", romaji: "resutoran", meaning: "Restaurant", meaningNepali: "रेस्टुरेन्ट" },
  { word: "ホテル", romaji: "hoteru", meaning: "Hotel", meaningNepali: "होटल" },
  { word: "こうえん", romaji: "kouen", meaning: "Park", meaningNepali: "पार्क" },
  { word: "トイレ", romaji: "toire", meaning: "Restroom", meaningNepali: "शौचालय" },
  { word: "デパート", romaji: "depaato", meaning: "Department store", meaningNepali: "डिपार्टमेन्ट स्टोर" },
  { word: "スーパー", romaji: "suupaa", meaning: "Supermarket", meaningNepali: "सुपरमार्केट" },

  // Animals & Objects
  { word: "いぬ", romaji: "inu", meaning: "Dog", meaningNepali: "कुकुर" },
  { word: "ねこ", romaji: "neko", meaning: "Cat", meaningNepali: "बिरालो" },
  { word: "とり", romaji: "tori", meaning: "Bird", meaningNepali: "चरा" },
  { word: "さかな", romaji: "sakana", meaning: "Fish", meaningNepali: "माछा" },
  { word: "くるま", romaji: "kuruma", meaning: "Car", meaningNepali: "गाडी" },
  { word: "じてんしゃ", romaji: "jitensha", meaning: "Bicycle", meaningNepali: "साइकल" },
  { word: "でんしゃ", romaji: "densha", meaning: "Train", meaningNepali: "रेल" },
  { word: "ひこうき", romaji: "hikouki", meaning: "Airplane", meaningNepali: "हवाइजहाज" },
  { word: "バス", romaji: "basu", meaning: "Bus", meaningNepali: "बस" },
  { word: "タクシー", romaji: "takushii", meaning: "Taxi", meaningNepali: "ट्याक्सी" },
  { word: "きっぷ", romaji: "kippu", meaning: "Ticket", meaningNepali: "टिकट" },
  { word: "かばん", romaji: "kaban", meaning: "Bag", meaningNepali: "झोला" },
  { word: "ほん", romaji: "hon", meaning: "Book", meaningNepali: "किताब" },
  { word: "ノート", romaji: "nooto", meaning: "Notebook", meaningNepali: "कापी" },
  { word: "ペン", romaji: "pen", meaning: "Pen", meaningNepali: "कलम" },
  { word: "えんぴつ", romaji: "enpitsu", meaning: "Pencil", meaningNepali: "पेन्सिल" },
  { word: "じしょ", romaji: "jisho", meaning: "Dictionary", meaningNepali: "शब्दकोश" },
  { word: "しんぶん", romaji: "shinbun", meaning: "Newspaper", meaningNepali: "समाचार पत्र" },
  { word: "てがみ", romaji: "tegami", meaning: "Letter", meaningNepali: "चिठ्ठी" },
  { word: "でんわ", romaji: "denwa", meaning: "Phone", meaningNepali: "फोन" },
  { word: "ケータイ", romaji: "keetai", meaning: "Mobile phone", meaningNepali: "मोबाइल" },
  { word: "テレビ", romaji: "terebi", meaning: "TV", meaningNepali: "टेलिभिजन" },
  { word: "パソコン", romaji: "pasokon", meaning: "PC / Computer", meaningNepali: "कम्प्युटर" },
  { word: "カメラ", romaji: "kamera", meaning: "Camera", meaningNepali: "क्यामेरा" },
  { word: "とけい", romaji: "tokei", meaning: "Clock / Watch", meaningNepali: "घडी" },
  { word: "かぎ", romaji: "kagi", meaning: "Key", meaningNepali: "साँचो" },
  { word: "おかね", romaji: "okane", meaning: "Money", meaningNepali: "पैसा" },

  // Food & Drink
  { word: "みず", romaji: "mizu", meaning: "Water", meaningNepali: "पानी" },
  { word: "おちゃ", romaji: "ocha", meaning: "Green tea", meaningNepali: "चिया" },
  { word: "コーヒー", romaji: "koohii", meaning: "Coffee", meaningNepali: "कफी" },
  { word: "ごはん", romaji: "gohan", meaning: "Rice / Meal", meaningNepali: "खाना" },
  { word: "パン", romaji: "pan", meaning: "Bread", meaningNepali: "पाउरोटी" },
  { word: "にく", romaji: "niku", meaning: "Meat", meaningNepali: "मासु" },
  { word: "やさい", romaji: "yasai", meaning: "Vegetable", meaningNepali: "तरकारी" },
  { word: "くだもの", romaji: "kudamono", meaning: "Fruit", meaningNepali: "फलफूल" },
  { word: "りんご", romaji: "ringo", meaning: "Apple", meaningNepali: "स्याउ" },
  { word: "みかん", romaji: "mikan", meaning: "Mandarin orange", meaningNepali: "सुन्तला" },
  { word: "バナナ", romaji: "banana", meaning: "Banana", meaningNepali: "केरा" },
  { word: "たまご", romaji: "tamago", meaning: "Egg", meaningNepali: "अण्डा" },
  { word: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "Milk", meaningNepali: "दूध" },
  { word: "おさけ", romaji: "osake", meaning: "Alcohol / Sake", meaningNepali: "रक्सी" },
  { word: "ビール", romaji: "biiru", meaning: "Beer", meaningNepali: "बियर" },
  { word: "あさごはん", romaji: "asagohan", meaning: "Breakfast", meaningNepali: "बिहानको खाना" },
  { word: "ひるごはん", romaji: "hirugohan", meaning: "Lunch", meaningNepali: "दिउँसोको खाना" },
  { word: "ばんごはん", romaji: "bangohan", meaning: "Dinner", meaningNepali: "बेलुकीको खाना" },

  // Household & Nature
  { word: "つくえ", romaji: "tsukue", meaning: "Desk", meaningNepali: "टेबल" },
  { word: "いす", romaji: "isu", meaning: "Chair", meaningNepali: "कुर्सी" },
  { word: "ベッド", romaji: "beddo", meaning: "Bed", meaningNepali: "ओछ्यान" },
  { word: "はな", romaji: "hana", meaning: "Flower", meaningNepali: "फूल" },
  { word: "うみ", romaji: "umi", meaning: "Sea / Ocean", meaningNepali: "समुद्र" },
  { word: "かわ", romaji: "kawa", meaning: "River", meaningNepali: "नदी" },
  { word: "やま", romaji: "yama", meaning: "Mountain", meaningNepali: "पहाड" },
  { word: "そら", romaji: "sora", meaning: "Sky", meaningNepali: "आकाश" },
  { word: "あめ", romaji: "ame", meaning: "Rain", meaningNepali: "पानी (वर्षा)" },
  { word: "ゆき", romaji: "yuki", meaning: "Snow", meaningNepali: "हिउँ" },
  { word: "かぜ", romaji: "kaze", meaning: "Wind", meaningNepali: "हावा" },
  { word: "はれ", romaji: "hare", meaning: "Sunny weather", meaningNepali: "सफा मौसम" },
  { word: "くもり", romaji: "kumori", meaning: "Cloudy weather", meaningNepali: "बादल लागेको" },

  // Adjectives
  { word: "あつい", romaji: "atsui", meaning: "Hot", meaningNepali: "गर्मी / तातो" },
  { word: "さむい", romaji: "samui", meaning: "Cold (weather)", meaningNepali: "जाडो" },
  { word: "つめたい", romaji: "tsumetai", meaning: "Cold (touch)", meaningNepali: "चिसो" },
  { word: "すずしい", romaji: "suzushii", meaning: "Cool (weather)", meaningNepali: "सितल" },
  { word: "あたたかい", romaji: "atatakai", meaning: "Warm", meaningNepali: "न्यानो" },
  { word: "おおきい", romaji: "ookii", meaning: "Big", meaningNepali: "ठूलो" },
  { word: "ちいさい", romaji: "chiisai", meaning: "Small", meaningNepali: "सानो" },
  { word: "あたらしい", romaji: "atarashii", meaning: "New", meaningNepali: "नयाँ" },
  { word: "ふるい", romaji: "furui", meaning: "Old", meaningNepali: "पुरानो" },
  { word: "いい", romaji: "ii", meaning: "Good", meaningNepali: "राम्रो" },
  { word: "わるい", romaji: "warui", meaning: "Bad", meaningNepali: "नराम्रो" },
  { word: "むずかしい", romaji: "muzukashii", meaning: "Difficult", meaningNepali: "गाह्रो" },
  { word: "やさしい", romaji: "yasashii", meaning: "Easy / Kind", meaningNepali: "सजिलो / दयालु" },
  { word: "たかい", romaji: "takai", meaning: "High / Expensive", meaningNepali: "अग्लो / महँगो" },
  { word: "やすい", romaji: "yasui", meaning: "Cheap", meaningNepali: "सस्तो" },
  { word: "ひくい", romaji: "hikui", meaning: "Low", meaningNepali: "होचो" },
  { word: "おいしい", romaji: "oishii", meaning: "Delicious", meaningNepali: "मिठो" },
  { word: "あまい", romaji: "amai", meaning: "Sweet", meaningNepali: "गुलियो" },
  { word: "からい", romaji: "karai", meaning: "Spicy", meaningNepali: "पिरो" },
  { word: "いそがしい", romaji: "isogashii", meaning: "Busy", meaningNepali: "व्यस्त" },
  { word: "たのしい", romaji: "tanoshii", meaning: "Fun / Enjoyable", meaningNepali: "रमाइलो" },
  { word: "おもしろい", romaji: "omoshiroi", meaning: "Interesting", meaningNepali: "रोचक / चाखलाग्दो" },
  { word: "つまらない", romaji: "tsumaranai", meaning: "Boring", meaningNepali: "दिक्क लाग्दो" },
  { word: "ちかい", romaji: "chikai", meaning: "Near / Close", meaningNepali: "नजिक" },
  { word: "とおい", romaji: "tooi", meaning: "Far", meaningNepali: "टाढा" },
  { word: "はやい", romaji: "hayai", meaning: "Fast / Early", meaningNepali: "चाँडो / छिटो" },
  { word: "おそい", romaji: "osoi", meaning: "Slow / Late", meaningNepali: "ढिलो" },
  { word: "きれい", romaji: "kirei", meaning: "Beautiful / Clean", meaningNepali: "सुन्दर / सफा" },
  { word: "しずか", romaji: "shizuka", meaning: "Quiet", meaningNepali: "शान्त" },
  { word: "にぎやか", romaji: "nigiyaka", meaning: "Lively", meaningNepali: "चहलपहल भएको" },
  { word: "べんり", romaji: "benri", meaning: "Convenient", meaningNepali: "सुविधाजनक" },
  { word: "ひま", romaji: "hima", meaning: "Free time", meaningNepali: "फुर्सद" },
  { word: "すき", romaji: "suki", meaning: "Like / Friendly", meaningNepali: "मनपर्ने" },
  { word: "きらい", romaji: "kirai", meaning: "Dislike / Hate", meaningNepali: "मन नपर्ने" },
  { word: "じょうず", romaji: "jouzu", meaning: "Skilled / Good at", meaningNepali: "सिपालु" },
  { word: "へた", romaji: "heta", meaning: "Unskilled / Poor at", meaningNepali: "नसिपालु" },
  { word: "かんたん", romaji: "kantan", meaning: "Easy / Simple", meaningNepali: "सजिलो / सरल" },

  // Basic Verbs
  { word: "いく", romaji: "iku", meaning: "To go", meaningNepali: "जानु" },
  { word: "くる", romaji: "kuru", meaning: "To come", meaningNepali: "आउनु" },
  { word: "かえる", romaji: "kaeru", meaning: "To return", meaningNepali: "फर्कनु" },
  { word: "たべる", romaji: "taberu", meaning: "To eat", meaningNepali: "कानु" }, // wait, user had "eating" -> let's make sure translation is right. "खानू"
  { word: "のむ", romaji: "nomu", meaning: "To drink", meaningNepali: "पिउनु" },
  { word: "みる", romaji: "miru", meaning: "To see / watch", meaningNepali: "हेर्नु" },
  { word: "きく", romaji: "kiku", meaning: "To hear / listen / ask", meaningNepali: "सुन्नु" },
  { word: "よむ", romaji: "yomu", meaning: "To read", meaningNepali: "पढ्नु" },
  { word: "かく", romaji: "kaku", meaning: "To write", meaningNepali: "लेख्नु" },
  { word: "はなす", romaji: "hanasu", meaning: "To speak", meaningNepali: "बोल्नु" },
  { word: "かう", romaji: "kau", meaning: "To buy", meaningNepali: "किन्नु" },
  { word: "する", romaji: "suru", meaning: "To do", meaningNepali: "गर्नु" },
  { word: "べんきょうする", romaji: "benkyou suru", meaning: "To study", meaningNepali: "अध्ययन गर्नु" },
  { word: "はたらく", romaji: "hataraku", meaning: "To work", meaningNepali: "काम गर्नु" },
  { word: "やすむ", romaji: "yasumu", meaning: "To rest / take a holiday", meaningNepali: "आराम गर्नु / बिदा लिनु" },
  { word: "あそぶ", romaji: "asobu", meaning: "To play / hang out", meaningNepali: "खेल्नु / घुम्नु" },
  { word: "あう", romaji: "au", meaning: "To meet", meaningNepali: "भेट्नु" },
  { word: "およぐ", romaji: "oyogu", meaning: "To swim", meaningNepali: "पौडिनु" },
  { word: "つくる", romaji: "tsukuru", meaning: "To make / create", meaningNepali: "बनाउनु" },
  { word: "つかう", romaji: "tsukau", meaning: "To use", meaningNepali: "प्रयोग गर्नु" },
  { word: "まつ", romaji: "matsu", meaning: "To wait", meaningNepali: "पर्खनु" },
  { word: "よぶ", romaji: "yobu", meaning: "To call", meaningNepali: "बोलाउनु" },
  { word: "はしる", romaji: "hashiru", meaning: "To run", meaningNepali: "दौडिनु" },
  { word: "あるく", romaji: "aruku", meaning: "To walk", meaningNepali: "हिँड्नु" },
  { word: "のる", romaji: "noru", meaning: "To ride", meaningNepali: "चढ्नु (गाडीमा)" },
  { word: "おりる", romaji: "oriru", meaning: "To get off", meaningNepali: "ओर्लनु" },
  { word: "はいる", romaji: "hairu", meaning: "To enter / go in", meaningNepali: "पस्नु" },
  { word: "でる", romaji: "deru", meaning: "To exit / leave", meaningNepali: "निस्कनु" }
];
