// ============================================================
// 300 COMMON HIGH-FREQUENCY KOREAN WORDS DATASET (1 TO 300 COMPLETE)
// Complete EPS-TOPIK, TOPIK I & Daily Survival Korean
// Every word includes Hangul, Romanization, English, and Nepali
// ============================================================

export interface KoreanCommonWord {
  id: number;
  word: string;
  romanization: string;
  meaning: string;
  meaningNepali: string;
  category: 'GREETINGS' | 'NUMBERS' | 'WORKPLACE' | 'DAILY' | 'FOOD' | 'TRANSPORT' | 'HEALTH' | 'SHOPPING' | 'VERBS' | 'ADJECTIVES';
  example?: string;
  exampleNepali?: string;
}

export const KOREAN_300_COMMON_WORDS: KoreanCommonWord[] = [
  // ── 1. GREETINGS & ESSENTIAL COURTESY (1–25) ──
  { id: 1, word: '안녕하세요', romanization: 'Annyeong-haseyo', meaning: 'Hello / How are you?', meaningNepali: 'नमस्ते / हालखबर के छ?', category: 'GREETINGS' },
  { id: 2, word: '감사합니다', romanization: 'Gamsa-hamnida', meaning: 'Thank you (formal)', meaningNepali: 'धन्यवाद (औपचारिक)', category: 'GREETINGS' },
  { id: 3, word: '고맙습니다', romanization: 'Gomap-seumnida', meaning: 'Thank you', meaningNepali: 'धन्यवाद', category: 'GREETINGS' },
  { id: 4, word: '죄송합니다', romanization: 'Joesong-hamnida', meaning: 'I am sorry (formal)', meaningNepali: 'माफ गर्नुहोस् (औपचारिक)', category: 'GREETINGS' },
  { id: 5, word: '미안합니다', romanization: 'Mian-hamnida', meaning: 'I am sorry', meaningNepali: 'माफ गर्नुहोस्', category: 'GREETINGS' },
  { id: 6, word: '안녕히 계세요', romanization: 'Annyeong-hi gyeseyo', meaning: 'Goodbye (to person staying)', meaningNepali: 'राम्रोसँग बस्नुहोस्', category: 'GREETINGS' },
  { id: 7, word: '안녕히 가세요', romanization: 'Annyeong-hi gaseyo', meaning: 'Goodbye (to person leaving)', meaningNepali: 'राम्रोसँग जानुहोस्', category: 'GREETINGS' },
  { id: 8, word: '처음 뵙겠습니다', romanization: 'Cheoeum boep-gesseumnida', meaning: 'Nice to meet you (first time)', meaningNepali: 'तपाईंलाई भेटेर खुसी लाग्यो (पहिलो पटक)', category: 'GREETINGS' },
  { id: 9, word: '반갑습니다', romanization: 'Ban-gap-seumnida', meaning: 'Glad to meet you', meaningNepali: 'भेटेर खुसी लाग्यो', category: 'GREETINGS' },
  { id: 10, word: '네 / 예', romanization: 'Ne / Ye', meaning: 'Yes', meaningNepali: 'हजुर / हो', category: 'GREETINGS' },
  { id: 11, word: '아니요', romanization: 'Aniyo', meaning: 'No', meaningNepali: 'होइन / छैन', category: 'GREETINGS' },
  { id: 12, word: '괜찮아요', romanization: 'Gwaenchan-ayo', meaning: 'It is okay / I am fine', meaningNepali: 'ठिकै छ / केही फरक पर्दैन', category: 'GREETINGS' },
  { id: 13, word: '수고하셨습니다', romanization: 'Sugo-hasyeosseumnida', meaning: 'Thank you for your hard work', meaningNepali: 'कडा परिश्रमको लागि धन्यवाद', category: 'GREETINGS' },
  { id: 14, word: '실례합니다', romanization: 'Sillye-hamnida', meaning: 'Excuse me', meaningNepali: 'क्षमा गर्नुहोस् / सुन्नुहोस् त', category: 'GREETINGS' },
  { id: 15, word: '어머나 / 세상에', romanization: 'Eomena / Sesang-e', meaning: 'Oh my goodness!', meaningNepali: 'अरे बाफ रे!', category: 'GREETINGS' },
  { id: 16, word: '주말 잘 보내세요', romanization: 'Jumal jal bonaeseyo', meaning: 'Have a good weekend', meaningNepali: 'सप्ताहन्त राम्रोसँग बिताउनुहोस्', category: 'GREETINGS' },
  { id: 17, word: '축하합니다', romanization: 'Chuk-ha-hamnida', meaning: 'Congratulations', meaningNepali: 'बधाई छ', category: 'GREETINGS' },
  { id: 18, word: '어서 오세요', romanization: 'Eoseo oseyo', meaning: 'Welcome!', meaningNepali: 'स्वागत छ!', category: 'GREETINGS' },
  { id: 19, word: '잘 부탁드립니다', romanization: 'Jal bu-tak-deurimnida', meaning: 'Please treat me well', meaningNepali: 'कृपया राम्रो सहयोग गर्नुहोला', category: 'GREETINGS' },
  { id: 20, word: '또 만나요', romanization: 'Tto mannayo', meaning: 'See you again', meaningNepali: 'फेरि भेटौँला', category: 'GREETINGS' },
  { id: 21, word: '잘 자요', romanization: 'Jal jayo', meaning: 'Good night', meaningNepali: 'शुभ रात्री', category: 'GREETINGS' },
  { id: 22, word: '좋은 아침입니다', romanization: 'Joheun achim-imnida', meaning: 'Good morning', meaningNepali: 'शुभ प्रभात', category: 'GREETINGS' },
  { id: 23, word: '맛있게 드세요', romanization: 'Masitge deuseyo', meaning: 'Bon appetit / Enjoy your meal', meaningNepali: 'मीठो गरी खानुहोस्', category: 'GREETINGS' },
  { id: 24, word: '잘 먹었습니다', romanization: 'Jal meogeosseumnida', meaning: 'Thank you for the meal', meaningNepali: 'मीठो खानाको लागि धन्यवाद', category: 'GREETINGS' },
  { id: 25, word: '오랜만이에요', romanization: 'Oraenman-ieyo', meaning: 'Long time no see', meaningNepali: 'धेरै समयपछि भेट भयो', category: 'GREETINGS' },

  // ── 2. NUMBERS & TIME (26–60) ──
  { id: 26, word: '하나 / 일', romanization: 'Hana / Il', meaning: 'One (1)', meaningNepali: 'एक (१)', category: 'NUMBERS' },
  { id: 27, word: '둘 / 이', romanization: 'Dul / I', meaning: 'Two (2)', meaningNepali: 'दुई (२)', category: 'NUMBERS' },
  { id: 28, word: '셋 / 삼', romanization: 'Set / Sam', meaning: 'Three (3)', meaningNepali: 'तीन (३)', category: 'NUMBERS' },
  { id: 29, word: '넷 / 사', romanization: 'Net / Sa', meaning: 'Four (4)', meaningNepali: 'चार (४)', category: 'NUMBERS' },
  { id: 30, word: '다섯 / 오', romanization: 'Daseot / O', meaning: 'Five (5)', meaningNepali: 'पाँच (५)', category: 'NUMBERS' },
  { id: 31, word: '여섯 / 육', romanization: 'Yeoseot / Yuk', meaning: 'Six (6)', meaningNepali: 'छ (६)', category: 'NUMBERS' },
  { id: 32, word: '일곱 / 칠', romanization: 'Ilgop / Chil', meaning: 'Seven (7)', meaningNepali: 'सात (७)', category: 'NUMBERS' },
  { id: 33, word: '여덟 / 팔', romanization: 'Yeodeol / Pal', meaning: 'Eight (8)', meaningNepali: 'आठ (८)', category: 'NUMBERS' },
  { id: 34, word: '아홉 / 구', romanization: 'Ahop / Gu', meaning: 'Nine (9)', meaningNepali: 'नौ (९)', category: 'NUMBERS' },
  { id: 35, word: '열 / 십', romanization: 'Yeol / Sip', meaning: 'Ten (10)', meaningNepali: 'दस (१०)', category: 'NUMBERS' },
  { id: 36, word: '백', romanization: 'Baek', meaning: 'Hundred (100)', meaningNepali: 'सय (१००)', category: 'NUMBERS' },
  { id: 37, word: '천', romanization: 'Cheon', meaning: 'Thousand (1,000)', meaningNepali: 'हजार (१,०००)', category: 'NUMBERS' },
  { id: 38, word: '만', romanization: 'Man', meaning: 'Ten Thousand (10,000)', meaningNepali: 'दस हजार (१०,०००)', category: 'NUMBERS' },
  { id: 39, word: '오늘', romanization: 'Oneul', meaning: 'Today', meaningNepali: 'आज', category: 'NUMBERS' },
  { id: 40, word: '내일', romanization: 'Naeil', meaning: 'Tomorrow', meaningNepali: 'भोलि', category: 'NUMBERS' },
  { id: 41, word: '어제', romanization: 'Eoje', meaning: 'Yesterday', meaningNepali: 'हिजो', category: 'NUMBERS' },
  { id: 42, word: '지금', romanization: 'Jigeum', meaning: 'Now', meaningNepali: 'अहिले', category: 'NUMBERS' },
  { id: 43, word: '아침', romanization: 'Achim', meaning: 'Morning / Breakfast', meaningNepali: 'बिहान / बिहानको खाना', category: 'NUMBERS' },
  { id: 44, word: '점심', romanization: 'Jeomsim', meaning: 'Afternoon / Lunch', meaningNepali: 'दिउँसो / दिउँसोको खाना', category: 'NUMBERS' },
  { id: 45, word: '저녁', romanization: 'Jeonyeok', meaning: 'Evening / Dinner', meaningNepali: 'साँझ / बेलुकाको खाना', category: 'NUMBERS' },
  { id: 46, word: '새벽', romanization: 'Saebyeok', meaning: 'Dawn / Early morning', meaningNepali: 'प्रत्युष / मिर्मिरे बिहान', category: 'NUMBERS' },
  { id: 47, word: '월요일', romanization: 'Woryoil', meaning: 'Monday', meaningNepali: 'सोमबार', category: 'NUMBERS' },
  { id: 48, word: '화요일', romanization: 'Hwayoil', meaning: 'Tuesday', meaningNepali: 'मंगलबार', category: 'NUMBERS' },
  { id: 49, word: '수요일', romanization: 'Suyoil', meaning: 'Wednesday', meaningNepali: 'बुधबार', category: 'NUMBERS' },
  { id: 50, word: '목요일', romanization: 'Mokyoil', meaning: 'Thursday', meaningNepali: 'बिहीबार', category: 'NUMBERS' },
  { id: 51, word: '금요일', romanization: 'Geumyoil', meaning: 'Friday', meaningNepali: 'शुक्रबार', category: 'NUMBERS' },
  { id: 52, word: '토요일', romanization: 'Toyoil', meaning: 'Saturday', meaningNepali: 'शनिबार', category: 'NUMBERS' },
  { id: 53, word: '일요일', romanization: 'Iryoil', meaning: 'Sunday', meaningNepali: 'आइतबार', category: 'NUMBERS' },
  { id: 54, word: '이번 주', romanization: 'Ibeon ju', meaning: 'This week', meaningNepali: 'यो हप्ता', category: 'NUMBERS' },
  { id: 55, word: '다음 주', romanization: 'Da-eum ju', meaning: 'Next week', meaningNepali: 'आउने हप्ता', category: 'NUMBERS' },
  { id: 56, word: '지난 주', romanization: 'Jinan ju', meaning: 'Last week', meaningNepali: 'गएको हप्ता', category: 'NUMBERS' },
  { id: 57, word: '올해 / 금년', romanization: 'Olhae / Geumnyeon', meaning: 'This year', meaningNepali: 'यो वर्ष', category: 'NUMBERS' },
  { id: 58, word: '내년', romanization: 'Naenyeon', meaning: 'Next year', meaningNepali: 'आउने वर्ष', category: 'NUMBERS' },
  { id: 59, word: '작년', romanization: 'Jangnyeon', meaning: 'Last year', meaningNepali: 'गएको वर्ष', category: 'NUMBERS' },
  { id: 60, word: '시 / 분 / 초', romanization: 'Si / Bun / Cho', meaning: 'Hour / Minute / Second', meaningNepali: 'बजे / मिनेट / सेकेन्ड', category: 'NUMBERS' },

  // ── 3. WORKPLACE & EPS SAFETY (61–100) ──
  { id: 61, word: '공장', romanization: 'Gongjang', meaning: 'Factory', meaningNepali: 'कारखाना / फ्याक्ट्री', category: 'WORKPLACE' },
  { id: 62, word: '회사', romanization: 'Hoesa', meaning: 'Company / Office', meaningNepali: 'कम्पनी / कार्यालय', category: 'WORKPLACE' },
  { id: 63, word: '작업장', romanization: 'Jageopjang', meaning: 'Worksite / Workplace', meaningNepali: 'कार्यस्थल', category: 'WORKPLACE' },
  { id: 64, word: '사장님', romanization: 'Sajangnim', meaning: 'Company President / Boss', meaningNepali: 'साहुजी / मालिक', category: 'WORKPLACE' },
  { id: 65, word: '반장님', romanization: 'Banjangnim', meaning: 'Foreman / Supervisor', meaningNepali: 'फोरम्यान / क्याप्टेन', category: 'WORKPLACE' },
  { id: 66, word: '동료', romanization: 'Dongryeo', meaning: 'Co-worker / Colleague', meaningNepali: 'सहकर्मी', category: 'WORKPLACE' },
  { id: 67, word: '월급', romanization: 'Wolgeup', meaning: 'Monthly Salary', meaningNepali: 'मासिक तलब', category: 'WORKPLACE' },
  { id: 68, word: '수당', romanization: 'Sudang', meaning: 'Allowance / Bonus pay', meaningNepali: 'भत्ता / अतिरिक्त पैसा', category: 'WORKPLACE' },
  { id: 69, word: '안전모', romanization: 'Anjeonmo', meaning: 'Safety Helmet', meaningNepali: 'सुरक्षा टोपी (हेल्मेट)', category: 'WORKPLACE' },
  { id: 70, word: '안전화', romanization: 'Anjeonhwa', meaning: 'Safety Shoes', meaningNepali: 'सुरक्षा जुत्ता', category: 'WORKPLACE' },
  { id: 71, word: '보호구', romanization: 'Bohogu', meaning: 'Protective Equipment', meaningNepali: 'सुरक्षात्मक उपकरणहरू', category: 'WORKPLACE' },
  { id: 72, word: '마스크', romanization: 'Maseukeu', meaning: 'Face Mask', meaningNepali: 'मास्क', category: 'WORKPLACE' },
  { id: 73, word: '장갑', romanization: 'Janggap', meaning: 'Gloves', meaningNepali: 'पन्जा', category: 'WORKPLACE' },
  { id: 74, word: '기계', romanization: 'Gigye', meaning: 'Machine / Machinery', meaningNepali: 'मेसिन / उपकरण', category: 'WORKPLACE' },
  { id: 75, word: '스위치', romanization: 'Seuwichi', meaning: 'Switch', meaningNepali: 'स्वीच', category: 'WORKPLACE' },
  { id: 76, word: '위험', romanization: 'Wiheom', meaning: 'Danger / Hazardous', meaningNepali: 'खतरा / जोखिम', category: 'WORKPLACE' },
  { id: 77, word: '주의', romanization: 'Jui', meaning: 'Caution / Warning', meaningNepali: 'सावधानी', category: 'WORKPLACE' },
  { id: 78, word: '금지', romanization: 'Geumji', meaning: 'Prohibition / Forbidden', meaningNepali: 'निषेध / मनाही', category: 'WORKPLACE' },
  { id: 79, word: '비상구', romanization: 'Bisang-gu', meaning: 'Emergency Exit', meaningNepali: 'आकस्मिक निकास', category: 'WORKPLACE' },
  { id: 80, word: '소화기', romanization: 'Sohwagi', meaning: 'Fire Extinguisher', meaningNepali: 'अग्निशामक यन्त्र', category: 'WORKPLACE' },
  { id: 81, word: '사고', romanization: 'Sago', meaning: 'Accident', meaningNepali: 'दुर्घटना', category: 'WORKPLACE' },
  { id: 82, word: '부상', romanization: 'Busang', meaning: 'Injury', meaningNepali: 'चोटपटक', category: 'WORKPLACE' },
  { id: 83, word: '휴가', romanization: 'Hyuga', meaning: 'Vacation / Leave', meaningNepali: 'बिदा', category: 'WORKPLACE' },
  { id: 84, word: '병가', romanization: 'Byeong-ga', meaning: 'Sick Leave', meaningNepali: 'बिरामी बिदा', category: 'WORKPLACE' },
  { id: 85, word: '잔업', romanization: 'Janeop', meaning: 'Overtime Work', meaningNepali: 'अतिरिक्त काम (ओभरटाइम)', category: 'WORKPLACE' },
  { id: 86, word: '야간 근무', romanization: 'Yagan geunmu', meaning: 'Night Shift Work', meaningNepali: 'रात्रिकालीन काम', category: 'WORKPLACE' },
  { id: 87, word: '퇴근', romanization: 'Toe-geun', meaning: 'Leaving work / Clocking out', meaningNepali: 'कामबाट छुट्टी', category: 'WORKPLACE' },
  { id: 88, word: '출근', romanization: 'Chul-geun', meaning: 'Going to work / Clocking in', meaningNepali: 'काममा उपस्थित हुनु', category: 'WORKPLACE' },
  { id: 89, word: '계약서', romanization: 'Geyakseo', meaning: 'Contract paper', meaningNepali: 'सम्झौता पत्र', category: 'WORKPLACE' },
  { id: 90, word: '비자', romanization: 'Bija', meaning: 'Visa', meaningNepali: 'भिसा', category: 'WORKPLACE' },
  { id: 91, word: '여권', romanization: 'Yeogwon', meaning: 'Passport', meaningNepali: 'राहदानी (पासपोर्ट)', category: 'WORKPLACE' },
  { id: 92, word: '신분증', romanization: 'Sinbunjeung', meaning: 'ID Card', meaningNepali: 'परिचयपत्र', category: 'WORKPLACE' },
  { id: 93, word: '외국인등록증', romanization: 'Oegug-in deungnokjeung', meaning: 'Alien Registration Card', meaningNepali: 'विदेशी दर्ता कार्ड', category: 'WORKPLACE' },
  { id: 94, word: '도구 / 공구', romanization: 'Dogu / Gong-gu', meaning: 'Tools / Hardware', meaningNepali: 'औजार / उपकरण', category: 'WORKPLACE' },
  { id: 95, word: '망치', romanization: 'Mangchi', meaning: 'Hammer', meaningNepali: 'हतौडा', category: 'WORKPLACE' },
  { id: 96, word: '드라이버', romanization: 'Deuraibeo', meaning: 'Screwdriver', meaningNepali: 'पेचकस (ड्राइभर)', category: 'WORKPLACE' },
  { id: 97, word: '펜치', romanization: 'Penchi', meaning: 'Pliers', meaningNepali: 'प्लायर्स (पिलास)', category: 'WORKPLACE' },
  { id: 98, word: '줄자', romanization: 'Julja', meaning: 'Measuring Tape', meaningNepali: 'नाप्ने टेप (फिता)', category: 'WORKPLACE' },
  { id: 99, word: '사다리', romanization: 'Sadari', meaning: 'Ladder', meaningNepali: 'भर्याङ', category: 'WORKPLACE' },
  { id: 100, word: '박스 / 상자', romanization: 'Bakseu / Sangja', meaning: 'Box / Carton', meaningNepali: 'बाकस / कार्टुन', category: 'WORKPLACE' },

  // ── 4. DAILY LIFE & PEOPLE (101–140) ──
  { id: 101, word: '사람', romanization: 'Saram', meaning: 'Person / Human', meaningNepali: 'मानिस / व्यक्ति', category: 'DAILY' },
  { id: 102, word: '친구', romanization: 'Chingu', meaning: 'Friend', meaningNepali: 'साथी', category: 'DAILY' },
  { id: 103, word: '가족', romanization: 'Gajok', meaning: 'Family', meaningNepali: 'परिवार', category: 'DAILY' },
  { id: 104, word: '아버지', romanization: 'Abeoji', meaning: 'Father', meaningNepali: 'बुबा', category: 'DAILY' },
  { id: 105, word: '어머니', romanization: 'Eomeoni', meaning: 'Mother', meaningNepali: 'आमा', category: 'DAILY' },
  { id: 106, word: '형 / 오빠', romanization: 'Hyeong / Oppa', meaning: 'Older brother', meaningNepali: 'दाजु', category: 'DAILY' },
  { id: 107, word: '누나 / 언니', romanization: 'Nuna / Eonni', meaning: 'Older sister', meaningNepali: 'दिदी', category: 'DAILY' },
  { id: 108, word: '동생', romanization: 'Dongsaeng', meaning: 'Younger sibling', meaningNepali: 'भाइ / बहिनी', category: 'DAILY' },
  { id: 109, word: '집', romanization: 'Jip', meaning: 'House / Home', meaningNepali: 'घर', category: 'DAILY' },
  { id: 110, word: '기숙사', romanization: 'Gisuksa', meaning: 'Dormitory', meaningNepali: 'हस्टल / आवास', category: 'DAILY' },
  { id: 111, word: '방', romanization: 'Bang', meaning: 'Room', meaningNepali: 'कोठा', category: 'DAILY' },
  { id: 112, word: '화장실', romanization: 'Hwajangsil', meaning: 'Restroom / Bathroom', meaningNepali: 'शौचालय', category: 'DAILY' },
  { id: 113, word: '식당', romanization: 'Sikdang', meaning: 'Restaurant / Cafeteria', meaningNepali: 'रेस्टुरेन्ट / भोजनालय', category: 'DAILY' },
  { id: 114, word: '병원', romanization: 'Byeong-won', meaning: 'Hospital / Clinic', meaningNepali: 'अस्पताल', category: 'DAILY' },
  { id: 115, word: '약국', romanization: 'Yakguk', meaning: 'Pharmacy', meaningNepali: 'औषधी पसल', category: 'DAILY' },
  { id: 116, word: '은행', romanization: 'Eunhaeng', meaning: 'Bank', meaningNepali: 'बैंक', category: 'DAILY' },
  { id: 117, word: '우체국', romanization: 'Ucheguk', meaning: 'Post Office', meaningNepali: 'हुलाक कार्यालय', category: 'DAILY' },
  { id: 118, word: '시장', romanization: 'Sijang', meaning: 'Market', meaningNepali: 'बजार', category: 'DAILY' },
  { id: 119, word: '마트', romanization: 'Mateu', meaning: 'Mart / Supermarket', meaningNepali: 'मार्केट / सुपरमार्केट', category: 'DAILY' },
  { id: 120, word: '편의점', romanization: 'Pyeon-uijeom', meaning: 'Convenience Store', meaningNepali: 'दैनिक उपभोग्य पसल', category: 'DAILY' },
  { id: 121, word: '학교', romanization: 'Hakgyo', meaning: 'School', meaningNepali: 'विद्यालय (स्कूल)', category: 'DAILY' },
  { id: 122, word: '선생님', romanization: 'Seonsaengnim', meaning: 'Teacher / Master', meaningNepali: 'शिक्षक / गुरु', category: 'DAILY' },
  { id: 123, word: '학생', romanization: 'Haksaeng', meaning: 'Student', meaningNepali: 'विद्यार्थी', category: 'DAILY' },
  { id: 124, word: '책', romanization: 'Chaek', meaning: 'Book', meaningNepali: 'किताब', category: 'DAILY' },
  { id: 125, word: '공책', romanization: 'Gongchaek', meaning: 'Notebook', meaningNepali: 'कपी / अभ्यास पुस्तिका', category: 'DAILY' },
  { id: 126, word: '볼펜 / 연필', romanization: 'Bolpen / Yeonpil', meaning: 'Pen / Pencil', meaningNepali: 'कलम / सिसाकलम', category: 'DAILY' },
  { id: 127, word: '시계', romanization: 'Sigye', meaning: 'Clock / Watch', meaningNepali: 'घडी', category: 'DAILY' },
  { id: 128, word: '지갑', romanization: 'Jigap', meaning: 'Wallet / Purse', meaningNepali: 'वॉलेट / वालेट', category: 'DAILY' },
  { id: 129, word: '가방', romanization: 'Gabang', meaning: 'Bag / Backpack', meaningNepali: 'झोला (बैग)', category: 'DAILY' },
  { id: 130, word: '휴대폰 / 스마트폰', romanization: 'Hyudaepon / Seumateupon', meaning: 'Mobile phone', meaningNepali: 'मोबाइल फोन', category: 'DAILY' },
  { id: 131, word: '컴퓨터', romanization: 'Keompyuteo', meaning: 'Computer', meaningNepali: 'कंप्यूटर', category: 'DAILY' },
  { id: 132, word: '옷', romanization: 'Ot', meaning: 'Clothes / Clothing', meaningNepali: 'कपडा', category: 'DAILY' },
  { id: 133, word: '신발', romanization: 'Sinbal', meaning: 'Shoes', meaningNepali: 'जुत्ता', category: 'DAILY' },
  { id: 134, word: '모자', romanization: 'Moja', meaning: 'Hat / Cap', meaningNepali: 'टोपी', category: 'DAILY' },
  { id: 135, word: '안경', romanization: 'Angyeong', meaning: 'Eyeglasses', meaningNepali: 'चश्मा', category: 'DAILY' },
  { id: 136, word: '우산', romanization: 'Usan', meaning: 'Umbrella', meaningNepali: 'छाता', category: 'DAILY' },
  { id: 137, word: '수건', romanization: 'Su-geon', meaning: 'Towel', meaningNepali: 'तौलिया', category: 'DAILY' },
  { id: 138, word: '비누', romanization: 'Binu', meaning: 'Soap', meaningNepali: 'साबुन', category: 'DAILY' },
  { id: 139, word: '치약 / 칫솔', romanization: 'Chiyak / Chitsol', meaning: 'Toothpaste / Toothbrush', meaningNepali: 'मञ्जन / ब्रस', category: 'DAILY' },
  { id: 140, word: '휴지', romanization: 'Hyuji', meaning: 'Tissue paper', meaningNepali: 'टिस्यु पेपर', category: 'DAILY' },

  // ── 5. FOOD & DRINK (141–175) ──
  { id: 141, word: '밥', romanization: 'Bap', meaning: 'Cooked Rice / Meal', meaningNepali: 'भात / खाना', category: 'FOOD' },
  { id: 142, word: '물', romanization: 'Mul', meaning: 'Water', meaningNepali: 'पानी', category: 'FOOD' },
  { id: 143, word: '고기', romanization: 'Gogi', meaning: 'Meat', meaningNepali: 'मासु', category: 'FOOD' },
  { id: 144, word: '돼지고기', romanization: 'Dwaejigogi', meaning: 'Pork', meaningNepali: 'सुँगुरको मासु', category: 'FOOD' },
  { id: 145, word: '소고기', romanization: 'Sogogi', meaning: 'Beef', meaningNepali: 'गाईको मासु', category: 'FOOD' },
  { id: 146, word: '닭고기', romanization: 'Dakgogi', meaning: 'Chicken Meat', meaningNepali: 'कुखुराको मासु', category: 'FOOD' },
  { id: 147, word: '생선', romanization: 'Saengseon', meaning: 'Fish', meaningNepali: 'माछा', category: 'FOOD' },
  { id: 148, word: '채소 / 야채', romanization: 'Chaeso / Yachae', meaning: 'Vegetable', meaningNepali: 'सागपात / तरकारी', category: 'FOOD' },
  { id: 149, word: '김치', romanization: 'Kimchi', meaning: 'Kimchi (Fermented cabbage)', meaningNepali: 'किम्ची (कोरियाली अचार)', category: 'FOOD' },
  { id: 150, word: '라면', romanization: 'Ramyeon', meaning: 'Instant Noodles (Ramen)', meaningNepali: 'चाउचाउ / चाउमिन', category: 'FOOD' },
  { id: 151, word: '빵', romanization: 'Ppang', meaning: 'Bread', meaningNepali: 'पाउरोटी', category: 'FOOD' },
  { id: 152, word: '계란 / 달걀', romanization: 'Gyeran / Dalgyal', meaning: 'Egg', meaningNepali: 'अण्डा', category: 'FOOD' },
  { id: 153, word: '우유', romanization: 'Uyu', meaning: 'Milk', meaningNepali: 'दूध', category: 'FOOD' },
  { id: 154, word: '커피', romanization: 'Keopi', meaning: 'Coffee', meaningNepali: 'कॉफी', category: 'FOOD' },
  { id: 155, word: '차', romanization: 'Cha', meaning: 'Tea', meaningNepali: 'चिया', category: 'FOOD' },
  { id: 156, word: '과일', romanization: 'Gwail', meaning: 'Fruit', meaningNepali: 'फलफूल', category: 'FOOD' },
  { id: 157, word: '사과', romanization: 'Sagwa', meaning: 'Apple', meaningNepali: 'स्याउ', category: 'FOOD' },
  { id: 158, word: '바나나', romanization: 'Banana', meaning: 'Banana', meaningNepali: 'केरा', category: 'FOOD' },
  { id: 159, word: '수박', romanization: 'Subak', meaning: 'Watermelon', meaningNepali: 'खरबुजा', category: 'FOOD' },
  { id: 160, word: '소금', romanization: 'Sogeum', meaning: 'Salt', meaningNepali: 'नुन', category: 'FOOD' },
  { id: 161, word: '설탕', romanization: 'Seoltang', meaning: 'Sugar', meaningNepali: 'चिनी', category: 'FOOD' },
  { id: 162, word: '간장', romanization: 'Ganjang', meaning: 'Soy sauce', meaningNepali: 'सोया सस', category: 'FOOD' },
  { id: 163, word: '고추장', romanization: 'Gochujang', meaning: 'Red chili paste', meaningNepali: 'खुर्सानीको पेस्ट', category: 'FOOD' },
  { id: 164, word: '기름', romanization: 'Gireum', meaning: 'Oil / Cooking oil', meaningNepali: 'तेल', category: 'FOOD' },
  { id: 165, word: '국 / 찌개', romanization: 'Guk / Jjigae', meaning: 'Soup / Stew', meaningNepali: 'झोल (सूप) / स्ट्यु', category: 'FOOD' },
  { id: 166, word: '불고기', romanization: 'Bulgogi', meaning: 'Grilled marinated meat', meaningNepali: 'बुल्गोगी (कोरियाली मासु डिश)', category: 'FOOD' },
  { id: 167, word: '비빔밥', romanization: 'Bibimbap', meaning: 'Mixed rice with veggies', meaningNepali: 'बिबिम्बाप (मिश्रित भात)', category: 'FOOD' },
  { id: 168, word: '만두', romanization: 'Mandu', meaning: 'Dumplings (Momo)', meaningNepali: 'ममो / डम्पलिंग', category: 'FOOD' },
  { id: 169, word: '음료수', romanization: 'Eumryosu', meaning: 'Beverage / Soft drink', meaningNepali: 'पेय पदार्थ (सफ्ट ड्रिंक)', category: 'FOOD' },
  { id: 170, word: '술 / 맥주 / 소주', romanization: 'Sul / Maekju / Soju', meaning: 'Alcohol / Beer / Soju', meaningNepali: 'रक्सी / बियर / सोजु', category: 'FOOD' },
  { id: 171, word: '숟가락', romanization: 'Sutgarak', meaning: 'Spoon', meaningNepali: 'चम्चा', category: 'FOOD' },
  { id: 172, word: '젓가락', romanization: 'Jeotgarak', meaning: 'Chopsticks', meaningNepali: 'चोपस्टिक्स (काँटा सट्टा)', category: 'FOOD' },
  { id: 173, word: '그릇', romanization: 'Geureot', meaning: 'Bowl / Dish', meaningNepali: 'बाटुलो (कटोरा / कचौरा)', category: 'FOOD' },
  { id: 174, word: '컵', romanization: 'Keop', meaning: 'Cup / Glass', meaningNepali: 'कप / गिलास', category: 'FOOD' },
  { id: 175, word: '메뉴판', romanization: 'Menyupan', meaning: 'Menu card', meaningNepali: 'मेनु कार्ड', category: 'FOOD' },

  // ── 6. TRANSPORT & DIRECTIONS (176–205) ──
  { id: 176, word: '차 / 자동차', romanization: 'Cha / Jadongcha', meaning: 'Car / Automobile', meaningNepali: 'गाडी / कार', category: 'TRANSPORT' },
  { id: 177, word: '버스', romanization: 'Beoseu', meaning: 'Bus', meaningNepali: 'बस', category: 'TRANSPORT' },
  { id: 178, word: '지하철', romanization: 'Jihacheol', meaning: 'Subway / Metro', meaningNepali: 'सबवे / भूमिगत रेल', category: 'TRANSPORT' },
  { id: 179, word: '기차', romanization: 'Gicha', meaning: 'Train', meaningNepali: 'रेलगाडी', category: 'TRANSPORT' },
  { id: 180, word: '택시', romanization: 'Taeksi', meaning: 'Taxi', meaningNepali: 'ट्याक्सी', category: 'TRANSPORT' },
  { id: 181, word: '비행기', romanization: 'Bihaenggi', meaning: 'Airplane', meaningNepali: 'हवाईजहाज', category: 'TRANSPORT' },
  { id: 182, word: '자전거', romanization: 'Jajeongeor', meaning: 'Bicycle', meaningNepali: 'साइकल', category: 'TRANSPORT' },
  { id: 183, word: '길', romanization: 'Gil', meaning: 'Road / Way / Path', meaningNepali: 'बाटो / सडक', category: 'TRANSPORT' },
  { id: 184, word: '위 / 아래', romanization: 'Wi / Arae', meaning: 'Above / Below', meaningNepali: 'माथि / तल', category: 'TRANSPORT' },
  { id: 185, word: '앞 / 뒤', romanization: 'Ap / Dwi', meaning: 'Front / Behind', meaningNepali: 'अगाडि / पछाडि', category: 'TRANSPORT' },
  { id: 186, word: '왼쪽 / 오른쪽', romanization: 'Oenjjok / Oreunjjok', meaning: 'Left / Right', meaningNepali: 'बायाँ / दायाँ', category: 'TRANSPORT' },
  { id: 187, word: '옆 / 근처', romanization: 'Yeop / Geuncheo', meaning: 'Beside / Nearby', meaningNepali: 'छेउमा / नजिक', category: 'TRANSPORT' },
  { id: 188, word: '직진', romanization: 'Jikjin', meaning: 'Go Straight', meaningNepali: 'सिधा अगाडि जानुहोस्', category: 'TRANSPORT' },
  { id: 189, word: '건너편', romanization: 'Geonneoppyeon', meaning: 'Across the street', meaningNepali: 'बाटो पारि', category: 'TRANSPORT' },
  { id: 190, word: '정류장', romanization: 'Jeongryujang', meaning: 'Bus Stop', meaningNepali: 'बस स्टप', category: 'TRANSPORT' },
  { id: 191, word: '역', romanization: 'Yeok', meaning: 'Train Station', meaningNepali: 'रेल स्टेशन', category: 'TRANSPORT' },
  { id: 192, word: '표', romanization: 'Pyo', meaning: 'Ticket', meaningNepali: 'टिकट', category: 'TRANSPORT' },
  { id: 193, word: '요금', romanization: 'Yogeum', meaning: 'Fare / Fee', meaningNepali: 'भाडा / शुल्क', category: 'TRANSPORT' },
  { id: 194, word: '지도', romanization: 'Jido', meaning: 'Map', meaningNepali: 'मानचित्र / नक्सा', category: 'TRANSPORT' },
  { id: 195, word: '위치', romanization: 'Wichi', meaning: 'Location', meaningNepali: 'स्थान / ठेगाना', category: 'TRANSPORT' },
  { id: 196, word: '신호등', romanization: 'Sinhodeung', meaning: 'Traffic Light', meaningNepali: 'ट्राफिक लाइट', category: 'TRANSPORT' },
  { id: 197, word: '횡단보도', romanization: 'Hoengdanbodo', meaning: 'Crosswalk / Zebra crossing', meaningNepali: 'जेब्रा क्रसिङ', category: 'TRANSPORT' },
  { id: 198, word: '주차장', romanization: 'Juchajang', meaning: 'Parking lot', meaningNepali: 'पार्किङ स्थल', category: 'TRANSPORT' },
  { id: 199, word: '공항', romanization: 'Gonghang', meaning: 'Airport', meaningNepali: 'हवाईअड्डा (एयरपोर्ट)', category: 'TRANSPORT' },
  { id: 200, word: '터미널', romanization: 'Teomineol', meaning: 'Bus Terminal', meaningNepali: 'बस पार्क (टर्मिनल)', category: 'TRANSPORT' },
  { id: 201, word: '교통카드', romanization: 'Gyotong-kadeu', meaning: 'Transportation card (T-money)', meaningNepali: 'यातायात कार्ड', category: 'TRANSPORT' },
  { id: 202, word: '환승', romanization: 'Hwanseung', meaning: 'Transfer (bus/subway)', meaningNepali: 'गाडी परिवर्तन (ट्रान्सफर)', category: 'TRANSPORT' },
  { id: 203, word: '출구', romanization: 'Chulgu', meaning: 'Exit (station/building)', meaningNepali: 'निकास (एक्जिट)', category: 'TRANSPORT' },
  { id: 204, word: '입구', romanization: 'Ipgu', meaning: 'Entrance', meaningNepali: 'प्रवेशद्वार (इन्ट्रान्स)', category: 'TRANSPORT' },
  { id: 205, word: '엘리베이터', romanization: 'Ellibeiteo', meaning: 'Elevator', meaningNepali: 'लिफ्ट (लिफ्ट/एलिभेटर)', category: 'TRANSPORT' },

  // ── 7. HEALTH & BODY (206–230) ──
  { id: 206, word: '머리', romanization: 'Meori', meaning: 'Head / Hair', meaningNepali: 'टाउको / कपाल', category: 'HEALTH' },
  { id: 207, word: '눈 / 코 / 입', romanization: 'Nun / Ko / Ip', meaning: 'Eye / Nose / Mouth', meaningNepali: 'आँखा / नाक / मुख', category: 'HEALTH' },
  { id: 208, word: '손 / 발', romanization: 'Son / Bal', meaning: 'Hand / Foot', meaningNepali: 'हात / खुट्टा', category: 'HEALTH' },
  { id: 209, word: '배', romanization: 'Bae', meaning: 'Stomach / Belly', meaningNepali: 'पेट', category: 'HEALTH' },
  { id: 210, word: '아프다', romanization: 'Apeuda', meaning: 'To be sick / Hurt', meaningNepali: 'दुख्नु / बिरामी हुनु', category: 'HEALTH' },
  { id: 211, word: '열', romanization: 'Yeol', meaning: 'Fever', meaningNepali: 'ज्वरो', category: 'HEALTH' },
  { id: 212, word: '감기', romanization: 'Gamgi', meaning: 'Cold / Flu', meaningNepali: 'रुघाखोकी', category: 'HEALTH' },
  { id: 213, word: '약', romanization: 'Yak', meaning: 'Medicine', meaningNepali: 'औषधी', category: 'HEALTH' },
  { id: 214, word: '주사', romanization: 'Jusa', meaning: 'Injection / Shot', meaningNepali: 'सुई (इन्जेक्सन)', category: 'HEALTH' },
  { id: 215, word: '의사 / 간호사', romanization: 'Uisa / Ganhosa', meaning: 'Doctor / Nurse', meaningNepali: 'डाक्टर / नर्स', category: 'HEALTH' },
  { id: 216, word: '기침', romanization: 'Gichim', meaning: 'Cough', meaningNepali: 'खोकी', category: 'HEALTH' },
  { id: 217, word: '두통', romanization: 'Dutong', meaning: 'Headache', meaningNepali: 'टाउको दुखाइ', category: 'HEALTH' },
  { id: 218, word: '복통', romanization: 'Boktong', meaning: 'Stomachache', meaningNepali: 'पेट दुखाइ', category: 'HEALTH' },
  { id: 219, word: '치통', romanization: 'Chitong', meaning: 'Toothache', meaningNepali: 'दाँत दुखाइ', category: 'HEALTH' },
  { id: 220, word: '설사', romanization: 'Seolsa', meaning: 'Diarrhea', meaningNepali: 'झाडापखाला', category: 'HEALTH' },
  { id: 221, word: '소화제', romanization: 'Sohwaje', meaning: 'Digestive medicine', meaningNepali: 'पाचन औसधी', category: 'HEALTH' },
  { id: 222, word: '진통제', romanization: 'Jintongje', meaning: 'Painkiller', meaningNepali: 'पेनकिलर (दुखाइ कम गर्ने औषधी)', category: 'HEALTH' },
  { id: 223, word: '파스', romanization: 'Paseu', meaning: 'Pain relief patch', meaningNepali: 'पेन रिलिफ प्याच (पट्टी)', category: 'HEALTH' },
  { id: 224, word: '밴드 / 반창고', romanization: 'Baendeuu / Banchanggo', meaning: 'Band-aid / Adhesive plaster', meaningNepali: 'ब्यान्डेज / प्लास्टर', category: 'HEALTH' },
  { id: 225, word: '응급실', romanization: 'Eunggeupsil', meaning: 'Emergency Room (ER)', meaningNepali: 'आकस्मिक कक्ष (एमरजेन्सी)', category: 'HEALTH' },
  { id: 226, word: '피', romanization: 'Pi', meaning: 'Blood', meaningNepali: 'रगत', category: 'HEALTH' },
  { id: 227, word: '상처', romanization: 'Sangcheo', meaning: 'Wound / Cut', meaningNepali: 'घाउ / चोट', category: 'HEALTH' },
  { id: 228, word: '깁스', romanization: 'Gipseu', meaning: 'Cast (for broken bone)', meaningNepali: 'प्लास्टर (हाड भाँच्चिँदा)', category: 'HEALTH' },
  { id: 229, word: '몸살', romanization: 'Momsal', meaning: 'Body ache / Fatigue', meaningNepali: 'ज्यान दुख्ने समस्या', category: 'HEALTH' },
  { id: 230, word: '건강', romanization: 'Geongang', meaning: 'Health / Wellness', meaningNepali: 'स्वास्थ्य', category: 'HEALTH' },

  // ── 8. CORE VERBS (231–270) ──
  { id: 231, word: '가다', romanization: 'Gada', meaning: 'To go', meaningNepali: 'जानु', category: 'VERBS' },
  { id: 232, word: '오다', romanization: 'Oda', meaning: 'To come', meaningNepali: 'आउनु', category: 'VERBS' },
  { id: 233, word: '먹다', romanization: 'Meokda', meaning: 'To eat', meaningNepali: 'खाऊनु', category: 'VERBS' },
  { id: 234, word: '마시다', romanization: 'Masida', meaning: 'To drink', meaningNepali: 'पिउनु', category: 'VERBS' },
  { id: 235, word: '자다', romanization: 'Jada', meaning: 'To sleep', meaningNepali: 'सुत्नु', category: 'VERBS' },
  { id: 236, word: '일어나다', romanization: 'Ireonada', meaning: 'To wake up / Stand up', meaningNepali: 'उठ्नु', category: 'VERBS' },
  { id: 237, word: '일하다', romanization: 'Irhada', meaning: 'To work', meaningNepali: 'काम गर्नु', category: 'VERBS' },
  { id: 238, word: '쉬다', romanization: 'Swida', meaning: 'To rest / Take a break', meaningNepali: 'आराम गर्नु', category: 'VERBS' },
  { id: 239, word: '공부하다', romanization: 'Gongbuhada', meaning: 'To study', meaningNepali: 'अध्ययन गर्नु', category: 'VERBS' },
  { id: 240, word: '사다', romanization: 'Sada', meaning: 'To buy', meaningNepali: 'किन्नु', category: 'VERBS' },
  { id: 241, word: '팔다', romanization: 'Palda', meaning: 'To sell', meaningNepali: 'बेच्नु', category: 'VERBS' },
  { id: 242, word: '보다', romanization: 'Boda', meaning: 'To watch / See / Look', meaningNepali: 'हेर्नु / देख्नु', category: 'VERBS' },
  { id: 243, word: '듣다', romanization: 'Deutda', meaning: 'To listen / Hear', meaningNepali: 'सुन्नु', category: 'VERBS' },
  { id: 244, word: '말하다', romanization: 'Malhada', meaning: 'To speak / Talk', meaningNepali: 'बोल्नु / कुरा गर्नु', category: 'VERBS' },
  { id: 245, word: '읽다', romanization: 'Ikda', meaning: 'To read', meaningNepali: 'पढ्नु', category: 'VERBS' },
  { id: 246, word: '쓰다', romanization: 'Sseuda', meaning: 'To write / Use', meaningNepali: 'लेख्नु / प्रयोग गर्नु', category: 'VERBS' },
  { id: 247, word: '만나다', romanization: 'Mannada', meaning: 'To meet', meaningNepali: 'भेट्नु', category: 'VERBS' },
  { id: 248, word: '알다', romanization: 'Alda', meaning: 'To know / Understand', meaningNepali: 'थाहा पाउनु / बुझ्नु', category: 'VERBS' },
  { id: 249, word: '모르다', romanization: 'Moreuda', meaning: 'To not know', meaningNepali: 'थाहा नहुनु', category: 'VERBS' },
  { id: 250, word: '전화하다', romanization: 'Jeonhwahada', meaning: 'To make a phone call', meaningNepali: 'फोन गर्नु', category: 'VERBS' },
  { id: 251, word: '청소하다', romanization: 'Cheongsohada', meaning: 'To clean up', meaningNepali: 'सरसफाइ गर्नु', category: 'VERBS' },
  { id: 252, word: '빨래하다', romanization: 'Ppallaehada', meaning: 'To do laundry', meaningNepali: 'कपडा धुनु', category: 'VERBS' },
  { id: 253, word: '요리하다', romanization: 'Yorihada', meaning: 'To cook', meaningNepali: 'खाना पकाउनु', category: 'VERBS' },
  { id: 254, word: '기다리다', romanization: 'Gidarida', meaning: 'To wait', meaningNepali: 'पर्खनु', category: 'VERBS' },
  { id: 255, word: '돕다', romanization: 'Dopda', meaning: 'To help', meaningNepali: 'सहयोग गर्नु', category: 'VERBS' },
  { id: 256, word: '시작하다', romanization: 'Sijakhada', meaning: 'To start / Begin', meaningNepali: 'शुरु गर्नु', category: 'VERBS' },
  { id: 257, word: '끝나다', romanization: 'Kkeutnada', meaning: 'To finish / End', meaningNepali: 'सकिनु / समाप्त हुनु', category: 'VERBS' },
  { id: 258, word: '운전하다', romanization: 'Unjeonhada', meaning: 'To drive', meaningNepali: 'गाडी हाँक्नु (ड्राइभ गर्नु)', category: 'VERBS' },
  { id: 259, word: '운동하다', romanization: 'Undonghada', meaning: 'To exercise / Play sports', meaningNepali: 'व्यायाम गर्नु', category: 'VERBS' },
  { id: 260, word: '생각하다', romanization: 'Saenggakhada', meaning: 'To think', meaningNepali: 'सोच्नु', category: 'VERBS' },
  { id: 261, word: '질문하다', romanization: 'Jilmunhada', meaning: 'To ask a question', meaningNepali: 'प्रश्न सोध्नु', category: 'VERBS' },
  { id: 262, word: '대답하다', romanization: 'Daedaphada', meaning: 'To answer / Reply', meaningNepali: 'उत्तर दिनु', category: 'VERBS' },
  { id: 263, word: '주문하다', romanization: 'Jumunhada', meaning: 'To order (food/goods)', meaningNepali: 'अर्डर गर्नु', category: 'VERBS' },
  { id: 264, word: '계산하다', romanization: 'Gyesanhada', meaning: 'To pay / Calculate bill', meaningNepali: 'हिसाब गर्नु / बिल तिर्नु', category: 'VERBS' },
  { id: 265, word: '예약하다', romanization: 'Yeyakhada', meaning: 'To reserve / Book', meaningNepali: 'बुकिङ (रिजर्भ) गर्नु', category: 'VERBS' },
  { id: 266, word: '도착하다', romanization: 'Dochakhada', meaning: 'To arrive', meaningNepali: 'आइपुग्नु', category: 'VERBS' },
  { id: 267, word: '출발하다', romanization: 'Chulbalhada', meaning: 'To depart / Leave', meaningNepali: 'प्रस्थान गर्नु (हिँड्नु)', category: 'VERBS' },
  { id: 268, word: '타다', romanization: 'Tada', meaning: 'To ride / Board (vehicle)', meaningNepali: 'चढ्नु (बस/गाडी)', category: 'VERBS' },
  { id: 269, word: '내리다', romanization: 'Naerida', meaning: 'To get off / Disembark', meaningNepali: 'झर्नु (गाडीबाट)', category: 'VERBS' },
  { id: 270, word: '갈아타다', romanization: 'Garatada', meaning: 'To transfer / Change bus', meaningNepali: 'गाडी फेरेर चढ्नु', category: 'VERBS' },

  // ── 9. CORE ADJECTIVES (271–300) ──
  { id: 271, word: '크다', romanization: 'Keuda', meaning: 'To be big / Large', meaningNepali: 'ठूलो हुनु', category: 'ADJECTIVES' },
  { id: 272, word: '작다', romanization: 'Jakda', meaning: 'To be small', meaningNepali: 'सानो हुनु', category: 'ADJECTIVES' },
  { id: 273, word: '많다', romanization: 'Manhta', meaning: 'To be many / Much', meaningNepali: 'धेरै हुनु', category: 'ADJECTIVES' },
  { id: 274, word: '적다', romanization: 'Jeokda', meaning: 'To be few / Little', meaningNepali: 'थोरै हुनु', category: 'ADJECTIVES' },
  { id: 275, word: '좋다', romanization: 'Johda', meaning: 'To be good / Like', meaningNepali: 'राम्रो हुनु / मन पर्नु', category: 'ADJECTIVES' },
  { id: 276, word: '나쁘다', romanization: 'Nappeuda', meaning: 'To be bad', meaningNepali: 'नराम्रो हुनु', category: 'ADJECTIVES' },
  { id: 277, word: '빠르다', romanization: 'Ppareuda', meaning: 'To be fast / Quick', meaningNepali: 'छिटो हुनु', category: 'ADJECTIVES' },
  { id: 278, word: '느리다', romanization: 'Neurida', meaning: 'To be slow', meaningNepali: 'ढिलो हुनु', category: 'ADJECTIVES' },
  { id: 279, word: '덥다', romanization: 'Deopda', meaning: 'To be hot (weather)', meaningNepali: 'गर्मी हुनु', category: 'ADJECTIVES' },
  { id: 280, word: '춥다', romanization: 'Chupda', meaning: 'To be cold (weather)', meaningNepali: 'जाडो हुनु', category: 'ADJECTIVES' },
  { id: 281, word: '바쁘다', romanization: 'Bappeuda', meaning: 'To be busy', meaningNepali: 'व्यस्त हुनु', category: 'ADJECTIVES' },
  { id: 282, word: '피곤하다', romanization: 'Pigonhada', meaning: 'To be tired', meaningNepali: 'थाकेको हुनु', category: 'ADJECTIVES' },
  { id: 283, word: '비싸다', romanization: 'Bissada', meaning: 'To be expensive', meaningNepali: 'महङ्गो हुनु', category: 'ADJECTIVES' },
  { id: 284, word: '싸다', romanization: 'Ssada', meaning: 'To be cheap', meaningNepali: 'सस्तो हुनु', category: 'ADJECTIVES' },
  { id: 285, word: '맛있다', romanization: 'Masitda', meaning: 'To be delicious', meaningNepali: 'मीठो हुनु', category: 'ADJECTIVES' },
  { id: 286, word: '맛없다', romanization: 'Maseoptda', meaning: 'To be tasteless / Not delicious', meaningNepali: 'मीठो नहुनु', category: 'ADJECTIVES' },
  { id: 287, word: '어렵다', romanization: 'Eoryeopda', meaning: 'To be difficult', meaningNepali: 'गाह्रो हुनु / कठिन हुनु', category: 'ADJECTIVES' },
  { id: 288, word: '쉬운 / 쉽다', romanization: 'Swi-un / Swipda', meaning: 'To be easy', meaningNepali: 'सजिलो हुनु', category: 'ADJECTIVES' },
  { id: 289, word: '기쁘다', romanization: 'Gippeuda', meaning: 'To be glad / Happy', meaningNepali: 'खुसी हुनु', category: 'ADJECTIVES' },
  { id: 290, word: '슬프다', romanization: 'Seulpeuda', meaning: 'To be sad', meaningNepali: 'दुःखी हुनु', category: 'ADJECTIVES' },
  { id: 291, word: '멀다', romanization: 'Meolda', meaning: 'To be far', meaningNepali: 'टाढा हुनु', category: 'ADJECTIVES' },
  { id: 292, word: '가깝다', romanization: 'Gagkapda', meaning: 'To be near / Close', meaningNepali: 'नजिक हुनु', category: 'ADJECTIVES' },
  { id: 293, word: '깨끗하다', romanization: 'Kkaekkeuthada', meaning: 'To be clean', meaningNepali: 'सफा हुनु', category: 'ADJECTIVES' },
  { id: 294, word: '더럽다', romanization: 'Deoreopda', meaning: 'To be dirty', meaningNepali: 'फोहोर हुनु', category: 'ADJECTIVES' },
  { id: 295, word: '조용하다', romanization: 'Joyonghada', meaning: 'To be quiet', meaningNepali: 'शान्त हुनु', category: 'ADJECTIVES' },
  { id: 296, word: '시끄럽다', romanization: 'Sikkeureopda', meaning: 'To be noisy', meaningNepali: 'हल्ला हुनु', category: 'ADJECTIVES' },
  { id: 297, word: '복잡하다', romanization: 'Bokjaphada', meaning: 'To be crowded / Complex', meaningNepali: 'भीडभाड हुनु / जटिल हुनु', category: 'ADJECTIVES' },
  { id: 298, word: '친절하다', romanization: 'Chinjeolhada', meaning: 'To be kind / Friendly', meaningNepali: 'दयालु हुनु / नम्र हुनु', category: 'ADJECTIVES' },
  { id: 299, word: '중요하다', romanization: 'Jung-yohada', meaning: 'To be important', meaningNepali: 'महत्वपूर्ण हुनु', category: 'ADJECTIVES' },
  { id: 300, word: '필요하다', romanization: 'Piryohada', meaning: 'To be necessary / Needed', meaningNepali: 'आवश्यक हुनु / चाहिनु', category: 'ADJECTIVES' },
];
