// ============================================================
// MINNA NO NIHONGO N5 — Complete Vocabulary & Grammar
// SOURCE: Minna no Nihongo I (Translations & Grammar Notes)
// LESSONS 6–10 (Full coverage, no omissions)
// English + Nepali meanings · Grammar sentences per word
// ============================================================

import type { VocabItem } from './nihongo-vocab';

export const N5_LESSONS_6TO10: VocabItem[] = [

  // ════════════════════════════════════════════════════════
  // LESSON 6 — Direct Objects & Actions
  // Grammar: N を Vます  ·  N で Vます  ·  どこで Vますか  ·  Vませんか  ·  Vましょう
  // ════════════════════════════════════════════════════════
  { id:'n5_6_01', lesson:6, level:'N5', word:'たべます', reading:'たべます', meaning:'Eat', meaningNepali:'खानु', kanjiCharacters:['食'], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[
      { japanese:'あさごはんをたべます。', reading:'あさごはんをたべます。', english:'I eat breakfast.', nepali:'म बिहानको खाना खान्छु।' },
      { japanese:'なにをたべましたか。', reading:'なにをたべましたか。', english:'What did you eat?', nepali:'तपाईंले के खानुभयो?' }
    ]},
  { id:'n5_6_02', lesson:6, level:'N5', word:'のみます', reading:'のみます', meaning:'Drink', meaningNepali:'पिउनु', kanjiCharacters:['飲'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[
      { japanese:'みずをのみます。', reading:'みずをのみます。', english:'I drink water.', nepali:'म पानी पिउँछु।' },
      { japanese:'いっしょにコーヒーをのみませんか。', reading:'いっしょにコーヒーをのみませんか。', english:'Would you like to drink coffee together?', nepali:'सँगै कफी पिउने हो?' }
    ]},
  { id:'n5_6_03', lesson:6, level:'N5', word:'すいます', reading:'すいます', meaning:'Smoke (tobacco) / Inhale', meaningNepali:'धूम्रपान गर्नु / तान्नु', kanjiCharacters:['吸'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'たばこをすいません。', reading:'たばこをすいません。', english:'I do not smoke cigarettes.', nepali:'म चुरोट पिउँदिन।' }]},
  { id:'n5_6_04', lesson:6, level:'N5', word:'みます', reading:'みます', meaning:'See / Watch / Look', meaningNepali:'हेर्नु', kanjiCharacters:['見'], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[
      { japanese:'えいがをみます。', reading:'えいがをみます。', english:'I watch a movie.', nepali:'म फिल्म हेर्छु।' },
      { japanese:'きのうテレビをみました。', reading:'きのうテレビをみました。', english:'I watched TV yesterday.', nepali:'मैले हिजो टेलिभिजन हेरें।' }
    ]},
  { id:'n5_6_05', lesson:6, level:'N5', word:'ききます', reading:'ききます', meaning:'Hear / Listen', meaningNepali:'सुन्नु', kanjiCharacters:['聞'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'おんがくをききます。', reading:'おんがくをききます。', english:'I listen to music.', nepali:'म सङ्गीत सुन्छु।' }]},
  { id:'n5_6_06', lesson:6, level:'N5', word:'よみます', reading:'よみます', meaning:'Read', meaningNepali:'पढ्नु (किताब/पत्रिका)', kanjiCharacters:['読'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'しんぶんをよみます。', reading:'しんぶんをよみます。', english:'I read the newspaper.', nepali:'म समाचारपत्र पढ्छु।' }]},
  { id:'n5_6_07', lesson:6, level:'N5', word:'かきます', reading:'かきます', meaning:'Write / Draw', meaningNepali:'लेख्नु / चित्र कोर्नु', kanjiCharacters:['書'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'てがみをかきます。', reading:'てがみをかきます。', english:'I write a letter.', nepali:'म पत्र लेख्छु।' }]},
  { id:'n5_6_08', lesson:6, level:'N5', word:'かいます', reading:'かいます', meaning:'Buy', meaningNepali:'किन्नु', kanjiCharacters:['買'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'スーパーでパンをかいました。', reading:'スーパーでパンをかいました。', english:'I bought bread at the supermarket.', nepali:'मैले सुपरमार्केटमा पाउरोटी किनें।' }]},
  { id:'n5_6_09', lesson:6, level:'N5', word:'とります', reading:'とります', meaning:'Take (a photograph)', meaningNepali:'खिच्नु (फोटो)', kanjiCharacters:['撮'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'しゃしんをとります。', reading:'しゃしんをとります。', english:'I take a photo.', nepali:'म फोटो खिच्छु।' }]},
  { id:'n5_6_10', lesson:6, level:'N5', word:'します', reading:'します', meaning:'Do / Play (games, sports)', meaningNepali:'गर्नु / खेल्नु', kanjiCharacters:[], partOfSpeech:'Verb (Irregular)',
    grammarSentences:[
      { japanese:'しゅくだいをします。', reading:'しゅくだいをします。', english:'I do homework.', nepali:'म गृहकार्य गर्छु।' },
      { japanese:'サッカーをします。', reading:'サッカーをします。', english:'I play soccer.', nepali:'म फुटबल खेल्छु।' }
    ]},
  { id:'n5_6_11', lesson:6, level:'N5', word:'あいます', reading:'あいます', meaning:'Meet (a friend)', meaningNepali:'भेट्नु (साथी)', kanjiCharacters:['会'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'えきでともだちにあいます。', reading:'えきでともだちにあいます。', english:'I will meet a friend at the station.', nepali:'म स्टेशनमा साथीलाई भेट्छु।' }]},
  { id:'n5_6_12', lesson:6, level:'N5', word:'ごはん', reading:'ごはん', meaning:'Cooked rice / Meal', meaningNepali:'भात / खाना', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ごはんをたべましたか。', reading:'ごはんをたべましたか。', english:'Did you eat a meal?', nepali:'खाना खानुभयो?' }]},
  { id:'n5_6_13', lesson:6, level:'N5', word:'あさごはん', reading:'あさごはん', meaning:'Breakfast', meaningNepali:'बिहानको खाना', kanjiCharacters:['朝'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'しちじにあさごはんをたべます。', reading:'しちじにあさごはんをたべます。', english:'I eat breakfast at 7 o\'clock.', nepali:'म ७ बजे बिहानको खाना खान्छु।' }]},
  { id:'n5_6_14', lesson:6, level:'N5', word:'ひるごはん', reading:'ひるごはん', meaning:'Lunch', meaningNepali:'दिउँसोको खाना', kanjiCharacters:['昼'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'しょくどうでひるごはんをたべます。', reading:'しょくどうでひるごはんをたべます。', english:'I eat lunch at the cafeteria.', nepali:'म क्यान्टिनमा दिउँसोको खाना खान्छु।' }]},
  { id:'n5_6_15', lesson:6, level:'N5', word:'ばんごはん', reading:'ばんごはん', meaning:'Dinner / Supper', meaningNepali:'रातिको खाना', kanjiCharacters:['晩'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'うちでばんごはんをたべます。', reading:'うちでばんごはんをたべます。', english:'I eat dinner at home.', nepali:'म घरमा रातिको खाना खान्छु।' }]},
  { id:'n5_6_16', lesson:6, level:'N5', word:'パン', reading:'パン', meaning:'Bread', meaningNepali:'पाउरोटी', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいあさパンをたべます。', reading:'まいあさパンをたべます。', english:'I eat bread every morning.', nepali:'म हरेक बिहान पाउरोटी खान्छु।' }]},
  { id:'n5_6_17', lesson:6, level:'N5', word:'たまご', reading:'たまご', meaning:'Egg', meaningNepali:'अण्डा', kanjiCharacters:['卵'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'たまごをたべます。', reading:'たまごをたべます。', english:'I eat eggs.', nepali:'म अण्डा खान्छु।' }]},
  { id:'n5_6_18', lesson:6, level:'N5', word:'にく', reading:'にく', meaning:'Meat', meaningNepali:'मासु', kanjiCharacters:['肉'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'とにくをかいました。', reading:'とにくをかいました。', english:'I bought chicken meat.', nepali:'मैले कुखुराको मासु किनें।' }]},
  { id:'n5_6_19', lesson:6, level:'N5', word:'さかな', reading:'さかな', meaning:'Fish', meaningNepali:'माछा', kanjiCharacters:['魚'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'さかながすきです。', reading:'さかながすきです。', english:'I like fish.', nepali:'मलाई माछा मनपर्छ।' }]},
  { id:'n5_6_20', lesson:6, level:'N5', word:'やさい', reading:'やさい', meaning:'Vegetable', meaningNepali:'तरकारी', kanjiCharacters:['野','菜'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいにちやさいをたべます。', reading:'まいにちやさいをたべます。', english:'I eat vegetables every day.', nepali:'म हरेक दिन तरकारी खान्छु।' }]},
  { id:'n5_6_21', lesson:6, level:'N5', word:'くだもの', reading:'くだもの', meaning:'Fruit', meaningNepali:'फलफूल', kanjiCharacters:['果','物'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'くだものがすきです。', reading:'くだものがすきです。', english:'I like fruit.', nepali:'मलाई फलफूल मनपर्छ।' }]},
  { id:'n5_6_22', lesson:6, level:'N5', word:'みず', reading:'みず', meaning:'Water', meaningNepali:'पानी', kanjiCharacters:['水'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'つめたいみずをのみます。', reading:'つめたいみずをのみます。', english:'I drink cold water.', nepali:'म चिसो पानी पिउँछु।' }]},
  { id:'n5_6_23', lesson:6, level:'N5', word:'おちゃ', reading:'おちゃ', meaning:'Green tea / Tea', meaningNepali:'चिया', kanjiCharacters:['茶'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おちゃをのみましょう。', reading:'おちゃをのみましょう。', english:'Let\'s drink tea.', nepali:'चिया पिऔँ।' }]},
  { id:'n5_6_24', lesson:6, level:'N5', word:'こうちゃ', reading:'こうちゃ', meaning:'Black tea', meaningNepali:'ब्ल्याक टी / कालो चिया', kanjiCharacters:['紅','茶'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こうちゃをのみます。', reading:'こうちゃをのみます。', english:'I drink black tea.', nepali:'म कालो चिया पिउँछु।' }]},
  { id:'n5_6_25', lesson:6, level:'N5', word:'ぎゅうにゅう', reading:'ぎゅうにゅう', meaning:'Milk', meaningNepali:'दूध', kanjiCharacters:['牛','乳'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいあさぎゅうにゅうをのみます。', reading:'まいあさぎゅうにゅうをのみます。', english:'I drink milk every morning.', nepali:'म हरेक बिहान दूध पिउँछु।' }]},
  { id:'n5_6_26', lesson:6, level:'N5', word:'ジュース', reading:'ジュース', meaning:'Juice', meaningNepali:'जस / रस', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'りんごジュースをのみます。', reading:'りんごジュースをのみます。', english:'I drink apple juice.', nepali:'म स्याउको जुस पिउँछु।' }]},
  { id:'n5_6_27', lesson:6, level:'N5', word:'ビール', reading:'ビール', meaning:'Beer', meaningNepali:'बियर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'つめたいビールをのみました。', reading:'つめたいビールをのみました。', english:'I drank cold beer.', nepali:'मैले चिसो बियर पिएँ।' }]},
  { id:'n5_6_28', lesson:6, level:'N5', word:'おさけ', reading:'おさけ', meaning:'Alcohol / Sake', meaningNepali:'रक्सी / मदिरा', kanjiCharacters:['酒'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おさけをのみません。', reading:'おさけをのみません。', english:'I do not drink alcohol.', nepali:'म रक्सी पिउँदिन।' }]},
  { id:'n5_6_29', lesson:6, level:'N5', word:'たばこ', reading:'たばこ', meaning:'Tobacco / Cigarette', meaningNepali:'चुरोट', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ここでたばこをすわないでください。', reading:'ここでたばこをすわないでください。', english:'Please do not smoke cigarettes here.', nepali:'कृपया यहाँ चुरोट नपिउनुहोस्।' }]},
  { id:'n5_6_30', lesson:6, level:'N5', word:'てがみ', reading:'てがみ', meaning:'Letter', meaningNepali:'पत्र / चिट्ठी', kanjiCharacters:['手','紙'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'くにとともだちにてがみをかきます。', reading:'くにとともだちにてがみをかきます。', english:'I write a letter to a friend in my home country.', nepali:'म देशको साथीलाई पत्र लेख्छु।' }]},
  { id:'n5_6_31', lesson:6, level:'N5', word:'レポート', reading:'レポート', meaning:'Report', meaningNepali:'रिपोर्ट / प्रतिवेदन', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にほんごでレポートをかきます。', reading:'にほんごでレポートをかきます。', english:'I write a report in Japanese.', nepali:'म जापानी भाषामा रिपोर्ट लेख्छु।' }]},
  { id:'n5_6_32', lesson:6, level:'N5', word:'しゃしん', reading:'しゃしん', meaning:'Photograph', meaningNepali:'फोटो / तस्बिर', kanjiCharacters:['写','真'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こうえんでしゃしんをとりました。', reading:'こうえんでしゃしんをとりました。', english:'I took photos in the park.', nepali:'मैले पार्कमा फोटो खिचें।' }]},
  { id:'n5_6_33', lesson:6, level:'N5', word:'ビデオ', reading:'ビデオ', meaning:'Video / Video tape', meaningNepali:'भिडियो', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ビデオをみます。', reading:'ビデオをみます。', english:'I watch a video.', nepali:'म भिडियो हेर्छु।' }]},
  { id:'n5_6_34', lesson:6, level:'N5', word:'みせ', reading:'みせ', meaning:'Shop / Store', meaningNepali:'पसल', kanjiCharacters:['店'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あのあつしみせでふくをかいました。', reading:'あのあつしみせでふくをかいました。', english:'I bought clothes at that store.', nepali:'मैले त्यो पसलमा कपडा किनें।' }]},
  { id:'n5_6_35', lesson:6, level:'N5', word:'レストラン', reading:'レストラン', meaning:'Restaurant', meaningNepali:'रेस्टुरेन्ट', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'レストランでばんごはんをたべます。', reading:'レストランでばんごはんをたべます。', english:'I eat dinner at a restaurant.', nepali:'म रेस्टुरेन्टमा रातिको खाना खान्छु।' }]},
  { id:'n5_6_36', lesson:6, level:'N5', word:'にわ', reading:'にわ', meaning:'Garden', meaningNepali:'बैंचा / बगैंचा', kanjiCharacters:['庭'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にわにはながあります。', reading:'にわにはながあります。', english:'There are flowers in the garden.', nepali:'बगैंचामा फूलहरू छन्।' }]},
  { id:'n5_6_37', lesson:6, level:'N5', word:'しゅくだい', reading:'しゅくだい', meaning:'Homework', meaningNepali:'गृहकार्य', kanjiCharacters:['宿','題'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいばんしゅくだいをします。', reading:'まいばんしゅくだいをします。', english:'I do homework every evening.', nepali:'म हरेक साँझ गृहकार्य गर्छु।' }]},
  { id:'n5_6_38', lesson:6, level:'N5', word:'テニス', reading:'テニス', meaning:'Tennis', meaningNepali:'टेनिस', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'どようびにテニスをします。', reading:'どようびにテニスをします。', english:'I play tennis on Saturday.', nepali:'म शनिबार टेनिस खेल्छु।' }]},
  { id:'n5_6_39', lesson:6, level:'N5', word:'サッカー', reading:'サッカー', meaning:'Soccer / Football', meaningNepali:'फुटबल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ともだちとサッカーをしました。', reading:'ともだちとサッカーをしました。', english:'I played soccer with friends.', nepali:'मैले साथीहरूसँग फुटबल खेलें।' }]},
  { id:'n5_6_40', lesson:6, level:'N5', word:'おはなみ', reading:'おはなみ', meaning:'Cherry-blossom viewing', meaningNepali:'फूल हेर्ने उत्सव', kanjiCharacters:['花','見'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'らいしゅうおはなみをします。', reading:'らいしゅうおはなみをします。', english:'We will go cherry-blossom viewing next week.', nepali:'हामी अर्को हप्ता फूल हेर्न जान्छौँ।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 7 — Means & Giving / Receiving
  // Grammar: N (tool/language) で V  ·  N (person) に あげます/もらいます
  // ════════════════════════════════════════════════════════
  { id:'n5_7_01', lesson:7, level:'N5', word:'きります', reading:'きります', meaning:'Cut / Slice', meaningNepali:'काट्नु', kanjiCharacters:['切'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'ナイフでパンをきります。', reading:'ナイフでパンをきります。', english:'I cut bread with a knife.', nepali:'म चक्कुले पाउरोटी काट्छु।' }]},
  { id:'n5_7_02', lesson:7, level:'N5', word:'おくります', reading:'おくります', meaning:'Send', meaningNepali:'पठाउनु', kanjiCharacters:['送'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'くにへ荷物をおくります。', reading:'くにへにもつをおくります。', english:'I send baggage to my home country.', nepali:'म देशमा सामान पठाउँछु।' }]},
  { id:'n5_7_03', lesson:7, level:'N5', word:'あげます', reading:'あげます', meaning:'Give (to someone else)', meaningNepali:'दिनु (अरूलाई)', kanjiCharacters:[], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[{ japanese:'ともだちにプレゼントをあげました。', reading:'ともだちにプレゼントをあげました。', english:'I gave a present to my friend.', nepali:'मैले साथीलाई उपहार दिएँ।' }]},
  { id:'n5_7_04', lesson:7, level:'N5', word:'もらいます', reading:'もらいます', meaning:'Receive / Get', meaningNepali:'पाउनु / लिनु', kanjiCharacters:[], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'せんせいにほんをもらいました。', reading:'せんせいにほんをもらいました。', english:'I received a book from the teacher.', nepali:'मैले गुरुबाट किताब पाएँ।' }]},
  { id:'n5_7_05', lesson:7, level:'N5', word:'かします', reading:'かします', meaning:'Lend', meaningNepali:'उधारो/सापट दिनु', kanjiCharacters:['貸'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'ともだちにほんをかしました。', reading:'ともだちにほんをかしました。', english:'I lent a book to a friend.', nepali:'मैले साथीलाई किताब सापट दिएँ।' }]},
  { id:'n5_7_06', lesson:7, level:'N5', word:'かります', reading:'かります', meaning:'Borrow', meaningNepali:'सापट लिनु', kanjiCharacters:['借'], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[{ japanese:'としょかんでほんをかりました。', reading:'としょかんでほんをかりました。', english:'I borrowed a book from the library.', nepali:'मैले पुस्तकालयबाट किताब सापट लिएँ।' }]},
  { id:'n5_7_07', lesson:7, level:'N5', word:'おしえます', reading:'おしえます', meaning:'Teach / Tell', meaningNepali:'सिकाउनु / भन्नु', kanjiCharacters:['教'], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[{ japanese:'たなかさんにえいごをおしえます。', reading:'たなかさんにえいごをおしえます。', english:'I teach English to Mr. Tanaka.', nepali:'म तानाका-जीलाई अंग्रेजी सिकाउँछु।' }]},
  { id:'n5_7_08', lesson:7, level:'N5', word:'ならいます', reading:'ならいます', meaning:'Learn', meaningNepali:'सिक्नु', kanjiCharacters:['習'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[{ japanese:'せんせいににほんごをならいます。', reading:'せんせいににほんごをならいます。', english:'I learn Japanese from a teacher.', nepali:'म गुरुबाट जापानी भाषा सिक्छु।' }]},
  { id:'n5_7_09', lesson:7, level:'N5', word:'かけます', reading:'かけます', meaning:'Make (a phone call)', meaningNepali:'कल गर्नु (फोन)', kanjiCharacters:[], partOfSpeech:'Verb (Group 2)',
    grammarSentences:[{ japanese:'かぞくにでんわをかけます。', reading:'かぞくにでんわをかけます。', english:'I make a phone call to my family.', nepali:'म परिवारलाई फोन गर्छु।' }]},
  { id:'n5_7_10', lesson:7, level:'N5', word:'て', reading:'て', meaning:'Hand / Arm', meaningNepali:'हात', kanjiCharacters:['手'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'てをあらいます。', reading:'てをあらいます。', english:'I wash my hands.', nepali:'म हात धुन्छु।' }]},
  { id:'n5_7_11', lesson:7, level:'N5', word:'はし', reading:'はし', meaning:'Chopsticks', meaningNepali:'चपस्टिक (खाने काँटा)', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'はしでたべます。', reading:'はしでたべます。', english:'I eat with chopsticks.', nepali:'म चपस्टिकले खान्छु।' }]},
  { id:'n5_7_12', lesson:7, level:'N5', word:'スプーン', reading:'スプーン', meaning:'Spoon', meaningNepali:'चम्चा', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'スプーンでスープをのみます。', reading:'スプーンでスープをのみます。', english:'I drink soup with a spoon.', nepali:'म चम्चाले सुप पिउँछु।' }]},
  { id:'n5_7_13', lesson:7, level:'N5', word:'ナイフ', reading:'ナイフ', meaning:'Knife', meaningNepali:'चक्कु', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ナイフで肉をきります。', reading:'ナイフでにくをきります。', english:'I cut meat with a knife.', nepali:'म चक्कुले मासु काट्छु।' }]},
  { id:'n5_7_14', lesson:7, level:'N5', word:'フォーク', reading:'フォーク', meaning:'Fork', meaningNepali:'काँटा चम्चा', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'フォークでパスタをたべます。', reading:'フォークでパスタをたべます。', english:'I eat pasta with a fork.', nepali:'म काँटाले पास्ता खान्छु।' }]},
  { id:'n5_7_15', lesson:7, level:'N5', word:'はさみ', reading:'はさみ', meaning:'Scissors', meaningNepali:'कैंची', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'はさみでかみをきります。', reading:'はさみでかみをきります。', english:'I cut paper with scissors.', nepali:'म कैंचीले कागज काट्छु।' }]},
  { id:'n5_7_16', lesson:7, level:'N5', word:'ファクス', reading:'ファクス', meaning:'Fax', meaningNepali:'फ्याक्स', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ファクスでレポートをおくりました。', reading:'ファクスでレポートをおくりました。', english:'I sent a report by fax.', nepali:'मैले फ्याक्सबाट प्रतिवेदन पठाएँ।' }]},
  { id:'n5_7_17', lesson:7, level:'N5', word:'ワープロ', reading:'ワープロ', meaning:'Word processor', meaningNepali:'वर्ड प्रोसेसर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ワープロでてがみをかきます。', reading:'ワープロでてがみをかきます。', english:'I write a letter on a word processor.', nepali:'म वर्ड प्रोसेसरमा पत्र लेख्छु।' }]},
  { id:'n5_7_18', lesson:7, level:'N5', word:'消しゴム', reading:'けしゴム', meaning:'Eraser / Rubber', meaningNepali:'इरेजर / रबर', kanjiCharacters:['消'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'けしゴムをかりてもいいですか。', reading:'けしゴムをかりてもいいですか。', english:'May I borrow an eraser?', nepali:'के म इरेजर सापट लिन सक्छु?' }]},
  { id:'n5_7_19', lesson:7, level:'N5', word:'かみ', reading:'かみ', meaning:'Paper', meaningNepali:'कागज', kanjiCharacters:['紙'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かみに名前をかいてください。', reading:'かみになまえをかいてください。', english:'Please write your name on the paper.', nepali:'कृपया कागजमा आफ्नो नाम लेख्नुहोस्।' }]},
  { id:'n5_7_20', lesson:7, level:'N5', word:'はな', reading:'はな', meaning:'Flower', meaningNepali:'फूल', kanjiCharacters:['花'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ははにはなをあげました。', reading:'ははにはなをあげました。', english:'I gave flowers to my mother.', nepali:'मैले आमालाई फूल दिएँ।' }]},
  { id:'n5_7_21', lesson:7, level:'N5', word:'シャツ', reading:'シャツ', meaning:'Shirt', meaningNepali:'शर्ट / कमिज', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あたらしいシャツをかいました。', reading:'あたらしいシャツをかいました。', english:'I bought a new shirt.', nepali:'मैले नयाँ शर्ट किनें।' }]},
  { id:'n5_7_22', lesson:7, level:'N5', word:'プレゼント', reading:'プレゼント', meaning:'Present / Gift', meaningNepali:'उपहार', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'たんじょうびのプレゼントをもらいました。', reading:'たんじょうびのプレゼントをもらいました。', english:'I received a birthday present.', nepali:'मैले जन्मदिनको उपहार पाएँ।' }]},
  { id:'n5_7_23', lesson:7, level:'N5', word:'きっぷ', reading:'きっぷ', meaning:'Ticket', meaningNepali:'टिकट', kanjiCharacters:['切','符'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんしゃのきっぷをかいます。', reading:'でんしゃのきっぷをかいます。', english:'I buy a train ticket.', nepali:'म ट्रेनको टिकट किन्छु।' }]},
  { id:'n5_7_24', lesson:7, level:'N5', word:'クリスマス', reading:'クリスマス', meaning:'Christmas', meaningNepali:'क्रिसमस', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'クリスマスにプレゼントをあげます。', reading:'クリスマスにプレゼントをあげます。', english:'I give presents at Christmas.', nepali:'म क्रिसमसमा उपहार दिन्छु।' }]},
  { id:'n5_7_25', lesson:7, level:'N5', word:'ちち', reading:'ちち', meaning:'My father', meaningNepali:'मेरो बुबा', kanjiCharacters:['父'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ちちはかいしゃいんです。', reading:'ちちはかいしゃいんです。', english:'My father is a company employee.', nepali:'मेरो बुबा कम्पनी कर्मचारी हुनुहुन्छ।' }]},
  { id:'n5_7_26', lesson:7, level:'N5', word:'はは', reading:'はは', meaning:'My mother', meaningNepali:'मेरो आमा', kanjiCharacters:['母'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ははのりょうりは美味しいです。', reading:'ははのりょうりはおいしいです。', english:'My mother\'s cooking is delicious.', nepali:'मेरो आमाको खाना मीठो छ।' }]},
  { id:'n5_7_27', lesson:7, level:'N5', word:'おとうさん', reading:'おとうさん', meaning:'Someone else\'s father / Father', meaningNepali:'बुबा (सम्मानित)', kanjiCharacters:['父'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おとうさんはおげんきですか。', reading:'おとうさんはおげんきですか。', english:'Is your father well?', nepali:'तपाईंको बुबा आरामै हुनुहुन्छ?' }]},
  { id:'n5_7_28', lesson:7, level:'N5', word:'おかあさん', reading:'おかあさん', meaning:'Someone else\'s mother / Mother', meaningNepali:'आमा (सम्मानित)', kanjiCharacters:['母'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おかあさんによろしく。', reading:'おかあさんによろしく。', english:'Give my regards to your mother.', nepali:'आमालाई मेरो नमस्कार भन्नुहोस्।' }]},
  { id:'n5_7_29', lesson:7, level:'N5', word:'もう', reading:'もう', meaning:'Already', meaningNepali:'भइसक्यो / पहिले नै', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'もうひるごはんをたべました。', reading:'もうひるごはんをたべました。', english:'I have already eaten lunch.', nepali:'मैले पहिले नै दिउँसोको खाना खाइसकें।' }]},
  { id:'n5_7_30', lesson:7, level:'N5', word:'まだ', reading:'まだ', meaning:'Not yet', meaningNepali:'अझै छैन', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'いいえ、まだです。', reading:'いいえ、まだです。', english:'No, not yet.', nepali:'होइन, अझै छैन।' }]},
  { id:'n5_7_31', lesson:7, level:'N5', word:'これから', reading:'これから', meaning:'From now on / Soon', meaningNepali:'अबदेखि / भर्खरै', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'これからひるごはんをたべます。', reading:'これからひるごはんをたべます。', english:'I am going to eat lunch now.', nepali:'म अब दिउँसोको खाना खान्छु।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 8 — Adjectives (i-adj & na-adj)
  // Grammar: N は い-adj です  ·  N は な-adj です  ·  な-adj な N  ·  い-adj N
  // ════════════════════════════════════════════════════════
  { id:'n5_8_01', lesson:8, level:'N5', word:'ハンサム[な]', reading:'ハンサム[な]', meaning:'Handsome', meaningNepali:'सुन्दर / हेन्डसम', kanjiCharacters:[], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'ミラーさんはハンサムな人です。', reading:'ミラーさんはハンサムなひとです。', english:'Mr. Miller is a handsome person.', nepali:'मिलर-जी सुन्दर मान्छे हुनुहुन्छ।' }]},
  { id:'n5_8_02', lesson:8, level:'N5', word:'きれい[な]', reading:'きれい[な]', meaning:'Beautiful / Clean', meaningNepali:'सुन्दर / सफा', kanjiCharacters:[], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'このへやはきれいですね。', reading:'このへやはきれいですね。', english:'This room is clean/beautiful, isn\'t it?', nepali:'यो कोठा सफा/सुन्दर छ, होइन?' }]},
  { id:'n5_8_03', lesson:8, level:'N5', word:'しずか[な]', reading:'しずか[な]', meaning:'Quiet', meaningNepali:'शान्त', kanjiCharacters:['静'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'としょかんはしずかです。', reading:'としょかんはしずかです。', english:'The library is quiet.', nepali:'पुस्तकालय शान्त छ।' }]},
  { id:'n5_8_04', lesson:8, level:'N5', word:'にぎやか[な]', reading:'にぎやか[な]', meaning:'Lively / Bustling', meaningNepali:'चहलपहल भएको / रमाइलो', kanjiCharacters:[], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'とうきょうはにぎやかなまちです。', reading:'とうきょうはにぎやかなまちです。', english:'Tokyo is a lively city.', nepali:'टोक्यो चहलपहल भएको शहर हो।' }]},
  { id:'n5_8_05', lesson:8, level:'N5', word:'ゆうめい[な]', reading:'ゆうめい[な]', meaning:'Famous', meaningNepali:'प्रख्यात / प्रसिद्ध', kanjiCharacters:['有','名'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'ふじさんはゆうめいです。', reading:'ふじさんはゆうめいです。', english:'Mt. Fuji is famous.', nepali:'फूजी पर्वत प्रसिद्ध छ।' }]},
  { id:'n5_8_06', lesson:8, level:'N5', word:'しんせつ[な]', reading:'しんせつ[な]', meaning:'Kind / Helpful', meaningNepali:'दयालु / सहयोगी', kanjiCharacters:['親','切'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'やまださんはしんせつな人です。', reading:'やまださんはしんせつなひとです。', english:'Mr. Yamada is a kind person.', nepali:'यामाडा-जी दयालु व्यक्ति हुनुहुन्छ।' }]},
  { id:'n5_8_07', lesson:8, level:'N5', word:'げんき[な]', reading:'げんき[な]', meaning:'Healthy / Energetic', meaningNepali:'स्वास्थ्य / स्फूर्त', kanjiCharacters:['元','気'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'おげんきですか。', reading:'おげんきですか。', english:'How are you? (Are you healthy?)', nepali:'तपाईंलाई सञ्चै छ?' }]},
  { id:'n5_8_08', lesson:8, level:'N5', word:'ひま[な]', reading:'ひま[な]', meaning:'Free (time) / Not busy', meaningNepali:'फुर्सद भएको', kanjiCharacters:['暇'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'きょうはひまです。', reading:'きょうはひまです。', english:'I am free today.', nepali:'आज मलाई फुर्सद छ।' }]},
  { id:'n5_8_09', lesson:8, level:'N5', word:'べんり[な]', reading:'べんり[な]', meaning:'Convenient', meaningNepali:'सुविधाजनक', kanjiCharacters:['便','利'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'スマホはとてもべんりです。', reading:'スマホはとてもべんりです。', english:'Smartphones are very convenient.', nepali:'स्मार्टफोन धेरै सुविधाजनक छ।' }]},
  { id:'n5_8_10', lesson:8, level:'N5', word:'すてき[な]', reading:'すてき[な]', meaning:'Fine / Nice / Wonderful', meaningNepali:'उत्कृष्ट / मनमोहक', kanjiCharacters:[], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'すてきなシャツですね。', reading:'すてきなシャツですね。', english:'That is a nice shirt, isn\'t it?', nepali:'त्यो राम्रो शर्ट छ, होइन?' }]},
  { id:'n5_8_11', lesson:8, level:'N5', word:'おおきい', reading:'おおきい', meaning:'Big / Large', meaningNepali:'ठूलो', kanjiCharacters:['大'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'このいえはおおきいです。', reading:'このいえはおおきいです。', english:'This house is big.', nepali:'यो घर ठूलो छ।' }]},
  { id:'n5_8_12', lesson:8, level:'N5', word:'ちいさい', reading:'ちいさい', meaning:'Small / Little', meaningNepali:'सानो', kanjiCharacters:['小'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'ちいさいいぬがいます。', reading:'ちいさいいぬがいます。', english:'There is a small dog.', nepali:'एउटा सानो कुकुर छ।' }]},
  { id:'n5_8_13', lesson:8, level:'N5', word:'あたらしい', reading:'あたらしい', meaning:'New', meaningNepali:'नयाँ', kanjiCharacters:['新'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'あたらしい車をかいました。', reading:'あたらしいくるまをかいました。', english:'I bought a new car.', nepali:'मैले नयाँ कार किनें।' }]},
  { id:'n5_8_14', lesson:8, level:'N5', word:'ふるい', reading:'ふるい', meaning:'Old (not used for people)', meaningNepali:'पुरानो', kanjiCharacters:['古'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'この本はふるいです。', reading:'このほんはふるいです。', english:'This book is old.', nepali:'यो किताब पुरानो छ।' }]},
  { id:'n5_8_15', lesson:8, level:'N5', word:'いい (よい)', reading:'いい(よい)', meaning:'Good', meaningNepali:'राम्रो / असल', kanjiCharacters:['好'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'きょうはいいてんきです。', reading:'きょうはいいてんきです。', english:'Today is good weather.', nepali:'आज राम्रो मौसम छ।' }]},
  { id:'n5_8_16', lesson:8, level:'N5', word:'わるい', reading:'わるい', meaning:'Bad', meaningNepali:'नराम्रो / खराब', kanjiCharacters:['悪'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'てんきがわるいです。', reading:'てんきがわるいです。', english:'The weather is bad.', nepali:'मौसम खराब छ।' }]},
  { id:'n5_8_17', lesson:8, level:'N5', word:'あつい', reading:'あつい', meaning:'Hot (weather/temperature)', meaningNepali:'गर्मी / तातो', kanjiCharacters:['熱','暑'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'きょうはとてもあついです。', reading:'きょうはとてもあついです。', english:'Today is very hot.', nepali:'आज धेरै गर्मी छ।' }]},
  { id:'n5_8_18', lesson:8, level:'N5', word:'さむい', reading:'さむい', meaning:'Cold (weather)', meaningNepali:'जाडो / चिसो (मौसम)', kanjiCharacters:['寒'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'きょうはさむいですね。', reading:'きょうはさむいですね。', english:'Today is cold, isn\'t it?', nepali:'आज जाडो छ, होइन?' }]},
  { id:'n5_8_19', lesson:8, level:'N5', word:'つめたい', reading:'つめたい', meaning:'Cold (to touch / drink)', meaningNepali:'चिसो (वस्तु/पेय)', kanjiCharacters:['冷'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'つめたいおみずをください。', reading:'つめたいおみずをください。', english:'Please give me cold water.', nepali:'कृपया मलाई चिसो पानी दिनुहोस्।' }]},
  { id:'n5_8_20', lesson:8, level:'N5', word:'むずかしい', reading:'むずかしい', meaning:'Difficult', meaningNepali:'गाह्रो / कठिन', kanjiCharacters:['難'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'にほんごはむずかしいですか。', reading:'にほんごはむずかしいですか。', english:'Is Japanese difficult?', nepali:'जापानी भाषा गाह्रो छ?' }]},
  { id:'n5_8_21', lesson:8, level:'N5', word:'やさしい', reading:'やさしい', meaning:'Easy / Kind', meaningNepali:'सजिलो / नम्र', kanjiCharacters:['易','優'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'このテストはやさしいです。', reading:'このテストはやさしいです。', english:'This test is easy.', nepali:'यो परीक्षा सजिलो छ।' }]},
  { id:'n5_8_22', lesson:8, level:'N5', word:'たかい', reading:'たかい', meaning:'Expensive / High / Tall', meaningNepali:'महँगो / अग्लो', kanjiCharacters:['高'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'このとけいはたかいです。', reading:'このとけいはたかいです。', english:'This watch is expensive.', nepali:'यो घडी महँगो छ।' }]},
  { id:'n5_8_23', lesson:8, level:'N5', word:'やすい', reading:'やすい', meaning:'Inexpensive / Cheap', meaningNepali:'सस्तो', kanjiCharacters:['安'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'スーパーのやさいはやすいです。', reading:'スーパーのやさいはやすいです。', english:'The vegetables at the supermarket are cheap.', nepali:'सुपरमार्केटको तरकारी सस्तो छ।' }]},
  { id:'n5_8_24', lesson:8, level:'N5', word:'ひくい', reading:'ひくい', meaning:'Low / Short (height)', meaningNepali:'होचो / कम', kanjiCharacters:['低'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'このやまはひくいです。', reading:'このやまはひくいです。', english:'This mountain is low.', nepali:'यो पहाड होचो छ।' }]},
  { id:'n5_8_25', lesson:8, level:'N5', word:'おもしろい', reading:'おもしろい', meaning:'Interesting / Funny', meaningNepali:'रोचक / रमाइलो', kanjiCharacters:['面','白'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'このえいがはおもしろいです。', reading:'このえいがはおもしろいです。', english:'This movie is interesting.', nepali:'यो फिल्म रोचक छ।' }]},
  { id:'n5_8_26', lesson:8, level:'N5', word:'おいしい', reading:'おいしい', meaning:'Delicious / Tasty', meaningNepali:'मीठो / स्वादिष्ट', kanjiCharacters:[], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'にほんのラーメンはおいしいです。', reading:'にほんのラーメンはおいしいです。', english:'Japanese ramen is delicious.', nepali:'जापानी रामेन मीठो हुन्छ।' }]},
  { id:'n5_8_27', lesson:8, level:'N5', word:'いそがしい', reading:'いそがしい', meaning:'Busy', meaningNepali:'व्यस्त', kanjiCharacters:['忙'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'きょうはいそがしいです。', reading:'きょうはいそがしいです。', english:'I am busy today.', nepali:'आज म व्यस्त छु।' }]},
  { id:'n5_8_28', lesson:8, level:'N5', word:'たのしい', reading:'たのしい', meaning:'Enjoyable / Fun', meaningNepali:'रमाइलो / आनन्ददायी', kanjiCharacters:['楽'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'りょこうはたのしかったです。', reading:'りょこうはたのしかったです。', english:'The trip was fun.', nepali:'भ्रमण रमाइलो थियो।' }]},
  { id:'n5_8_29', lesson:8, level:'N5', word:'しろい', reading:'しろい', meaning:'White', meaningNepali:'सेतो', kanjiCharacters:['白'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'しろいシャツをきています。', reading:'しろいシャツをきています。', english:'I am wearing a white shirt.', nepali:'म सेतो शर्ट लगाउँदैछु।' }]},
  { id:'n5_8_30', lesson:8, level:'N5', word:'くろい', reading:'くろい', meaning:'Black', meaningNepali:'कालो', kanjiCharacters:['黒'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'くろいかばんをかいました。', reading:'くろいかばんをかいました。', english:'I bought a black bag.', nepali:'मैले कालो झोला किनें।' }]},
  { id:'n5_8_31', lesson:8, level:'N5', word:'あかい', reading:'あかい', meaning:'Red', meaningNepali:'रातो', kanjiCharacters:['赤'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'あかいりんごをたべます。', reading:'あかいりんごをたべます。', english:'I eat a red apple.', nepali:'म रातो स्याउ खान्छु।' }]},
  { id:'n5_8_32', lesson:8, level:'N5', word:'あおい', reading:'あおい', meaning:'Blue', meaningNepali:'नीलो', kanjiCharacters:['青'], partOfSpeech:'I-Adjective',
    grammarSentences:[{ japanese:'そらがあおいです。', reading:'そらがあおいです。', english:'The sky is blue.', nepali:'आकाश नीलो छ।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 9 — Preferences, Abilities & Causes
  // Grammar: N が すき/きらい/じょうず/へた です  ·  N が あります/わかります  ·  〜から (reason)
  // ════════════════════════════════════════════════════════
  { id:'n5_9_01', lesson:9, level:'N5', word:'すき[な]', reading:'すき[な]', meaning:'Like / Fond of', meaningNepali:'मनपर्ने', kanjiCharacters:['好'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'わたしはスポーツがすきです。', reading:'わたしはスポーツがすきです。', english:'I like sports.', nepali:'मलाई खेलकुद मनपर्छ।' }]},
  { id:'n5_9_02', lesson:9, level:'N5', word:'きらい[な]', reading:'きらい[な]', meaning:'Dislike / Hate', meaningNepali:'मननपर्ने', kanjiCharacters:['嫌'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'さかながきらいです。', reading:'さかながきらいです。', english:'I dislike fish.', nepali:'मलाई माछा मनपर्दैन।' }]},
  { id:'n5_9_03', lesson:9, level:'N5', word:'じょうず[な]', reading:'じょうず[な]', meaning:'Good at / Skillful', meaningNepali:'बाठो / सीपालु', kanjiCharacters:['上','手'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'ミラーさんはにほんごがじょうずです。', reading:'ミラーさんはにほんごがじょうずです。', english:'Mr. Miller is good at Japanese.', nepali:'मिलर-जी जापानी भाषामा बाठो हुनुहुन्छ।' }]},
  { id:'n5_9_04', lesson:9, level:'N5', word:'へた[な]', reading:'へた[な]', meaning:'Poor at / Unskillful', meaningNepali:'नजान्ने / कमजोर', kanjiCharacters:['下','手'], partOfSpeech:'Na-Adjective',
    grammarSentences:[{ japanese:'わたしはりょうりがへたです。', reading:'わたしはりょうりがへたです。', english:'I am poor at cooking.', nepali:'म खाना बनाउन जान्दिन।' }]},
  { id:'n5_9_05', lesson:9, level:'N5', word:'りょうり', reading:'りょうり', meaning:'Dish / Cooking', meaningNepali:'खाना / परिकार', kanjiCharacters:['料','理'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にほんのりょうりがすきです。', reading:'にほんのりょうりがすきです。', english:'I like Japanese dishes.', nepali:'मलाई जापानी खाना मनपर्छ।' }]},
  { id:'n5_9_06', lesson:9, level:'N5', word:'スポーツ', reading:'スポーツ', meaning:'Sports', meaningNepali:'खेलकुद', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'どんなスポーツがすきですか。', reading:'どんなスポーツがすきですか。', english:'What kind of sports do you like?', nepali:'तपाईंलाई कुन प्रकारको खेलकुद मनपर्छ?' }]},
  { id:'n5_9_07', lesson:9, level:'N5', word:'やきゅう', reading:'やきゅう', meaning:'Baseball', meaningNepali:'बेसबोल', kanjiCharacters:['野','球'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'やきゅうがすきです。', reading:'やきゅうがすきです。', english:'I like baseball.', nepali:'मलाई बेसबोल मनपर्छ।' }]},
  { id:'n5_9_08', lesson:9, level:'N5', word:'ダンス', reading:'ダンス', meaning:'Dance', meaningNepali:'नृत्य / नाच', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ダンスがじょうずですね。', reading:'ダンスがじょうずですね。', english:'You are good at dancing, aren\'t you?', nepali:'तपाईं नाच्न बाठो हुनुहुन्छ है।' }]},
  { id:'n5_9_09', lesson:9, level:'N5', word:'おんがく', reading:'おんがく', meaning:'Music', meaningNepali:'सङ्गीत', kanjiCharacters:['音','楽'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'クラシックおんがくをききます。', reading:'クラシックおんがくをききます。', english:'I listen to classical music.', nepali:'म क्लासिकल सङ्गीत सुन्छु।' }]},
  { id:'n5_9_10', lesson:9, level:'N5', word:'うた', reading:'うた', meaning:'Song', meaningNepali:'गीत', kanjiCharacters:['歌'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にほんのうたをうたいます。', reading:'にほんのうたをうたいます。', english:'I sing Japanese songs.', nepali:'म जापानी गीत गाउँछु।' }]},
  { id:'n5_9_11', lesson:9, level:'N5', word:'こまかいおかね', reading:'こまかいおかね', meaning:'Small change (coins)', meaningNepali:'खुद्रा पैसा', kanjiCharacters:['細','金'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こまかいおかねがありますか。', reading:'こまかいおかねがありますか。', english:'Do you have small change?', nepali:'तपाईंसँग खुद्रा पैसा छ?' }]},
  { id:'n5_9_12', lesson:9, level:'N5', word:'チケット', reading:'チケット', meaning:'Ticket (concert/movie)', meaningNepali:'टिकट (कन्सर्ट/फिल्म)', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'コンサートのチケットをかいました。', reading:'コンサートのチケットをかいました。', english:'I bought a concert ticket.', nepali:'मैले कन्सर्टको टिकट किनें।' }]},
  { id:'n5_9_13', lesson:9, level:'N5', word:'じかん', reading:'じかん', meaning:'Time', meaningNepali:'समय', kanjiCharacters:['時','間'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'じかんがありません。', reading:'じかんがありません。', english:'I don\'t have time.', nepali:'मसँग समय छैन।' }]},
  { id:'n5_9_14', lesson:9, level:'N5', word:'ようじ', reading:'ようじ', meaning:'Things to do / Business', meaningNepali:'काम / कामको मामिला', kanjiCharacters:['用','事'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きょうはようじがあります。', reading:'きょうはようじがあります。', english:'I have things to do today.', nepali:'आज मेरो काम छ।' }]},
  { id:'n5_9_15', lesson:9, level:'N5', word:'やくそく', reading:'やくそく', meaning:'Promise / Appointment', meaningNepali:'वाचा / भेट्ने समय', kanjiCharacters:['約','束'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ともだちとやくそくがあります。', reading:'ともだちとやくそくがあります。', english:'I have an appointment with a friend.', nepali:'मेरो साथीसँग भेट्ने प्रतिबद्धता छ।' }]},
  { id:'n5_9_16', lesson:9, level:'N5', word:'わかります', reading:'わかります', meaning:'Understand / Know', meaningNepali:'बुझ्नु', kanjiCharacters:['分'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[
      { japanese:'にほんごがわかります。', reading:'にほんごがわかります。', english:'I understand Japanese.', nepali:'म जापानी बुझ्छु।' },
      { japanese:'えいごがよくわかりません。', reading:'えいごがよくわかりません。', english:'I don\'t understand English well.', nepali:'म अंग्रेजी राम्ररी बुझ्दिन।' }
    ]},
  { id:'n5_9_17', lesson:9, level:'N5', word:'ぜんぜん', reading:'ぜんぜん', meaning:'Not at all (used with negative)', meaningNepali:'बिलकुलै छैन / अलिकति पनि होइन', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'ぜんぜんわかりません。', reading:'ぜんぜんわかりません。', english:'I don\'t understand at all.', nepali:'म अलिकति पनि बुझ्दिन।' }]},
  { id:'n5_9_18', lesson:9, level:'N5', word:'たくさん', reading:'たくさん', meaning:'Many / Much / A lot', meaningNepali:'धेरै', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'おかねがたくさんあります。', reading:'おかねがたくさんあります。', english:'I have a lot of money.', nepali:'मसँग धेरै पैसा छ।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 10 — Existence & Positional Location
  // Grammar: N が あります/います  ·  N1 (place) に N2 が あります/います
  //           N1 は N2 (place) に あります/います  ·  N1 の N2 (まえ/うえ/した/なか)
  // ════════════════════════════════════════════════════════
  { id:'n5_10_01', lesson:10, level:'N5', word:'おとこのひと', reading:'おとこのひと', meaning:'Man', meaningNepali:'पुरुष / मान्छे', kanjiCharacters:['男','人'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あそこにおとこのひとがいます。', reading:'あそこにおとこのひとがいます。', english:'There is a man over there.', nepali:'त्यहाँ एकजना पुरुष हुनुहुन्छ।' }]},
  { id:'n5_10_02', lesson:10, level:'N5', word:'おんなのひと', reading:'おんなのひと', meaning:'Woman', meaningNepali:'महिला / स्त्री', kanjiCharacters:['女','人'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おんなのひとがはなしています。', reading:'おんなのひとがはなしています。', english:'A woman is talking.', nepali:'एकजना महिला बोल्दै हुनुहुन्छ।' }]},
  { id:'n5_10_03', lesson:10, level:'N5', word:'おとこのこ', reading:'おとこのこ', meaning:'Boy', meaningNepali:'केटा (बालक)', kanjiCharacters:['男','子'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おとこのこがこうえんであそんでいます。', reading:'おとこのこがこうえんであそんでいます。', english:'A boy is playing in the park.', nepali:'केटा पार्कमा खेल्दैछ।' }]},
  { id:'n5_10_04', lesson:10, level:'N5', word:'おんなのこ', reading:'おんなのこ', meaning:'Girl', meaningNepali:'केटी (बालिका)', kanjiCharacters:['女','子'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おんなのこがほんをよんでいます。', reading:'おんなのこがほんをよんでいます。', english:'A girl is reading a book.', nepali:'केटी किताब पढ्दैछे।' }]},
  { id:'n5_10_05', lesson:10, level:'N5', word:'いぬ', reading:'いぬ', meaning:'Dog', meaningNepali:'कुकुर', kanjiCharacters:['犬'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にわにいぬがいます。', reading:'にわにいぬがいます。', english:'There is a dog in the garden.', nepali:'बगैंचामा कुकुर छ।' }]},
  { id:'n5_10_06', lesson:10, level:'N5', word:'ねこ', reading:'ねこ', meaning:'Cat', meaningNepali:'बिरालो', kanjiCharacters:['猫'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'つくえのしたにねこがいます。', reading:'つくえのしたにねこがいます。', english:'There is a cat under the desk.', nepali:'डेस्कको मुनि बिरालो छ।' }]},
  { id:'n5_10_07', lesson:10, level:'N5', word:'き', reading:'き', meaning:'Tree / Wood', meaningNepali:'रूख / काठ', kanjiCharacters:['木'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こうえんに大きなきがあります。', reading:'こうえんにおおきなきがあります。', english:'There is a big tree in the park.', nepali:'पार्कमा एउटा ठूलो रूख छ।' }]},
  { id:'n5_10_08', lesson:10, level:'N5', word:'もの', reading:'もの', meaning:'Thing / Object', meaningNepali:'चीज / वस्तु', kanjiCharacters:['物'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'はこのなかにいろいろなものがあります。', reading:'はこのなかにいろいろなものがあります。', english:'There are various things in the box.', nepali:'बाकसभित्र विभिन्न चीजहरू छन्।' }]},
  { id:'n5_10_09', lesson:10, level:'N5', word:'フィルム', reading:'フィルム', meaning:'Film', meaningNepali:'फिल्म / रイル', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'カメラのフィルムをかいました。', reading:'カメラのフィルムをかいました。', english:'I bought camera film.', nepali:'मैले क्यामेराको रिल किनें।' }]},
  { id:'n5_10_10', lesson:10, level:'N5', word:'でんち', reading:'でんち', meaning:'Battery', meaningNepali:'ब्याट्री', kanjiCharacters:['電','池'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんちをこうかんします。', reading:'でんちをこうかんします。', english:'I will change the battery.', nepali:'म ब्याट्री फेर्छु।' }]},
  { id:'n5_10_11', lesson:10, level:'N5', word:'はこ', reading:'はこ', meaning:'Box', meaningNepali:'बाकस / बाक्स', kanjiCharacters:['箱'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このはこはおもいです。', reading:'このはこはおもいです。', english:'This box is heavy.', nepali:'यो बाकस भारी छ।' }]},
  { id:'n5_10_12', lesson:10, level:'N5', word:'スイッチ', reading:'スイッチ', meaning:'Switch', meaningNepali:'स्विच', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'スイッチをおしてください。', reading:'スイッチをおしてください。', english:'Please press the switch.', nepali:'कृपया स्विच थिच्नुहोस्।' }]},
  { id:'n5_10_13', lesson:10, level:'N5', word:'れいぞうこ', reading:'れいぞうこ', meaning:'Refrigerator / Fridge', meaningNepali:'फ्रिज / फ्रिज', kanjiCharacters:['冷','蔵','庫'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'れいぞうこのなかにみずがあります。', reading:'れいぞうこのなかにみずがあります。', english:'There is water in the fridge.', nepali:'फ्रिजभित्र पानी छ।' }]},
  { id:'n5_10_14', lesson:10, level:'N5', word:'テーブル', reading:'テーブル', meaning:'Table', meaningNepali:'टेबुल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'テーブルのうえにパンがあります。', reading:'テーブルのうえにパンがあります。', english:'There is bread on the table.', nepali:'टेबुलमा पाउरोटी छ।' }]},
  { id:'n5_10_15', lesson:10, level:'N5', word:'ベッド', reading:'ベッド', meaning:'Bed', meaningNepali:'खाट / बेड', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ベッドのうえでねます。', reading:'ベッドのうえでねます。', english:'I sleep on the bed.', nepali:'म खाटमा सुत्छु।' }]},
  { id:'n5_10_16', lesson:10, level:'N5', word:'たな', reading:'たな', meaning:'Shelf / Bookshelf', meaningNepali:'दराज / र्याक', kanjiCharacters:['棚'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'たなにほんをならべます。', reading:'たなにほんをならべます。', english:'I arrange books on the shelf.', nepali:'म र्याकमा किताबहरू मिलाउँछु।' }]},
  { id:'n5_10_17', lesson:10, level:'N5', word:'ドア', reading:'ドア', meaning:'Door', meaningNepali:'ढोका', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ドアをあけてください。', reading:'ドアをあけてください。', english:'Please open the door.', nepali:'कृपया ढोका खोल्नुहोस्।' }]},
  { id:'n5_10_18', lesson:10, level:'N5', word:'まど', reading:'まど', meaning:'Window', meaningNepali:'झ्याल', kanjiCharacters:['窓'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まどをしめてください。', reading:'まどをしめてください。', english:'Please close the window.', nepali:'कृपया झ्याल ढोका बन्द गर्नुहोस्।' }]},
  { id:'n5_10_19', lesson:10, level:'N5', word:'ポスト', reading:'ポスト', meaning:'Postbox / Mailbox', meaningNepali:'पत्र मञ्जुषा / हुलाक बाकस', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ポストにてがみをいれました。', reading:'ポストにてがみをいれました。', english:'I posted a letter in the mailbox.', nepali:'मैले हुलाक बाकसमा पत्र खसालेँ।' }]},
  { id:'n5_10_20', lesson:10, level:'N5', word:'ビル', reading:'ビル', meaning:'Building', meaningNepali:'भवन / बिल्डिङ', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'たかいビルがたくさんあります。', reading:'たかいビルがたくさんあります。', english:'There are many tall buildings.', nepali:'धेरै अग्ला भवनहरू छन्।' }]},
  { id:'n5_10_21', lesson:10, level:'N5', word:'コンビニ', reading:'コンビニ', meaning:'Convenience store', meaningNepali:'सुविधाजनक पसल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'コンビニでお弁当をかいました。', reading:'コンビニでおべんとうをかいました。', english:'I bought a bento at the convenience store.', nepali:'मैले पसलबाट खाजा किनें।' }]},
  { id:'n5_10_22', lesson:10, level:'N5', word:'のりば', reading:'のりば', meaning:'Bus stop / Taxi stand / Platform', meaningNepali:'चढ्ने ठाउँ / बिसौनी', kanjiCharacters:['乗','り','場'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'バスののりばはどこですか。', reading:'バスののりばはどこですか。', english:'Where is the bus stop?', nepali:'बस स्टप कहाँ छ?' }]},
  { id:'n5_10_23', lesson:10, level:'N5', word:'けん', reading:'けん', meaning:'Prefecture', meaningNepali:'अञ्चल / प्रदेश', kanjiCharacters:['県'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'わたしはかながわけんにすんでいます。', reading:'わたしはかながわけんにすんでいます。', english:'I live in Kanagawa Prefecture.', nepali:'म कानागावा प्रदेशमा बस्छु।' }]},
  { id:'n5_10_24', lesson:10, level:'N5', word:'あいだ', reading:'あいだ', meaning:'Between', meaningNepali:'बीचमा', kanjiCharacters:['間'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ぎんこうとゆうびんきょくのあいだにあります。', reading:'ぎんこうとゆうびんきょくのあいだにあります。', english:'It is between the bank and post office.', nepali:'यो बैंक र हुलाक घरको बीचमा छ।' }]}
];
