// ============================================================
// MINNA NO NIHONGO N5 — Complete Vocabulary & Grammar
// SOURCE: Minna no Nihongo I (Translations & Grammar Notes)
// LESSONS 1–5  (Full coverage, no omissions)
// English + Nepali meanings · Grammar sentences per word
// ============================================================

import type { VocabItem } from './nihongo-vocab';

export const N5_LESSONS_1TO5: VocabItem[] = [

  // ════════════════════════════════════════════════════════
  // LESSON 1 — People, Occupations & the は〜です Structure
  // Grammar: N は N です / N は N じゃ(では)ありません / N は N ですか
  // ════════════════════════════════════════════════════════
  { id:'n5_1_01', lesson:1, level:'N5', word:'わたし', reading:'わたし', meaning:'I / Me', meaningNepali:'म', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[
      { japanese:'わたしはマリアです。', reading:'わたしはマリアです。', english:'I am Maria.', nepali:'म मारिया हुँ।' },
      { japanese:'わたしはがくせいじゃありません。', reading:'わたしはがくせいじゃありません。', english:'I am not a student.', nepali:'म विद्यार्थी होइन।' }
    ]},
  { id:'n5_1_02', lesson:1, level:'N5', word:'わたしたち', reading:'わたしたち', meaning:'We / Us', meaningNepali:'हामी', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'わたしたちはともだちです。', reading:'わたしたちはともだちです。', english:'We are friends.', nepali:'हामी साथीहरू हौं।' }]},
  { id:'n5_1_03', lesson:1, level:'N5', word:'あなた', reading:'あなた', meaning:'You', meaningNepali:'तपाईं / तिमी', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'あなたはがくせいですか。', reading:'あなたはがくせいですか。', english:'Are you a student?', nepali:'के तपाईं विद्यार्थी हुनुहुन्छ?' }]},
  { id:'n5_1_04', lesson:1, level:'N5', word:'あのひと', reading:'あのひと', meaning:'That person (over there)', meaningNepali:'त्यो मान्छे (टाढा)', kanjiCharacters:['人'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あのひとはだれですか。', reading:'あのひとはだれですか。', english:'Who is that person?', nepali:'त्यो मान्छे को हुनुहुन्छ?' }]},
  { id:'n5_1_05', lesson:1, level:'N5', word:'あのかた', reading:'あのかた', meaning:'That person (polite)', meaningNepali:'त्यो हजुर (सम्मानित)', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あのかたはどなたですか。', reading:'あのかたはどなたですか。', english:'Who is that person (polite)?', nepali:'त्यो हजुर को हुनुहुन्छ?' }]},
  { id:'n5_1_06', lesson:1, level:'N5', word:'〜さん', reading:'〜さん', meaning:'Mr. / Ms. / Mrs. (honorific)', meaningNepali:'जी / श्री / श्रीमती', kanjiCharacters:[], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'ミラーさんはせんせいですか。', reading:'ミラーさんはせんせいですか。', english:'Is Mr. Miller a teacher?', nepali:'मिलर-जी शिक्षक हुनुहुन्छ?' }]},
  { id:'n5_1_07', lesson:1, level:'N5', word:'〜ちゃん', reading:'〜ちゃん', meaning:'Familiar honorific (children / close friends)', meaningNepali:'माया गरी बोलाउने तरिका', kanjiCharacters:[], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'さくらちゃんはなんさいですか。', reading:'さくらちゃんはなんさいですか。', english:'How old is Sakura?', nepali:'साकुरा कति वर्षको हो?' }]},
  { id:'n5_1_08', lesson:1, level:'N5', word:'〜くん', reading:'〜くん', meaning:'Honorific for younger males', meaningNepali:'केटाहरूका लागि सम्बोधन', kanjiCharacters:[], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'やまだくんはがくせいです。', reading:'やまだくんはがくせいです。', english:'Yamada (kun) is a student.', nepali:'यामाडा विद्यार्थी हो।' }]},
  { id:'n5_1_09', lesson:1, level:'N5', word:'せんせい', reading:'せんせい', meaning:'Teacher', meaningNepali:'शिक्षक / गुरु', kanjiCharacters:['先','生'], partOfSpeech:'Noun',
    grammarSentences:[
      { japanese:'やまださんはせんせいです。', reading:'やまださんはせんせいです。', english:'Mr. Yamada is a teacher.', nepali:'यामाडा-जी शिक्षक हुनुहुन्छ।' },
      { japanese:'わたしはせんせいじゃありません。', reading:'わたしはせんせいじゃありません。', english:'I am not a teacher.', nepali:'म शिक्षक होइन।' }
    ]},
  { id:'n5_1_10', lesson:1, level:'N5', word:'きょうし', reading:'きょうし', meaning:'Teacher (professional title)', meaningNepali:'शिक्षक (पेशागत)', kanjiCharacters:['教','師'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かれはきょうしです。', reading:'かれはきょうしです。', english:'He is a teacher.', nepali:'उहाँ शिक्षक हुनुहुन्छ।' }]},
  { id:'n5_1_11', lesson:1, level:'N5', word:'がくせい', reading:'がくせい', meaning:'Student', meaningNepali:'विद्यार्थी', kanjiCharacters:['学','生'], partOfSpeech:'Noun',
    grammarSentences:[
      { japanese:'わたしはがくせいです。', reading:'わたしはがくせいです。', english:'I am a student.', nepali:'म विद्यार्थी हुँ।' },
      { japanese:'あのひとはがくせいですか。', reading:'あのひとはがくせいですか。', english:'Is that person a student?', nepali:'त्यो मान्छे विद्यार्थी हुनुहुन्छ?' }
    ]},
  { id:'n5_1_12', lesson:1, level:'N5', word:'かいしゃいん', reading:'かいしゃいん', meaning:'Company employee', meaningNepali:'कम्पनी कर्मचारी', kanjiCharacters:['会','社','員'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ちちはかいしゃいんです。', reading:'ちちはかいしゃいんです。', english:'My father is a company employee.', nepali:'मेरो बुबा कम्पनीमा काम गर्नुहुन्छ।' }]},
  { id:'n5_1_13', lesson:1, level:'N5', word:'しゃいん', reading:'しゃいん', meaning:'Company worker / Staff', meaningNepali:'कम्पनी कर्मी', kanjiCharacters:['社','員'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かのじょはしゃいんです。', reading:'かのじょはしゃいんです。', english:'She is a company worker.', nepali:'उनी कम्पनी कर्मी हुन्।' }]},
  { id:'n5_1_14', lesson:1, level:'N5', word:'ぎんこういん', reading:'ぎんこういん', meaning:'Bank employee', meaningNepali:'बैंक कर्मचारी', kanjiCharacters:['銀','行','員'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かれはぎんこういんです。', reading:'かれはぎんこういんです。', english:'He is a bank employee.', nepali:'उहाँ बैंक कर्मचारी हुनुहुन्छ।' }]},
  { id:'n5_1_15', lesson:1, level:'N5', word:'いしゃ', reading:'いしゃ', meaning:'Doctor', meaningNepali:'डाक्टर', kanjiCharacters:['医','者'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あのかたはいしゃです。', reading:'あのかたはいしゃです。', english:'That person is a doctor.', nepali:'त्यो हजुर डाक्टर हुनुहुन्छ।' }]},
  { id:'n5_1_16', lesson:1, level:'N5', word:'けんきゅうしゃ', reading:'けんきゅうしゃ', meaning:'Researcher', meaningNepali:'अनुसन्धानकर्ता', kanjiCharacters:['研','究','者'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'たなかさんはけんきゅうしゃです。', reading:'たなかさんはけんきゅうしゃです。', english:'Mr. Tanaka is a researcher.', nepali:'तानाका-जी अनुसन्धानकर्ता हुनुहुन्छ।' }]},
  { id:'n5_1_17', lesson:1, level:'N5', word:'エンジニア', reading:'エンジニア', meaning:'Engineer', meaningNepali:'इन्जिनियर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'わたしはエンジニアです。', reading:'わたしはエンジニアです。', english:'I am an engineer.', nepali:'म इन्जिनियर हुँ।' }]},
  { id:'n5_1_18', lesson:1, level:'N5', word:'だいがく', reading:'だいがく', meaning:'University', meaningNepali:'विश्वविद्यालय', kanjiCharacters:['大','学'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'わたしはだいがくのがくせいです。', reading:'わたしはだいがくのがくせいです。', english:'I am a university student.', nepali:'म विश्वविद्यालयको विद्यार्थी हुँ।' }]},
  { id:'n5_1_19', lesson:1, level:'N5', word:'びょういん', reading:'びょういん', meaning:'Hospital', meaningNepali:'अस्पताल', kanjiCharacters:['病','院'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このびょういんはおおきいです。', reading:'このびょういんはおおきいです。', english:'This hospital is big.', nepali:'यो अस्पताल ठूलो छ।' }]},
  { id:'n5_1_20', lesson:1, level:'N5', word:'でんき', reading:'でんき', meaning:'Electric / Electronics (company type)', meaningNepali:'विद्युत / इलेक्ट्रोनिक्स', kanjiCharacters:['電','気'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんきのかいしゃにはたらいています。', reading:'でんきのかいしゃにはたらいています。', english:'I work at an electronics company.', nepali:'म इलेक्ट्रोनिक्स कम्पनीमा काम गर्छु।' }]},
  { id:'n5_1_21', lesson:1, level:'N5', word:'〜さい', reading:'〜さい', meaning:'~ years old', meaningNepali:'~ वर्ष उमेर', kanjiCharacters:['歳'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'わたしは２２さいです。', reading:'わたしはにじゅうにさいです。', english:'I am 22 years old.', nepali:'म २२ वर्षको छु।' }]},
  { id:'n5_1_22', lesson:1, level:'N5', word:'なんさい', reading:'なんさい', meaning:'How old?', meaningNepali:'कति उमेर?', kanjiCharacters:['何','歳'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'おこさんはなんさいですか。', reading:'おこさんはなんさいですか。', english:'How old is your child?', nepali:'तपाईंको बच्चा कति वर्षको हो?' }]},
  { id:'n5_1_23', lesson:1, level:'N5', word:'はい', reading:'はい', meaning:'Yes', meaningNepali:'हो / हजुर', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'はい、そうです。', reading:'はい、そうです。', english:'Yes, that is right.', nepali:'हो, ठिकै छ।' }]},
  { id:'n5_1_24', lesson:1, level:'N5', word:'いいえ', reading:'いいえ', meaning:'No', meaningNepali:'होइन / भएन', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'いいえ、ちがいます。', reading:'いいえ、ちがいます。', english:'No, that is wrong.', nepali:'होइन, त्यो गलत हो।' }]},
  { id:'n5_1_25', lesson:1, level:'N5', word:'そうです', reading:'そうです', meaning:'That is right / Correct', meaningNepali:'ठिक छ / सही छ', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'はい、そうです。', reading:'はい、そうです。', english:'Yes, that is right.', nepali:'हो, ठिकै छ।' }]},
  { id:'n5_1_26', lesson:1, level:'N5', word:'ちがいます', reading:'ちがいます', meaning:'That is wrong / Different', meaningNepali:'गलत छ / फरक छ', kanjiCharacters:['違'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'いいえ、ちがいます。', reading:'いいえ、ちがいます。', english:'No, that is wrong.', nepali:'होइन, त्यो गलत हो।' }]},
  { id:'n5_1_27', lesson:1, level:'N5', word:'〜じん', reading:'〜じん', meaning:'Person from ~ (nationality)', meaningNepali:'~ देशको मान्छे', kanjiCharacters:['人'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'わたしはにほんじんです。', reading:'わたしはにほんじんです。', english:'I am Japanese.', nepali:'म जापानी हुँ।' }]},
  { id:'n5_1_28', lesson:1, level:'N5', word:'にほん', reading:'にほん', meaning:'Japan', meaningNepali:'जापान', kanjiCharacters:['日','本'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にほんはうつくしいくにです。', reading:'にほんはうつくしいくにです。', english:'Japan is a beautiful country.', nepali:'जापान सुन्दर देश हो।' }]},
  { id:'n5_1_29', lesson:1, level:'N5', word:'アメリカ', reading:'アメリカ', meaning:'America / USA', meaningNepali:'अमेरिका', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ミラーさんはアメリカじんです。', reading:'ミラーさんはアメリカじんです。', english:'Mr. Miller is American.', nepali:'मिलर-जी अमेरिकन हुनुहुन्छ।' }]},
  { id:'n5_1_30', lesson:1, level:'N5', word:'どこ', reading:'どこ', meaning:'Where', meaningNepali:'कहाँ', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'トイレはどこですか。', reading:'トイレはどこですか。', english:'Where is the toilet?', nepali:'शौचालय कहाँ छ?' }]},
  { id:'n5_1_31', lesson:1, level:'N5', word:'おくに', reading:'おくに', meaning:'Your country (polite)', meaningNepali:'तपाईंको देश (सम्मानित)', kanjiCharacters:['国'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おくにはどちらですか。', reading:'おくにはどちらですか。', english:'Where are you from?', nepali:'तपाईं कुन देशबाट हुनुहुन्छ?' }]},
  { id:'n5_1_32', lesson:1, level:'N5', word:'しつれいですが', reading:'しつれいですが', meaning:'Excuse me, but... (polite opening)', meaningNepali:'माफ गर्नुस् / क्षमा गर्नुस्', kanjiCharacters:['失','礼'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'しつれいですが、おなまえは？', reading:'しつれいですが、おなまえは？', english:'Excuse me, what is your name?', nepali:'माफ गर्नुस्, तपाईंको नाम के हो?' }]},
  { id:'n5_1_33', lesson:1, level:'N5', word:'おなまえ', reading:'おなまえ', meaning:'Your name (polite)', meaningNepali:'तपाईंको नाम (सम्मानित)', kanjiCharacters:['名'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おなまえはなんですか。', reading:'おなまえはなんですか。', english:'What is your name?', nepali:'तपाईंको नाम के हो?' }]},
  { id:'n5_1_34', lesson:1, level:'N5', word:'〜語', reading:'〜ご', meaning:'~ language', meaningNepali:'~ भाषा', kanjiCharacters:['語'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'にほんごをべんきょうします。', reading:'にほんごをべんきょうします。', english:'I study Japanese.', nepali:'म जापानी भाषा पढ्छु।' }]},
  { id:'n5_1_35', lesson:1, level:'N5', word:'なん / なに', reading:'なん/なに', meaning:'What', meaningNepali:'के', kanjiCharacters:['何'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'これはなんですか。', reading:'これはなんですか。', english:'What is this?', nepali:'यो के हो?' }]},
  { id:'n5_1_36', lesson:1, level:'N5', word:'だれ', reading:'だれ', meaning:'Who', meaningNepali:'को', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'あのひとはだれですか。', reading:'あのひとはだれですか。', english:'Who is that person?', nepali:'त्यो मान्छे को हुनुहुन्छ?' }]},
  { id:'n5_1_37', lesson:1, level:'N5', word:'どなた', reading:'どなた', meaning:'Who (polite)', meaningNepali:'को हजुर (सम्मानित)', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'あのかたはどなたですか。', reading:'あのかたはどなたですか。', english:'Who is that person (polite)?', nepali:'त्यो हजुर को हुनुहुन्छ?' }]},
  { id:'n5_1_38', lesson:1, level:'N5', word:'も', reading:'も', meaning:'Also / Too', meaningNepali:'पनि', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'わたしもがくせいです。', reading:'わたしもがくせいです。', english:'I am also a student.', nepali:'म पनि विद्यार्थी हुँ।' }]},
  { id:'n5_1_39', lesson:1, level:'N5', word:'の', reading:'の', meaning:'Possessive particle (of)', meaningNepali:'को (स्वामित्व)', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'これはわたしのほんです。', reading:'これはわたしのほんです。', english:'This is my book.', nepali:'यो मेरो किताब हो।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 2 — This / That / Which & Objects
  // Grammar: これ/それ/あれ/どれ は N です · この/その/あの N · 〜の (possession) · いくら
  // ════════════════════════════════════════════════════════
  { id:'n5_2_01', lesson:2, level:'N5', word:'これ', reading:'これ', meaning:'This (near speaker)', meaningNepali:'यो (वक्ता नजिक)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'これはわたしのほんです。', reading:'これはわたしのほんです。', english:'This is my book.', nepali:'यो मेरो किताब हो।' }]},
  { id:'n5_2_02', lesson:2, level:'N5', word:'それ', reading:'それ', meaning:'That (near listener)', meaningNepali:'त्यो (श्रोता नजिक)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'それはなんですか。', reading:'それはなんですか。', english:'What is that?', nepali:'त्यो के हो?' }]},
  { id:'n5_2_03', lesson:2, level:'N5', word:'あれ', reading:'あれ', meaning:'That (far from both)', meaningNepali:'त्यो (दुवैबाट टाढा)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'あれはだれのかばんですか。', reading:'あれはだれのかばんですか。', english:'Whose bag is that over there?', nepali:'त्यो कसको झोला हो?' }]},
  { id:'n5_2_04', lesson:2, level:'N5', word:'どれ', reading:'どれ', meaning:'Which one?', meaningNepali:'कुन?', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'あなたのほんはどれですか。', reading:'あなたのほんはどれですか。', english:'Which one is your book?', nepali:'तपाईंको किताब कुन हो?' }]},
  { id:'n5_2_05', lesson:2, level:'N5', word:'この', reading:'この', meaning:'This ~ (adjective form)', meaningNepali:'यो ~ (विशेषण)', kanjiCharacters:[], partOfSpeech:'Determiner',
    grammarSentences:[{ japanese:'このほんはおもしろいです。', reading:'このほんはおもしろいです。', english:'This book is interesting.', nepali:'यो किताब रोचक छ।' }]},
  { id:'n5_2_06', lesson:2, level:'N5', word:'その', reading:'その', meaning:'That ~ (near listener)', meaningNepali:'त्यो ~ (श्रोता नजिक)', kanjiCharacters:[], partOfSpeech:'Determiner',
    grammarSentences:[{ japanese:'そのかばんはたかいですか。', reading:'そのかばんはたかいですか。', english:'Is that bag expensive?', nepali:'त्यो झोला महँगो छ?' }]},
  { id:'n5_2_07', lesson:2, level:'N5', word:'あの', reading:'あの', meaning:'That ~ (far from both)', meaningNepali:'त्यो ~ (टाढा)', kanjiCharacters:[], partOfSpeech:'Determiner',
    grammarSentences:[{ japanese:'あのひとはだれですか。', reading:'あのひとはだれですか。', english:'Who is that person?', nepali:'त्यो मान्छे को हुनुहुन्छ?' }]},
  { id:'n5_2_08', lesson:2, level:'N5', word:'どの', reading:'どの', meaning:'Which ~ ?', meaningNepali:'कुन ~?', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'どのほんがあなたのですか。', reading:'どのほんがあなたのですか。', english:'Which book is yours?', nepali:'तपाईंको कुन किताब हो?' }]},
  { id:'n5_2_09', lesson:2, level:'N5', word:'ほん', reading:'ほん', meaning:'Book', meaningNepali:'किताब', kanjiCharacters:['本'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'これはにほんごのほんです。', reading:'これはにほんごのほんです。', english:'This is a Japanese language book.', nepali:'यो जापानी भाषाको किताब हो।' }]},
  { id:'n5_2_10', lesson:2, level:'N5', word:'じしょ', reading:'じしょ', meaning:'Dictionary', meaningNepali:'शब्दकोश', kanjiCharacters:['辞','書'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'これはにほんごのじしょです。', reading:'これはにほんごのじしょです。', english:'This is a Japanese dictionary.', nepali:'यो जापानी शब्दकोश हो।' }]},
  { id:'n5_2_11', lesson:2, level:'N5', word:'ざっし', reading:'ざっし', meaning:'Magazine', meaningNepali:'पत्रिका', kanjiCharacters:['雑','誌'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'そのざっしはおもしろいですか。', reading:'そのざっしはおもしろいですか。', english:'Is that magazine interesting?', nepali:'त्यो पत्रिका रोचक छ?' }]},
  { id:'n5_2_12', lesson:2, level:'N5', word:'しんぶん', reading:'しんぶん', meaning:'Newspaper', meaningNepali:'समाचारपत्र', kanjiCharacters:['新','聞'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいにちしんぶんをよみます。', reading:'まいにちしんぶんをよみます。', english:'I read the newspaper every day.', nepali:'म हरेक दिन अखबार पढ्छु।' }]},
  { id:'n5_2_13', lesson:2, level:'N5', word:'ノート', reading:'ノート', meaning:'Notebook', meaningNepali:'नोटबुक', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このノートはいくらですか。', reading:'このノートはいくらですか。', english:'How much is this notebook?', nepali:'यो नोटबुक कति पर्छ?' }]},
  { id:'n5_2_14', lesson:2, level:'N5', word:'テキスト', reading:'テキスト', meaning:'Textbook', meaningNepali:'पाठ्यपुस्तक', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このテキストはやさしいです。', reading:'このテキストはやさしいです。', english:'This textbook is easy.', nepali:'यो पाठ्यपुस्तक सजिलो छ।' }]},
  { id:'n5_2_15', lesson:2, level:'N5', word:'えんぴつ', reading:'えんぴつ', meaning:'Pencil', meaningNepali:'पेन्सिल', kanjiCharacters:['鉛','筆'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'えんぴつをかしてください。', reading:'えんぴつをかしてください。', english:'Please lend me a pencil.', nepali:'मलाई पेन्सिल दिनुस् न।' }]},
  { id:'n5_2_16', lesson:2, level:'N5', word:'ボールペン', reading:'ボールペン', meaning:'Ball-point pen', meaningNepali:'बलपेन', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ボールペンでかいてください。', reading:'ボールペンでかいてください。', english:'Please write with a ball-point pen.', nepali:'कृपया बलपेनले लेख्नुस्।' }]},
  { id:'n5_2_17', lesson:2, level:'N5', word:'シャープペンシル', reading:'シャープペンシル', meaning:'Mechanical pencil', meaningNepali:'मेकानिकल पेन्सिल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'シャープペンシルをかいました。', reading:'シャープペンシルをかいました。', english:'I bought a mechanical pencil.', nepali:'मैले मेकानिकल पेन्सिल किनें।' }]},
  { id:'n5_2_18', lesson:2, level:'N5', word:'かばん', reading:'かばん', meaning:'Bag', meaningNepali:'झोला / ब्याग', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このかばんはたかいです。', reading:'このかばんはたかいです。', english:'This bag is expensive.', nepali:'यो झोला महँगो छ।' }]},
  { id:'n5_2_19', lesson:2, level:'N5', word:'かさ', reading:'かさ', meaning:'Umbrella', meaningNepali:'छाता', kanjiCharacters:['傘'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'これはだれのかさですか。', reading:'これはだれのかさですか。', english:'Whose umbrella is this?', nepali:'यो कसको छाता हो?' }]},
  { id:'n5_2_20', lesson:2, level:'N5', word:'くつ', reading:'くつ', meaning:'Shoes', meaningNepali:'जुत्ता', kanjiCharacters:['靴'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このくつはいくらですか。', reading:'このくつはいくらですか。', english:'How much are these shoes?', nepali:'यो जुत्ता कति पर्छ?' }]},
  { id:'n5_2_21', lesson:2, level:'N5', word:'ネクタイ', reading:'ネクタイ', meaning:'Necktie', meaningNepali:'टाई', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'そのネクタイはすてきですね。', reading:'そのネクタイはすてきですね。', english:'That necktie is nice, isn\'t it?', nepali:'त्यो टाई राम्रो छ हैन?' }]},
  { id:'n5_2_22', lesson:2, level:'N5', word:'とけい', reading:'とけい', meaning:'Watch / Clock', meaningNepali:'घडी', kanjiCharacters:['時','計'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このとけいはにほんせいです。', reading:'このとけいはにほんせいです。', english:'This watch is made in Japan.', nepali:'यो घडी जापानमा बनेको हो।' }]},
  { id:'n5_2_23', lesson:2, level:'N5', word:'カメラ', reading:'カメラ', meaning:'Camera', meaningNepali:'क्यामेरा', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このカメラはいくらですか。', reading:'このカメラはいくらですか。', english:'How much is this camera?', nepali:'यो क्यामेरा कति पर्छ?' }]},
  { id:'n5_2_24', lesson:2, level:'N5', word:'でんしじしょ', reading:'でんしじしょ', meaning:'Electronic dictionary', meaningNepali:'इलेक्ट्रोनिक शब्दकोश', kanjiCharacters:['電','子','辞','書'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんしじしょはべんりです。', reading:'でんしじしょはべんりです。', english:'An electronic dictionary is convenient.', nepali:'इलेक्ट्रोनिक शब्दकोश सुविधाजनक छ।' }]},
  { id:'n5_2_25', lesson:2, level:'N5', word:'テレビ', reading:'テレビ', meaning:'Television / TV', meaningNepali:'टेलिभिजन', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいばんテレビをみます。', reading:'まいばんテレビをみます。', english:'I watch TV every evening.', nepali:'म हरेक साँझ टेलिभिजन हेर्छु।' }]},
  { id:'n5_2_26', lesson:2, level:'N5', word:'ラジオ', reading:'ラジオ', meaning:'Radio', meaningNepali:'रेडियो', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このラジオはアメリカせいです。', reading:'このラジオはアメリカせいです。', english:'This radio is made in America.', nepali:'यो रेडियो अमेरिकामा बनेको हो।' }]},
  { id:'n5_2_27', lesson:2, level:'N5', word:'テープレコーダー', reading:'テープレコーダー', meaning:'Tape recorder', meaningNepali:'टेप रेकर्डर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'テープレコーダーをかいました。', reading:'テープレコーダーをかいました。', english:'I bought a tape recorder.', nepali:'मैले टेप रेकर्डर किनें।' }]},
  { id:'n5_2_28', lesson:2, level:'N5', word:'パソコン', reading:'パソコン', meaning:'Personal computer / PC', meaningNepali:'पर्सनल कम्प्युटर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このパソコンはあたらしいです。', reading:'このパソコンはあたらしいです。', english:'This computer is new.', nepali:'यो कम्प्युटर नयाँ छ।' }]},
  { id:'n5_2_29', lesson:2, level:'N5', word:'くるま', reading:'くるま', meaning:'Car', meaningNepali:'गाडी / कार', kanjiCharacters:['車'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あれはわたしのくるまです。', reading:'あれはわたしのくるまです。', english:'That over there is my car.', nepali:'त्यो मेरो गाडी हो।' }]},
  { id:'n5_2_30', lesson:2, level:'N5', word:'つくえ', reading:'つくえ', meaning:'Desk', meaningNepali:'डेस्क / टेबुल', kanjiCharacters:['机'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'つくえのうえにほんがあります。', reading:'つくえのうえにほんがあります。', english:'There is a book on the desk.', nepali:'डेस्कको माथि किताब छ।' }]},
  { id:'n5_2_31', lesson:2, level:'N5', word:'いす', reading:'いす', meaning:'Chair', meaningNepali:'कुर्सी', kanjiCharacters:['椅','子'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'いすのしたにねこがいます。', reading:'いすのしたにねこがいます。', english:'There is a cat under the chair.', nepali:'कुर्सीको मुनि बिरालो छ।' }]},
  { id:'n5_2_32', lesson:2, level:'N5', word:'チョコレート', reading:'チョコレート', meaning:'Chocolate', meaningNepali:'चकलेट', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'このチョコレートはおいしいです。', reading:'このチョコレートはおいしいです。', english:'This chocolate is delicious.', nepali:'यो चकलेट मिठो छ।' }]},
  { id:'n5_2_33', lesson:2, level:'N5', word:'コーヒー', reading:'コーヒー', meaning:'Coffee', meaningNepali:'कफी', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'コーヒーをいっぱいのみました。', reading:'コーヒーをいっぱいのみました。', english:'I drank one cup of coffee.', nepali:'मैले एक कप कफी खाएँ।' }]},
  { id:'n5_2_34', lesson:2, level:'N5', word:'おみやげ', reading:'おみやげ', meaning:'Souvenir', meaningNepali:'उपहार / सुभेच्छा', kanjiCharacters:['土','産'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にほんのおみやげをもってきました。', reading:'にほんのおみやげをもってきました。', english:'I brought a souvenir from Japan.', nepali:'मैले जापानबाट उपहार ल्याएँ।' }]},
  { id:'n5_2_35', lesson:2, level:'N5', word:'〜せい', reading:'〜せい', meaning:'Made in ~', meaningNepali:'~ मा बनेको', kanjiCharacters:['製'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'このとけいはスイスせいです。', reading:'このとけいはスイスせいです。', english:'This watch is Swiss-made.', nepali:'यो घडी स्विट्जरल्याण्डमा बनेको हो।' }]},
  { id:'n5_2_36', lesson:2, level:'N5', word:'いくら', reading:'いくら', meaning:'How much?', meaningNepali:'कति पर्छ?', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'これはいくらですか。', reading:'これはいくらですか。', english:'How much is this?', nepali:'यो कति पर्छ?' }]},
  { id:'n5_2_37', lesson:2, level:'N5', word:'ひゃく', reading:'ひゃく', meaning:'100 (hundred)', meaningNepali:'एक सय', kanjiCharacters:['百'], partOfSpeech:'Number',
    grammarSentences:[{ japanese:'このほんはひゃくえんです。', reading:'このほんはひゃくえんです。', english:'This book is 100 yen.', nepali:'यो किताब १०० येन छ।' }]},
  { id:'n5_2_38', lesson:2, level:'N5', word:'せん', reading:'せん', meaning:'1,000 (thousand)', meaningNepali:'एक हजार', kanjiCharacters:['千'], partOfSpeech:'Number',
    grammarSentences:[{ japanese:'このかばんはせんえんです。', reading:'このかばんはせんえんです。', english:'This bag is 1,000 yen.', nepali:'यो झोला १,००० येन छ।' }]},
  { id:'n5_2_39', lesson:2, level:'N5', word:'まん', reading:'まん', meaning:'10,000 (ten thousand)', meaningNepali:'दश हजार', kanjiCharacters:['万'], partOfSpeech:'Number',
    grammarSentences:[{ japanese:'このとけいはいちまんえんです。', reading:'このとけいはいちまんえんです。', english:'This watch is 10,000 yen.', nepali:'यो घडी १०,००० येन छ।' }]},
  { id:'n5_2_40', lesson:2, level:'N5', word:'えん', reading:'えん', meaning:'Yen (Japanese currency)', meaningNepali:'येन (जापानी मुद्रा)', kanjiCharacters:['円'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ごひゃくえんです。', reading:'ごひゃくえんです。', english:'It is 500 yen.', nepali:'यो ५०० येन छ।' }]},
  { id:'n5_2_41', lesson:2, level:'N5', word:'すみません', reading:'すみません', meaning:'Excuse me / I\'m sorry', meaningNepali:'माफ गर्नुस् / क्षमा', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'すみません、これはいくらですか。', reading:'すみません、これはいくらですか。', english:'Excuse me, how much is this?', nepali:'माफ गर्नुस्, यो कति पर्छ?' }]},
  { id:'n5_2_42', lesson:2, level:'N5', word:'ちょっと', reading:'ちょっと', meaning:'A little / Just a moment', meaningNepali:'अलिकति / एक क्षण', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'ちょっとまってください。', reading:'ちょっとまってください。', english:'Please wait a moment.', nepali:'कृपया एक क्षण पर्खनुस्।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 3 — Places & Location
  // Grammar: ここ/そこ/あそこ は N です · N は (place) に あります/います · Position expressions
  // ════════════════════════════════════════════════════════
  { id:'n5_3_01', lesson:3, level:'N5', word:'ここ', reading:'ここ', meaning:'Here (near speaker)', meaningNepali:'यहाँ (वक्ता नजिक)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'ここはわたしのへやです。', reading:'ここはわたしのへやです。', english:'Here is my room.', nepali:'यहाँ मेरो कोठा हो।' }]},
  { id:'n5_3_02', lesson:3, level:'N5', word:'そこ', reading:'そこ', meaning:'There (near listener)', meaningNepali:'त्यहाँ (श्रोता नजिक)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'そこはなんですか。', reading:'そこはなんですか。', english:'What is that place there?', nepali:'त्यहाँ के छ?' }]},
  { id:'n5_3_03', lesson:3, level:'N5', word:'あそこ', reading:'あそこ', meaning:'Over there (far from both)', meaningNepali:'त्यहाँ (दुवैबाट टाढा)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'あそこはぎんこうです。', reading:'あそこはぎんこうです。', english:'Over there is a bank.', nepali:'त्यहाँ बैंक छ।' }]},
  { id:'n5_3_04', lesson:3, level:'N5', word:'こちら', reading:'こちら', meaning:'This way / This direction (polite)', meaningNepali:'यता (सम्मानित)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'こちらへどうぞ。', reading:'こちらへどうぞ。', english:'Please come this way.', nepali:'कृपया यताबाट आउनुस्।' }]},
  { id:'n5_3_05', lesson:3, level:'N5', word:'そちら', reading:'そちら', meaning:'That way (polite, near listener)', meaningNepali:'त्यता (सम्मानित, श्रोता नजिक)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'そちらはどちらですか。', reading:'そちらはどちらですか。', english:'Which way is that?', nepali:'त्यता कता हो?' }]},
  { id:'n5_3_06', lesson:3, level:'N5', word:'あちら', reading:'あちら', meaning:'That way (polite, far from both)', meaningNepali:'त्यता (सम्मानित, टाढा)', kanjiCharacters:[], partOfSpeech:'Pronoun',
    grammarSentences:[{ japanese:'あちらはこうばんです。', reading:'あちらはこうばんです。', english:'Over there is a police box.', nepali:'त्यता प्रहरी चौकी छ।' }]},
  { id:'n5_3_07', lesson:3, level:'N5', word:'どちら', reading:'どちら', meaning:'Which way / Where (polite)', meaningNepali:'कता / कुन (सम्मानित)', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'おくにはどちらですか。', reading:'おくにはどちらですか。', english:'Where are you from?', nepali:'तपाईं कुन देशबाट हुनुहुन्छ?' }]},
  { id:'n5_3_08', lesson:3, level:'N5', word:'きょうしつ', reading:'きょうしつ', meaning:'Classroom', meaningNepali:'कक्षाकोठा', kanjiCharacters:['教','室'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きょうしつはどこですか。', reading:'きょうしつはどこですか。', english:'Where is the classroom?', nepali:'कक्षाकोठा कहाँ छ?' }]},
  { id:'n5_3_09', lesson:3, level:'N5', word:'しょくどう', reading:'しょくどう', meaning:'Canteen / Cafeteria / Dining hall', meaningNepali:'क्यान्टिन / भोजनालय', kanjiCharacters:['食','堂'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'しょくどうはにかいにあります。', reading:'しょくどうはにかいにあります。', english:'The cafeteria is on the second floor.', nepali:'भोजनालय दोस्रो तलामा छ।' }]},
  { id:'n5_3_10', lesson:3, level:'N5', word:'じむしょ', reading:'じむしょ', meaning:'Office', meaningNepali:'कार्यालय', kanjiCharacters:['事','務','所'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'じむしょはいっかいです。', reading:'じむしょはいっかいです。', english:'The office is on the first floor.', nepali:'कार्यालय पहिलो तलामा छ।' }]},
  { id:'n5_3_11', lesson:3, level:'N5', word:'かいだん', reading:'かいだん', meaning:'Stairs', meaningNepali:'भर्‍याङ', kanjiCharacters:['階','段'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かいだんはあそこにあります。', reading:'かいだんはあそこにあります。', english:'The stairs are over there.', nepali:'भर्‍याङ त्यहाँ छ।' }]},
  { id:'n5_3_12', lesson:3, level:'N5', word:'エレベーター', reading:'エレベーター', meaning:'Elevator / Lift', meaningNepali:'लिफ्ट', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'エレベーターはどこですか。', reading:'エレベーターはどこですか。', english:'Where is the elevator?', nepali:'लिफ्ट कहाँ छ?' }]},
  { id:'n5_3_13', lesson:3, level:'N5', word:'トイレ', reading:'トイレ', meaning:'Toilet / Restroom', meaningNepali:'शौचालय', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'トイレはにかいにあります。', reading:'トイレはにかいにあります。', english:'The toilet is on the second floor.', nepali:'शौचालय दोस्रो तलामा छ।' }]},
  { id:'n5_3_14', lesson:3, level:'N5', word:'ロビー', reading:'ロビー', meaning:'Lobby', meaningNepali:'लबी', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ロビーはいっかいです。', reading:'ロビーはいっかいです。', english:'The lobby is on the first floor.', nepali:'लबी पहिलो तलामा छ।' }]},
  { id:'n5_3_15', lesson:3, level:'N5', word:'うけつけ', reading:'うけつけ', meaning:'Reception desk', meaningNepali:'रिसेप्सन', kanjiCharacters:['受','付'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'うけつけはいっかいにあります。', reading:'うけつけはいっかいにあります。', english:'The reception is on the first floor.', nepali:'रिसेप्सन पहिलो तलामा छ।' }]},
  { id:'n5_3_16', lesson:3, level:'N5', word:'かいぎしつ', reading:'かいぎしつ', meaning:'Meeting room / Conference room', meaningNepali:'बैठककोठा', kanjiCharacters:['会','議','室'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かいぎしつはよんかいです。', reading:'かいぎしつはよんかいです。', english:'The meeting room is on the 4th floor.', nepali:'बैठककोठा चौथो तलामा छ।' }]},
  { id:'n5_3_17', lesson:3, level:'N5', word:'〜かい', reading:'〜かい', meaning:'~ floor (of a building)', meaningNepali:'~ तला', kanjiCharacters:['階'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'わたしのへやはさんかいです。', reading:'わたしのへやはさんかいです。', english:'My room is on the third floor.', nepali:'मेरो कोठा तेस्रो तलामा छ।' }]},
  { id:'n5_3_18', lesson:3, level:'N5', word:'こうばん', reading:'こうばん', meaning:'Police box', meaningNepali:'प्रहरी चौकी', kanjiCharacters:['交','番'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ちかくにこうばんがあります。', reading:'ちかくにこうばんがあります。', english:'There is a police box nearby.', nepali:'नजिकै प्रहरी चौकी छ।' }]},
  { id:'n5_3_19', lesson:3, level:'N5', word:'ちかく', reading:'ちかく', meaning:'Nearby / Close to', meaningNepali:'नजिक / छेउमा', kanjiCharacters:['近'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'えきのちかくにぎんこうがあります。', reading:'えきのちかくにぎんこうがあります。', english:'There is a bank near the station.', nepali:'स्टेशनको नजिक बैंक छ।' }]},
  { id:'n5_3_20', lesson:3, level:'N5', word:'〜のなかに', reading:'〜のなかに', meaning:'Inside ~', meaningNepali:'~ भित्र', kanjiCharacters:['中'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'はこのなかになにがありますか。', reading:'はこのなかになにがありますか。', english:'What is inside the box?', nepali:'बाकसभित्र के छ?' }]},
  { id:'n5_3_21', lesson:3, level:'N5', word:'〜のうえに', reading:'〜のうえに', meaning:'On top of / Above ~', meaningNepali:'~ माथि', kanjiCharacters:['上'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'つくえのうえにほんがあります。', reading:'つくえのうえにほんがあります。', english:'There is a book on the desk.', nepali:'डेस्कको माथि किताब छ।' }]},
  { id:'n5_3_22', lesson:3, level:'N5', word:'〜のしたに', reading:'〜のしたに', meaning:'Under / Below ~', meaningNepali:'~ मुनि / तल', kanjiCharacters:['下'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'いすのしたにねこがいます。', reading:'いすのしたにねこがいます。', english:'There is a cat under the chair.', nepali:'कुर्सीको मुनि बिरालो छ।' }]},
  { id:'n5_3_23', lesson:3, level:'N5', word:'〜のまえに', reading:'〜のまえに', meaning:'In front of ~', meaningNepali:'~ अगाडि', kanjiCharacters:['前'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'えきのまえにバスていがあります。', reading:'えきのまえにバスていがあります。', english:'There is a bus stop in front of the station.', nepali:'स्टेशन अगाडि बस स्टप छ।' }]},
  { id:'n5_3_24', lesson:3, level:'N5', word:'〜のうしろに', reading:'〜のうしろに', meaning:'Behind ~', meaningNepali:'~ पछाडि', kanjiCharacters:['後'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'スーパーのうしろにこうえんがあります。', reading:'スーパーのうしろにこうえんがあります。', english:'There is a park behind the supermarket.', nepali:'सुपरमार्केट पछाडि पार्क छ।' }]},
  { id:'n5_3_25', lesson:3, level:'N5', word:'〜のよこに', reading:'〜のよこに', meaning:'Next to / Beside ~', meaningNepali:'~ छेउमा', kanjiCharacters:['横'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'ぎんこうのよこにゆうびんきょくがあります。', reading:'ぎんこうのよこにゆうびんきょくがあります。', english:'There is a post office next to the bank.', nepali:'बैंकको छेउमा हुलाक घर छ।' }]},
  { id:'n5_3_26', lesson:3, level:'N5', word:'デパート', reading:'デパート', meaning:'Department store', meaningNepali:'डिपार्टमेन्ट स्टोर', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'えきのちかくにデパートがあります。', reading:'えきのちかくにデパートがあります。', english:'There is a department store near the station.', nepali:'स्टेशनको नजिक डिपार्टमेन्ट स्टोर छ।' }]},
  { id:'n5_3_27', lesson:3, level:'N5', word:'スーパー', reading:'スーパー', meaning:'Supermarket', meaningNepali:'सुपरमार्केट', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ちかくにスーパーがあります。', reading:'ちかくにスーパーがあります。', english:'There is a supermarket nearby.', nepali:'नजिकै सुपरमार्केट छ।' }]},
  { id:'n5_3_28', lesson:3, level:'N5', word:'ぎんこう', reading:'ぎんこう', meaning:'Bank', meaningNepali:'बैंक', kanjiCharacters:['銀','行'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ぎんこうはあちらです。', reading:'ぎんこうはあちらです。', english:'The bank is over there.', nepali:'बैंक त्यता छ।' }]},
  { id:'n5_3_29', lesson:3, level:'N5', word:'ゆうびんきょく', reading:'ゆうびんきょく', meaning:'Post office', meaningNepali:'हुलाक घर', kanjiCharacters:['郵','便','局'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ゆうびんきょくはどこですか。', reading:'ゆうびんきょくはどこですか。', english:'Where is the post office?', nepali:'हुलाक घर कहाँ छ?' }]},
  { id:'n5_3_30', lesson:3, level:'N5', word:'えき', reading:'えき', meaning:'Train station', meaningNepali:'रेलवे स्टेशन', kanjiCharacters:['駅'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'えきはどこですか。', reading:'えきはどこですか。', english:'Where is the station?', nepali:'स्टेशन कहाँ छ?' }]},
  { id:'n5_3_31', lesson:3, level:'N5', word:'こうえん', reading:'こうえん', meaning:'Park', meaningNepali:'पार्क', kanjiCharacters:['公','園'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こうえんのなかにこどもがいます。', reading:'こうえんのなかにこどもがいます。', english:'There are children in the park.', nepali:'पार्कभित्र बच्चाहरू छन्।' }]},
  { id:'n5_3_32', lesson:3, level:'N5', word:'じどうはんばいき', reading:'じどうはんばいき', meaning:'Vending machine', meaningNepali:'भेन्डिङ मेसिन', kanjiCharacters:['自','動','販','売','機'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'じどうはんばいきはえきのまえにあります。', reading:'じどうはんばいきはえきのまえにあります。', english:'The vending machine is in front of the station.', nepali:'भेन्डिङ मेसिन स्टेशन अगाडि छ।' }]},
  { id:'n5_3_33', lesson:3, level:'N5', word:'あります', reading:'あります', meaning:'There is (inanimate objects)', meaningNepali:'छ (निर्जीव वस्तु)', kanjiCharacters:['有'], partOfSpeech:'Verb',
    grammarSentences:[
      { japanese:'つくえのうえにほんがあります。', reading:'つくえのうえにほんがあります。', english:'There is a book on the desk.', nepali:'डेस्कको माथि किताब छ।' },
      { japanese:'ちかくにぎんこうがありますか。', reading:'ちかくにぎんこうがありますか。', english:'Is there a bank nearby?', nepali:'नजिक बैंक छ?' }
    ]},
  { id:'n5_3_34', lesson:3, level:'N5', word:'います', reading:'います', meaning:'There is (people / animals)', meaningNepali:'छ (मान्छे / जनावर)', kanjiCharacters:['居'], partOfSpeech:'Verb',
    grammarSentences:[
      { japanese:'こうえんにこどもがいます。', reading:'こうえんにこどもがいます。', english:'There are children in the park.', nepali:'पार्कमा बच्चाहरू छन्।' },
      { japanese:'いすのしたにねこがいます。', reading:'いすのしたにねこがいます。', english:'There is a cat under the chair.', nepali:'कुर्सीको मुनि बिरालो छ।' }
    ]},
  { id:'n5_3_35', lesson:3, level:'N5', word:'どうぞ', reading:'どうぞ', meaning:'Please / Here you are / Go ahead', meaningNepali:'कृपया / लिनुस् / जानुस्', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'こちらへどうぞ。', reading:'こちらへどうぞ。', english:'Please come this way.', nepali:'कृपया यताबाट आउनुस्।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 4 — Time Expressions, Numbers & Days
  // Grammar: いまなんじですか · 〜から〜まで · やすみはいつですか · 〜ようび
  // ════════════════════════════════════════════════════════
  { id:'n5_4_01', lesson:4, level:'N5', word:'いま', reading:'いま', meaning:'Now', meaningNepali:'अहिले', kanjiCharacters:['今'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'いまなんじですか。', reading:'いまなんじですか。', english:'What time is it now?', nepali:'अहिले कति बजेको छ?' }]},
  { id:'n5_4_02', lesson:4, level:'N5', word:'〜じ', reading:'〜じ', meaning:'~ o\'clock', meaningNepali:'~ बजे', kanjiCharacters:['時'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'じゅうにじにひるごはんをたべます。', reading:'じゅうにじにひるごはんをたべます。', english:'I eat lunch at 12 o\'clock.', nepali:'म १२ बजे दिउँसो खाना खान्छु।' }]},
  { id:'n5_4_03', lesson:4, level:'N5', word:'〜ふん / 〜ぷん', reading:'〜ふん/〜ぷん', meaning:'~ minutes', meaningNepali:'~ मिनेट', kanjiCharacters:['分'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'えいがはくじじゅっぷんからです。', reading:'えいがはくじじゅっぷんからです。', english:'The movie starts at 9:10.', nepali:'फिल्म ९ बजकर १० मिनेटमा सुरु हुन्छ।' }]},
  { id:'n5_4_04', lesson:4, level:'N5', word:'〜はん', reading:'〜はん', meaning:'~ half past', meaningNepali:'साढे ~', kanjiCharacters:['半'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'くじはんにおきます。', reading:'くじはんにおきます。', english:'I get up at 9:30.', nepali:'म साढे ९ बजे उठ्छु।' }]},
  { id:'n5_4_05', lesson:4, level:'N5', word:'なんじ', reading:'なんじ', meaning:'What time?', meaningNepali:'कति बजे?', kanjiCharacters:['何','時'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'かいぎはなんじですか。', reading:'かいぎはなんじですか。', english:'What time is the meeting?', nepali:'बैठक कति बजे छ?' }]},
  { id:'n5_4_06', lesson:4, level:'N5', word:'なんぷん', reading:'なんぷん', meaning:'How many minutes?', meaningNepali:'कति मिनेट?', kanjiCharacters:['何','分'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'えきまでなんぷんかかりますか。', reading:'えきまでなんぷんかかりますか。', english:'How many minutes does it take to the station?', nepali:'स्टेशनसम्म कति मिनेट लाग्छ?' }]},
  { id:'n5_4_07', lesson:4, level:'N5', word:'ごぜん', reading:'ごぜん', meaning:'A.M. / Before noon', meaningNepali:'बिहान (दिउँसो १२ बजे अगाडि)', kanjiCharacters:['午','前'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ごぜんくじにじゅぎょうがあります。', reading:'ごぜんくじにじゅぎょうがあります。', english:'There is a class at 9 a.m.', nepali:'बिहान ९ बजे कक्षा छ।' }]},
  { id:'n5_4_08', lesson:4, level:'N5', word:'ごご', reading:'ごご', meaning:'P.M. / Afternoon', meaningNepali:'दिउँसो / साँझ (१२ बजे पछि)', kanjiCharacters:['午','後'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ごごよじにしごとがおわります。', reading:'ごごよじにしごとがおわります。', english:'Work ends at 4 p.m.', nepali:'काम दिउँसो ४ बजे सकिन्छ।' }]},
  { id:'n5_4_09', lesson:4, level:'N5', word:'〜から', reading:'〜から', meaning:'From ~ (starting point)', meaningNepali:'~ देखि', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'くじからしごとがはじまります。', reading:'くじからしごとがはじまります。', english:'Work starts from 9 o\'clock.', nepali:'काम ९ बजेदेखि सुरु हुन्छ।' }]},
  { id:'n5_4_10', lesson:4, level:'N5', word:'〜まで', reading:'〜まで', meaning:'Until ~ / Up to ~', meaningNepali:'~ सम्म', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'ごじまでしごとをします。', reading:'ごじまでしごとをします。', english:'I work until 5 o\'clock.', nepali:'म ५ बजेसम्म काम गर्छु।' }]},
  { id:'n5_4_11', lesson:4, level:'N5', word:'やすみ', reading:'やすみ', meaning:'Holiday / Day off / Break', meaningNepali:'बिदा / विश्राम', kanjiCharacters:['休'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きょうはやすみです。', reading:'きょうはやすみです。', english:'Today is a holiday.', nepali:'आज बिदा छ।' }]},
  { id:'n5_4_12', lesson:4, level:'N5', word:'ひるやすみ', reading:'ひるやすみ', meaning:'Lunch break', meaningNepali:'दिउँसो आराम', kanjiCharacters:['昼','休'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ひるやすみはじゅうにじからいちじまでです。', reading:'ひるやすみはじゅうにじからいちじまでです。', english:'Lunch break is from 12 to 1.', nepali:'दिउँसो आराम १२ बजेदेखि १ बजेसम्म हो।' }]},
  { id:'n5_4_13', lesson:4, level:'N5', word:'まいにち', reading:'まいにち', meaning:'Every day', meaningNepali:'हरेक दिन', kanjiCharacters:['毎','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいにちにほんごをべんきょうします。', reading:'まいにちにほんごをべんきょうします。', english:'I study Japanese every day.', nepali:'म हरेक दिन जापानी पढ्छु।' }]},
  { id:'n5_4_14', lesson:4, level:'N5', word:'まいあさ', reading:'まいあさ', meaning:'Every morning', meaningNepali:'हरेक बिहान', kanjiCharacters:['毎','朝'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいあさはやくおきます。', reading:'まいあさはやくおきます。', english:'I wake up early every morning.', nepali:'म हरेक बिहान चाँडो उठ्छु।' }]},
  { id:'n5_4_15', lesson:4, level:'N5', word:'まいばん', reading:'まいばん', meaning:'Every evening / Every night', meaningNepali:'हरेक साँझ', kanjiCharacters:['毎','晩'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいばんテレビをみます。', reading:'まいばんテレビをみます。', english:'I watch TV every evening.', nepali:'म हरेक साँझ टेलिभिजन हेर्छु।' }]},
  { id:'n5_4_16', lesson:4, level:'N5', word:'おととい', reading:'おととい', meaning:'The day before yesterday', meaningNepali:'अस्तिको दिन', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おとといはなにをしましたか。', reading:'おとといはなにをしましたか。', english:'What did you do the day before yesterday?', nepali:'अस्ति के गर्नुभयो?' }]},
  { id:'n5_4_17', lesson:4, level:'N5', word:'きのう', reading:'きのう', meaning:'Yesterday', meaningNepali:'हिजो', kanjiCharacters:['昨','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きのうえいがをみました。', reading:'きのうえいがをみました。', english:'I watched a movie yesterday.', nepali:'मैले हिजो फिल्म हेरें।' }]},
  { id:'n5_4_18', lesson:4, level:'N5', word:'きょう', reading:'きょう', meaning:'Today', meaningNepali:'आज', kanjiCharacters:['今','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きょうはなんようびですか。', reading:'きょうはなんようびですか。', english:'What day of the week is today?', nepali:'आज हप्ताको कुन दिन हो?' }]},
  { id:'n5_4_19', lesson:4, level:'N5', word:'あした', reading:'あした', meaning:'Tomorrow', meaningNepali:'भोलि', kanjiCharacters:['明','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あしたしけんがあります。', reading:'あしたしけんがあります。', english:'There is an exam tomorrow.', nepali:'भोलि परीक्षा छ।' }]},
  { id:'n5_4_20', lesson:4, level:'N5', word:'あさって', reading:'あさって', meaning:'The day after tomorrow', meaningNepali:'पर्सि', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'あさってはやすみです。', reading:'あさってはやすみです。', english:'The day after tomorrow is a holiday.', nepali:'पर्सि बिदा छ।' }]},
  { id:'n5_4_21', lesson:4, level:'N5', word:'せんしゅう', reading:'せんしゅう', meaning:'Last week', meaningNepali:'गत हप्ता', kanjiCharacters:['先','週'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'せんしゅうどこへいきましたか。', reading:'せんしゅうどこへいきましたか。', english:'Where did you go last week?', nepali:'गत हप्ता कहाँ गयौ?' }]},
  { id:'n5_4_22', lesson:4, level:'N5', word:'こんしゅう', reading:'こんしゅう', meaning:'This week', meaningNepali:'यो हप्ता', kanjiCharacters:['今','週'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こんしゅうはいそがしいです。', reading:'こんしゅうはいそがしいです。', english:'I am busy this week.', nepali:'यो हप्ता व्यस्त छु।' }]},
  { id:'n5_4_23', lesson:4, level:'N5', word:'らいしゅう', reading:'らいしゅう', meaning:'Next week', meaningNepali:'अर्को हप्ता', kanjiCharacters:['来','週'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'らいしゅうかいぎがあります。', reading:'らいしゅうかいぎがあります。', english:'There is a meeting next week.', nepali:'अर्को हप्ता बैठक छ।' }]},
  { id:'n5_4_24', lesson:4, level:'N5', word:'せんげつ', reading:'せんげつ', meaning:'Last month', meaningNepali:'गत महिना', kanjiCharacters:['先','月'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'せんげつにほんへきました。', reading:'せんげつにほんへきました。', english:'I came to Japan last month.', nepali:'मैले गत महिना जापान आएँ।' }]},
  { id:'n5_4_25', lesson:4, level:'N5', word:'こんげつ', reading:'こんげつ', meaning:'This month', meaningNepali:'यो महिना', kanjiCharacters:['今','月'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こんげつはいそがしいです。', reading:'こんげつはいそがしいです。', english:'I am busy this month.', nepali:'यो महिना व्यस्त छु।' }]},
  { id:'n5_4_26', lesson:4, level:'N5', word:'らいげつ', reading:'らいげつ', meaning:'Next month', meaningNepali:'अर्को महिना', kanjiCharacters:['来','月'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'らいげつにほんにいきます。', reading:'らいげつにほんにいきます。', english:'I will go to Japan next month.', nepali:'म अर्को महिना जापान जान्छु।' }]},
  { id:'n5_4_27', lesson:4, level:'N5', word:'きょねん', reading:'きょねん', meaning:'Last year', meaningNepali:'गत वर्ष', kanjiCharacters:['去','年'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きょねんにほんにきました。', reading:'きょねんにほんにきました。', english:'I came to Japan last year.', nepali:'मैले गत वर्ष जापान आएँ।' }]},
  { id:'n5_4_28', lesson:4, level:'N5', word:'ことし', reading:'ことし', meaning:'This year', meaningNepali:'यो वर्ष', kanjiCharacters:['今','年'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ことしそつぎょうします。', reading:'ことしそつぎょうします。', english:'I will graduate this year.', nepali:'म यो वर्ष स्नातक गर्छु।' }]},
  { id:'n5_4_29', lesson:4, level:'N5', word:'らいねん', reading:'らいねん', meaning:'Next year', meaningNepali:'अर्को वर्ष', kanjiCharacters:['来','年'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'らいねんにほんにいきます。', reading:'らいねんにほんにいきます。', english:'I will go to Japan next year.', nepali:'म अर्को वर्ष जापान जान्छु।' }]},
  { id:'n5_4_30', lesson:4, level:'N5', word:'なんようび', reading:'なんようび', meaning:'What day of the week?', meaningNepali:'हप्ताको कुन दिन?', kanjiCharacters:['何','曜','日'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'きょうはなんようびですか。', reading:'きょうはなんようびですか。', english:'What day of the week is today?', nepali:'आज हप्ताको कुन दिन हो?' }]},
  { id:'n5_4_31', lesson:4, level:'N5', word:'にちようび', reading:'にちようび', meaning:'Sunday', meaningNepali:'आइतबार', kanjiCharacters:['日','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'にちようびにうみへいきます。', reading:'にちようびにうみへいきます。', english:'I will go to the sea on Sunday.', nepali:'म आइतबार समुद्र जान्छु।' }]},
  { id:'n5_4_32', lesson:4, level:'N5', word:'げつようび', reading:'げつようび', meaning:'Monday', meaningNepali:'सोमबार', kanjiCharacters:['月','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'げつようびにかいぎがあります。', reading:'げつようびにかいぎがあります。', english:'There is a meeting on Monday.', nepali:'सोमबार बैठक छ।' }]},
  { id:'n5_4_33', lesson:4, level:'N5', word:'かようび', reading:'かようび', meaning:'Tuesday', meaningNepali:'मंगलबार', kanjiCharacters:['火','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かようびにテニスをします。', reading:'かようびにテニスをします。', english:'I play tennis on Tuesday.', nepali:'मंगलबार टेनिस खेल्छु।' }]},
  { id:'n5_4_34', lesson:4, level:'N5', word:'すいようび', reading:'すいようび', meaning:'Wednesday', meaningNepali:'बुधबार', kanjiCharacters:['水','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'すいようびはひまです。', reading:'すいようびはひまです。', english:'I am free on Wednesday.', nepali:'बुधबार फुर्सद छ।' }]},
  { id:'n5_4_35', lesson:4, level:'N5', word:'もくようび', reading:'もくようび', meaning:'Thursday', meaningNepali:'बिहिबार', kanjiCharacters:['木','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'もくようびにえいごをならいます。', reading:'もくようびにえいごをならいます。', english:'I learn English on Thursday.', nepali:'बिहिबार अंग्रेजी सिक्छु।' }]},
  { id:'n5_4_36', lesson:4, level:'N5', word:'きんようび', reading:'きんようび', meaning:'Friday', meaningNepali:'शुक्रबार', kanjiCharacters:['金','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'きんようびはすきです。', reading:'きんようびはすきです。', english:'I like Fridays.', nepali:'म शुक्रबार मनपराउँछु।' }]},
  { id:'n5_4_37', lesson:4, level:'N5', word:'どようび', reading:'どようび', meaning:'Saturday', meaningNepali:'शनिबार', kanjiCharacters:['土','曜','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'どようびはやすみです。', reading:'どようびはやすみです。', english:'Saturday is a day off.', nepali:'शनिबार बिदा हो।' }]},
  { id:'n5_4_38', lesson:4, level:'N5', word:'なんがつ', reading:'なんがつ', meaning:'What month?', meaningNepali:'कुन महिना?', kanjiCharacters:['何','月'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'たんじょうびはなんがつですか。', reading:'たんじょうびはなんがつですか。', english:'What month is your birthday?', nepali:'तपाईंको जन्मदिन कुन महिना हो?' }]},
  { id:'n5_4_39', lesson:4, level:'N5', word:'〜がつ', reading:'〜がつ', meaning:'Month ~ (いちがつ=Jan, etc.)', meaningNepali:'~ महिना', kanjiCharacters:['月'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'わたしのたんじょうびはさんがつです。', reading:'わたしのたんじょうびはさんがつです。', english:'My birthday is in March.', nepali:'मेरो जन्मदिन मार्चमा छ।' }]},
  { id:'n5_4_40', lesson:4, level:'N5', word:'なんにち', reading:'なんにち', meaning:'What date?', meaningNepali:'कति गते?', kanjiCharacters:['何','日'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'きょうはなんにちですか。', reading:'きょうはなんにちですか。', english:'What date is today?', nepali:'आज कति गते हो?' }]},
  { id:'n5_4_41', lesson:4, level:'N5', word:'たんじょうび', reading:'たんじょうび', meaning:'Birthday', meaningNepali:'जन्मदिन', kanjiCharacters:['誕','生','日'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'おたんじょうびはいつですか。', reading:'おたんじょうびはいつですか。', english:'When is your birthday?', nepali:'तपाईंको जन्मदिन कहिले हो?' }]},
  { id:'n5_4_42', lesson:4, level:'N5', word:'いつ', reading:'いつ', meaning:'When?', meaningNepali:'कहिले?', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'しけんはいつですか。', reading:'しけんはいつですか。', english:'When is the exam?', nepali:'परीक्षा कहिले हो?' }]},
  { id:'n5_4_43', lesson:4, level:'N5', word:'でんわ', reading:'でんわ', meaning:'Telephone', meaningNepali:'टेलिफोन', kanjiCharacters:['電','話'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんわばんごうはなんですか。', reading:'でんわばんごうはなんですか。', english:'What is your telephone number?', nepali:'तपाईंको फोन नम्बर के हो?' }]},
  { id:'n5_4_44', lesson:4, level:'N5', word:'ばんごう', reading:'ばんごう', meaning:'Number', meaningNepali:'नम्बर', kanjiCharacters:['番','号'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんわばんごうをおしえてください。', reading:'でんわばんごうをおしえてください。', english:'Please tell me your phone number.', nepali:'कृपया मलाई तपाईंको फोन नम्बर बताउनुस्।' }]},
  { id:'n5_4_45', lesson:4, level:'N5', word:'なんじかん', reading:'なんじかん', meaning:'How many hours?', meaningNepali:'कति घण्टा?', kanjiCharacters:['何','時','間'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'にほんまでなんじかんかかりますか。', reading:'にほんまでなんじかんかかりますか。', english:'How many hours does it take to Japan?', nepali:'जापानसम्म कति घण्टा लाग्छ?' }]},
  { id:'n5_4_46', lesson:4, level:'N5', word:'〜じかん', reading:'〜じかん', meaning:'~ hours (duration)', meaningNepali:'~ घण्टा', kanjiCharacters:['時','間'], partOfSpeech:'Suffix',
    grammarSentences:[{ japanese:'にほんまでじゅうにじかんかかります。', reading:'にほんまでじゅうにじかんかかります。', english:'It takes 12 hours to Japan.', nepali:'जापानसम्म १२ घण्टा लाग्छ।' }]},

  // ════════════════════════════════════════════════════════
  // LESSON 5 — Verbs: Going, Coming & Returning + Destinations
  // Grammar: N へ いきます/きます/かえります · なにで · だれと · 〜ませんか · 〜ましょう
  // ════════════════════════════════════════════════════════
  { id:'n5_5_01', lesson:5, level:'N5', word:'いきます', reading:'いきます', meaning:'Go', meaningNepali:'जानु', kanjiCharacters:['行'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[
      { japanese:'にほんへいきます。', reading:'にほんへいきます。', english:'I will go to Japan.', nepali:'म जापान जान्छु।' },
      { japanese:'どこへいきますか。', reading:'どこへいきますか。', english:'Where are you going?', nepali:'तपाईं कहाँ जाँदैहुनुहुन्छ?' }
    ]},
  { id:'n5_5_02', lesson:5, level:'N5', word:'きます', reading:'きます', meaning:'Come', meaningNepali:'आउनु', kanjiCharacters:['来'], partOfSpeech:'Verb (Irregular)',
    grammarSentences:[
      { japanese:'ともだちがきます。', reading:'ともだちがきます。', english:'A friend is coming.', nepali:'साथी आउँदैछ।' },
      { japanese:'にほんからきました。', reading:'にほんからきました。', english:'I came from Japan.', nepali:'म जापानबाट आएँ।' }
    ]},
  { id:'n5_5_03', lesson:5, level:'N5', word:'かえります', reading:'かえります', meaning:'Return / Go home', meaningNepali:'फर्कनु / घर जानु', kanjiCharacters:['帰'], partOfSpeech:'Verb (Group 1)',
    grammarSentences:[
      { japanese:'うちへかえります。', reading:'うちへかえります。', english:'I will return home.', nepali:'म घर फर्कन्छु।' },
      { japanese:'なんじにかえりますか。', reading:'なんじにかえりますか。', english:'What time will you go home?', nepali:'कति बजे घर फर्कनुहुन्छ?' }
    ]},
  { id:'n5_5_04', lesson:5, level:'N5', word:'うち', reading:'うち', meaning:'House / Home', meaningNepali:'घर', kanjiCharacters:['家'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'うちはどこですか。', reading:'うちはどこですか。', english:'Where is your home?', nepali:'तपाईंको घर कहाँ छ?' }]},
  { id:'n5_5_05', lesson:5, level:'N5', word:'くに', reading:'くに', meaning:'Country / Hometown', meaningNepali:'देश / गाउँ', kanjiCharacters:['国'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'なつやすみにくにへかえります。', reading:'なつやすみにくにへかえります。', english:'I will return to my country during summer vacation.', nepali:'गर्मी बिदामा देश फर्कन्छु।' }]},
  { id:'n5_5_06', lesson:5, level:'N5', word:'がっこう', reading:'がっこう', meaning:'School', meaningNepali:'विद्यालय', kanjiCharacters:['学','校'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'まいあさがっこうへいきます。', reading:'まいあさがっこうへいきます。', english:'I go to school every morning.', nepali:'म हरेक बिहान विद्यालय जान्छु।' }]},
  { id:'n5_5_07', lesson:5, level:'N5', word:'かいしゃ', reading:'かいしゃ', meaning:'Company', meaningNepali:'कम्पनी', kanjiCharacters:['会','社'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'かいしゃはどこですか。', reading:'かいしゃはどこですか。', english:'Where is the company?', nepali:'कम्पनी कहाँ छ?' }]},
  { id:'n5_5_08', lesson:5, level:'N5', word:'〜へ', reading:'〜へ', meaning:'To ~ (direction particle)', meaningNepali:'~ तिर / ~ लाई (दिशा)', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'とうきょうへいきます。', reading:'とうきょうへいきます。', english:'I am going to Tokyo.', nepali:'म टोक्यो जाँदैछु।' }]},
  { id:'n5_5_09', lesson:5, level:'N5', word:'ひとりで', reading:'ひとりで', meaning:'Alone / By oneself', meaningNepali:'एक्लै', kanjiCharacters:['一','人'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'ひとりでえいがをみました。', reading:'ひとりでえいがをみました。', english:'I watched a movie alone.', nepali:'मैले एक्लै फिल्म हेरें।' }]},
  { id:'n5_5_10', lesson:5, level:'N5', word:'〜と', reading:'〜と', meaning:'With ~ (together with)', meaningNepali:'~सँगै', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'ともだちとえいがをみました。', reading:'ともだちとえいがをみました。', english:'I watched a movie with my friend.', nepali:'मैले साथीसँगै फिल्म हेरें।' }]},
  { id:'n5_5_11', lesson:5, level:'N5', word:'だれと', reading:'だれと', meaning:'With whom?', meaningNepali:'कसँग?', kanjiCharacters:[], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'だれといきますか。', reading:'だれといきますか。', english:'Who will you go with?', nepali:'कसँग जाने?' }]},
  { id:'n5_5_12', lesson:5, level:'N5', word:'なにで / なんで', reading:'なにで/なんで', meaning:'By what means?', meaningNepali:'कसरी / के साधनले?', kanjiCharacters:['何'], partOfSpeech:'Question',
    grammarSentences:[{ japanese:'なんでいきますか。', reading:'なんでいきますか。', english:'How will you go?', nepali:'कसरी जानुहुन्छ?' }]},
  { id:'n5_5_13', lesson:5, level:'N5', word:'〜で', reading:'〜で', meaning:'By ~ (means of transport)', meaningNepali:'~ले (साधन)', kanjiCharacters:[], partOfSpeech:'Particle',
    grammarSentences:[{ japanese:'でんしゃでいきます。', reading:'でんしゃでいきます。', english:'I will go by train.', nepali:'म ट्रेनले जान्छु।' }]},
  { id:'n5_5_14', lesson:5, level:'N5', word:'ひこうき', reading:'ひこうき', meaning:'Airplane', meaningNepali:'हवाइजहाज', kanjiCharacters:['飛','行','機'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ひこうきでにほんへいきます。', reading:'ひこうきでにほんへいきます。', english:'I will go to Japan by airplane.', nepali:'म हवाइजहाजले जापान जान्छु।' }]},
  { id:'n5_5_15', lesson:5, level:'N5', word:'ふね', reading:'ふね', meaning:'Ship / Boat', meaningNepali:'जहाज / डुंगा', kanjiCharacters:['船'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ふねでしまへいきます。', reading:'ふねでしまへいきます。', english:'I will go to the island by boat.', nepali:'म डुंगाले टापुमा जान्छु।' }]},
  { id:'n5_5_16', lesson:5, level:'N5', word:'でんしゃ', reading:'でんしゃ', meaning:'Train', meaningNepali:'ट्रेन', kanjiCharacters:['電','車'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'でんしゃでかいしゃにいきます。', reading:'でんしゃでかいしゃにいきます。', english:'I go to the company by train.', nepali:'म ट्रेनले कम्पनी जान्छु।' }]},
  { id:'n5_5_17', lesson:5, level:'N5', word:'バス', reading:'バス', meaning:'Bus', meaningNepali:'बस', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'バスでがっこうへいきます。', reading:'バスでがっこうへいきます。', english:'I go to school by bus.', nepali:'म बसले विद्यालय जान्छु।' }]},
  { id:'n5_5_18', lesson:5, level:'N5', word:'ちかてつ', reading:'ちかてつ', meaning:'Subway', meaningNepali:'सबवे / भूमिगत रेल', kanjiCharacters:['地','下','鉄'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ちかてつでえきへいきます。', reading:'ちかてつでえきへいきます。', english:'I go to the station by subway.', nepali:'म सबवेले स्टेशन जान्छु।' }]},
  { id:'n5_5_19', lesson:5, level:'N5', word:'タクシー', reading:'タクシー', meaning:'Taxi', meaningNepali:'ट्याक्सी', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'タクシーでホテルへいきました。', reading:'タクシーでホテルへいきました。', english:'I went to the hotel by taxi.', nepali:'मैले ट्याक्सीले होटल गएँ।' }]},
  { id:'n5_5_20', lesson:5, level:'N5', word:'バイク', reading:'バイク', meaning:'Motorbike', meaningNepali:'मोटरसाइकल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'バイクでがっこうへいきます。', reading:'バイクでがっこうへいきます。', english:'I go to school by motorbike.', nepali:'म मोटरसाइकलले विद्यालय जान्छु।' }]},
  { id:'n5_5_21', lesson:5, level:'N5', word:'じてんしゃ', reading:'じてんしゃ', meaning:'Bicycle', meaningNepali:'साइकल', kanjiCharacters:['自','転','車'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'じてんしゃでえきへいきます。', reading:'じてんしゃでえきへいきます。', english:'I go to the station by bicycle.', nepali:'म साइकलले स्टेशन जान्छु।' }]},
  { id:'n5_5_22', lesson:5, level:'N5', word:'あるいて', reading:'あるいて', meaning:'On foot / Walking', meaningNepali:'हिँडेर', kanjiCharacters:['歩'], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'えきまであるいていきます。', reading:'えきまであるいていきます。', english:'I walk to the station.', nepali:'म हिँडेर स्टेशन जान्छु।' }]},
  { id:'n5_5_23', lesson:5, level:'N5', word:'りょこう', reading:'りょこう', meaning:'Travel / Trip', meaningNepali:'यात्रा / भ्रमण', kanjiCharacters:['旅','行'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'なつやすみにりょこうします。', reading:'なつやすみにりょこうします。', english:'I will travel during summer vacation.', nepali:'गर्मी बिदामा यात्रा गर्छु।' }]},
  { id:'n5_5_24', lesson:5, level:'N5', word:'かいもの', reading:'かいもの', meaning:'Shopping', meaningNepali:'किनमेल', kanjiCharacters:['買','物'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'デパートへかいものにいきます。', reading:'デパートへかいものにいきます。', english:'I will go shopping at the department store.', nepali:'म किनमेल गर्न डिपार्टमेन्ट स्टोर जान्छु।' }]},
  { id:'n5_5_25', lesson:5, level:'N5', word:'しょくじ', reading:'しょくじ', meaning:'Meal / Dining', meaningNepali:'भोजन / खाना', kanjiCharacters:['食','事'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'いっしょにしょくじをしませんか。', reading:'いっしょにしょくじをしませんか。', english:'Would you like to have a meal together?', nepali:'सँगै खाना खाने हो?' }]},
  { id:'n5_5_26', lesson:5, level:'N5', word:'さんぽ', reading:'さんぽ', meaning:'Walk / Stroll', meaningNepali:'टहल / भ्रमण', kanjiCharacters:['散','歩'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'こうえんでさんぽします。', reading:'こうえんでさんぽします。', english:'I will take a walk in the park.', nepali:'म पार्कमा टहल गर्छु।' }]},
  { id:'n5_5_27', lesson:5, level:'N5', word:'いっしょに', reading:'いっしょに', meaning:'Together', meaningNepali:'सँगै', kanjiCharacters:['一','緒'], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'いっしょにいきましょう。', reading:'いっしょにいきましょう。', english:'Let\'s go together.', nepali:'सँगै जाउँ।' }]},
  { id:'n5_5_28', lesson:5, level:'N5', word:'〜ませんか', reading:'〜ませんか', meaning:'Won\'t you ~? / Shall we ~? (invitation)', meaningNepali:'~ गर्नुहुन्न? (निमन्त्रणा)', kanjiCharacters:[], partOfSpeech:'Grammar Pattern',
    grammarSentences:[{ japanese:'いっしょにたべませんか。', reading:'いっしょにたべませんか。', english:'Won\'t you eat together with me?', nepali:'मसँगै खाने हो?' }]},
  { id:'n5_5_29', lesson:5, level:'N5', word:'〜ましょう', reading:'〜ましょう', meaning:'Let\'s ~ (suggestion)', meaningNepali:'~ गरौँ (सुझाव)', kanjiCharacters:[], partOfSpeech:'Grammar Pattern',
    grammarSentences:[{ japanese:'えいがをみましょう。', reading:'えいがをみましょう。', english:'Let\'s watch a movie.', nepali:'फिल्म हेरौँ।' }]},
  { id:'n5_5_30', lesson:5, level:'N5', word:'〜ましょうか', reading:'〜ましょうか', meaning:'Shall I / Shall we ~?', meaningNepali:'~ गरौँ कि?', kanjiCharacters:[], partOfSpeech:'Grammar Pattern',
    grammarSentences:[{ japanese:'てつだいましょうか。', reading:'てつだいましょうか。', english:'Shall I help you?', nepali:'म मद्दत गरौँ?' }]},
  { id:'n5_5_31', lesson:5, level:'N5', word:'なつやすみ', reading:'なつやすみ', meaning:'Summer vacation', meaningNepali:'गर्मी बिदा', kanjiCharacters:['夏','休'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'なつやすみにどこへいきますか。', reading:'なつやすみにどこへいきますか。', english:'Where will you go during summer vacation?', nepali:'गर्मी बिदामा कहाँ जाने?' }]},
  { id:'n5_5_32', lesson:5, level:'N5', word:'ふゆやすみ', reading:'ふゆやすみ', meaning:'Winter vacation', meaningNepali:'जाडो बिदा', kanjiCharacters:['冬','休'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ふゆやすみにスキーをします。', reading:'ふゆやすみにスキーをします。', english:'I will ski during winter vacation.', nepali:'जाडो बिदामा स्की गर्छु।' }]},
  { id:'n5_5_33', lesson:5, level:'N5', word:'しゅうまつ', reading:'しゅうまつ', meaning:'Weekend', meaningNepali:'सप्ताहन्त', kanjiCharacters:['週','末'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'しゅうまつはなにをしますか。', reading:'しゅうまつはなにをしますか。', english:'What do you do on weekends?', nepali:'सप्ताहन्तमा के गर्नुहुन्छ?' }]},
  { id:'n5_5_34', lesson:5, level:'N5', word:'いい / よい', reading:'いい/よい', meaning:'Good / Fine', meaningNepali:'राम्रो / ठिक', kanjiCharacters:[], partOfSpeech:'Adjective (i)',
    grammarSentences:[{ japanese:'きょうはいいてんきですね。', reading:'きょうはいいてんきですね。', english:'Today is nice weather, isn\'t it?', nepali:'आज मौसम राम्रो छ, हैन?' }]},
  { id:'n5_5_35', lesson:5, level:'N5', word:'どうですか', reading:'どうですか', meaning:'How is it? / How about?', meaningNepali:'कस्तो छ? / के गर्ने?', kanjiCharacters:[], partOfSpeech:'Expression',
    grammarSentences:[{ japanese:'にほんのたべものはどうですか。', reading:'にほんのたべものはどうですか。', english:'How is Japanese food?', nepali:'जापानी खाना कस्तो छ?' }]},
  { id:'n5_5_36', lesson:5, level:'N5', word:'ぜひ', reading:'ぜひ', meaning:'By all means / Definitely', meaningNepali:'अवश्य / निश्चित रूपमा', kanjiCharacters:['是','非'], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'ぜひきてください。', reading:'ぜひきてください。', english:'Please come by all means.', nepali:'अवश्य आउनुस्।' }]},
  { id:'n5_5_37', lesson:5, level:'N5', word:'もちろん', reading:'もちろん', meaning:'Of course', meaningNepali:'अवश्य / पक्कै', kanjiCharacters:[], partOfSpeech:'Adverb',
    grammarSentences:[{ japanese:'もちろんいきます。', reading:'もちろんいきます。', english:'Of course I will go.', nepali:'पक्कै जान्छु।' }]},
  { id:'n5_5_38', lesson:5, level:'N5', word:'ホテル', reading:'ホテル', meaning:'Hotel', meaningNepali:'होटल', kanjiCharacters:[], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'ホテルへかえります。', reading:'ホテルへかえります。', english:'I will return to the hotel.', nepali:'म होटल फर्कन्छु।' }]},
  { id:'n5_5_39', lesson:5, level:'N5', word:'とうきょう', reading:'とうきょう', meaning:'Tokyo', meaningNepali:'टोक्यो', kanjiCharacters:['東','京'], partOfSpeech:'Noun',
    grammarSentences:[{ japanese:'とうきょうへいきます。', reading:'とうきょうへいきます。', english:'I will go to Tokyo.', nepali:'म टोक्यो जान्छु।' }]},
];
