import json

# ============================================================
# LESSONS 11 - 15 VOCABULARY
# ============================================================
l11_data = [
    { "id": "n5_11_01", "lesson": 11, "level": "N5", "word": "１つ", "reading": "ひとつ", "meaning": "One (general counter)", "meaningNepali": "एउटा", "kanjiCharacters": ["一"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "りんごを１つください。", "reading": "りんごをひとつください。", "english": "Please give me one apple.", "nepali": "कृपया मलाई एउटा स्याउ दिनुहोस्।" }] },
    { "id": "n5_11_02", "lesson": 11, "level": "N5", "word": "２つ", "reading": "ふたつ", "meaning": "Two (general counter)", "meaningNepali": "दुइटा", "kanjiCharacters": ["二"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "みかんを２つたべました。", "reading": "みかんをふたつたべました。", "english": "I ate two mandarin oranges.", "nepali": "मैले दुइटा सुन्तला खाएँ।" }] },
    { "id": "n5_11_03", "lesson": 11, "level": "N5", "word": "３つ", "reading": "みっつ", "meaning": "Three (general counter)", "meaningNepali": "तीनटा", "kanjiCharacters": ["三"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "たまごを３つかいました。", "reading": "たまごをみっつかいました。", "english": "I bought three eggs.", "nepali": "मैले तीनटा अण्डा किनें।" }] },
    { "id": "n5_11_04", "lesson": 11, "level": "N5", "word": "４つ", "reading": "よっつ", "meaning": "Four (general counter)", "meaningNepali": "चारवटा", "kanjiCharacters": ["四"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "いすを４つならべます。", "reading": "いすをよっつならべます。", "english": "I arrange four chairs.", "nepali": "म चारवटा कुर्सी मिलाउँछु।" }] },
    { "id": "n5_11_05", "lesson": 11, "level": "N5", "word": "５つ", "reading": "いつつ", "meaning": "Five (general counter)", "meaningNepali": "पाँचवटा", "kanjiCharacters": ["五"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "パンを５つかいました。", "reading": "パンをいつつかいました。", "english": "I bought five pieces of bread.", "nepali": "मैले पाँचवटा पाउरोटी किनें।" }] },
    { "id": "n5_11_06", "lesson": 11, "level": "N5", "word": "６つ", "reading": "むっつ", "meaning": "Six (general counter)", "meaningNepali": "छवटा", "kanjiCharacters": ["六"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "はこが６つあります。", "reading": "はこがむっつあります。", "english": "There are six boxes.", "nepali": "छवटा बाकसहरू छन्।" }] },
    { "id": "n5_11_07", "lesson": 11, "level": "N5", "word": "７つ", "reading": "ななつ", "meaning": "Seven (general counter)", "meaningNepali": "सातवटा", "kanjiCharacters": ["七"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "チョコレートを７つあげました。", "reading": "チョコレートをななつあげました。", "english": "I gave seven chocolates.", "nepali": "मैले सातवटा चकलेट दिएँ।" }] },
    { "id": "n5_11_08", "lesson": 11, "level": "N5", "word": "８つ", "reading": "やっつ", "meaning": "Eight (general counter)", "meaningNepali": "आठवटा", "kanjiCharacters": ["八"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "ケーキを８つかいました。", "reading": "ケーキをやっつかいました。", "english": "I bought eight cakes.", "nepali": "मैले आठवटा केक किनें।" }] },
    { "id": "n5_11_09", "lesson": 11, "level": "N5", "word": "９つ", "reading": "ここのつ", "meaning": "Nine (general counter)", "meaningNepali": "नौवटा", "kanjiCharacters": ["九"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "お皿が９つあります。", "reading": "おさらがここのつあります。", "english": "There are nine plates.", "nepali": "नौवटा प्लेटहरू छन्।" }] },
    { "id": "n5_11_10", "lesson": 11, "level": "N5", "word": "10", "reading": "とお", "meaning": "Ten (general counter)", "meaningNepali": "दशवटा", "kanjiCharacters": ["十"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "みかんが10あります。", "reading": "みかんがとおあります。", "english": "There are ten mandarins.", "nepali": "दशवटा सुन्तलाहरू छन्।" }] },
    { "id": "n5_11_11", "lesson": 11, "level": "N5", "word": "いくつ", "reading": "いくつ", "meaning": "How many / How old", "meaningNepali": "कतिवटा / कति उमेर", "kanjiCharacters": [], "partOfSpeech": "Question",
      "grammarSentences": [{ "japanese": "みかんをいくつかいましたか。", "reading": "みかんをいくつかいましたか。", "english": "How many mandarins did you buy?", "nepali": "तपाईंले कतिवटा सुन्तला किन्नुभयो?" }] },
    { "id": "n5_11_12", "lesson": 11, "level": "N5", "word": "１人", "reading": "ひとり", "meaning": "One person", "meaningNepali": "एकजना", "kanjiCharacters": ["一", "人"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "部屋に１人います。", "reading": "へやにひとりいます。", "english": "There is one person in the room.", "nepali": "कोठामा एकजना हुनुहुन्छ।" }] },
    { "id": "n5_11_13", "lesson": 11, "level": "N5", "word": "２人", "reading": "ふたり", "meaning": "Two people", "meaningNepali": "दुईजना", "kanjiCharacters": ["二", "人"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "２人で旅行にいきます。", "reading": "ふたりでりょこうにいきます。", "english": "Two of us will go on a trip.", "nepali": "हामी दुईजना भ्रमणमा जान्छौँ।" }] },
    { "id": "n5_11_14", "lesson": 11, "level": "N5", "word": "〜人", "reading": "〜にん", "meaning": "~ people (counter)", "meaningNepali": "~ जना", "kanjiCharacters": ["人"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "教室に学生が10人います。", "reading": "きょうしつにがくせいがじゅうにんいます。", "english": "There are 10 students in the classroom.", "nepali": "कक्षाकोठामा १० जना विद्यार्थी छन्।" }] },
    { "id": "n5_11_15", "lesson": 11, "level": "N5", "word": "〜台", "reading": "〜だい", "meaning": "~ machines / vehicles counter", "meaningNepali": "~ वटा (गाडी/मेसिन)", "kanjiCharacters": ["台"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "車が２台あります。", "reading": "くるまがにだいあります。", "english": "There are two cars.", "nepali": "दुइटा कारहरू छन्।" }] },
    { "id": "n5_11_16", "lesson": 11, "level": "N5", "word": "〜枚", "reading": "〜まい", "meaning": "~ flat objects counter (paper, shirts)", "meaningNepali": "~ वटा (पाता/कागज/शर्ट)", "kanjiCharacters": ["枚"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "切手を５枚かいました。", "reading": "きってをごまいかいました。", "english": "I bought 5 stamps.", "nepali": "मैले ५ वटा टिकट किनें।" }] },
    { "id": "n5_11_17", "lesson": 11, "level": "N5", "word": "〜回", "reading": "〜かい", "meaning": "~ times (frequency)", "meaningNepali": "~ पटक", "kanjiCharacters": ["回"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "一か月に３回映画をみます。", "reading": "いっかけてにさんかいえいがをみます。", "english": "I watch movies three times a month.", "nepali": "म महिनामा तीन पटक फिल्म हेर्छु।" }] },
    { "id": "n5_11_18", "lesson": 11, "level": "N5", "word": "りんご", "reading": "りんご", "meaning": "Apple", "meaningNepali": "स्याउ", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "赤いりんごを食べます。", "reading": "あかいりんごをたべます。", "english": "I eat a red apple.", "nepali": "म रातो स्याउ खान्छु।" }] },
    { "id": "n5_11_19", "lesson": 11, "level": "N5", "word": "みかん", "reading": "みかん", "meaning": "Mandarin orange", "meaningNepali": "सुन्तला", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "甘いみかんが好きです。", "reading": "あまいみかんがすきです。", "english": "I like sweet mandarin oranges.", "nepali": "मलाई गुलियो सुन्तला मनपर्छ।" }] },
    { "id": "n5_11_20", "lesson": 20, "level": "N5", "word": "サンドイッチ", "reading": "サンドイッチ", "meaning": "Sandwich", "meaningNepali": "स्यान्डविच", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "朝ごはんにサンドイッチを食べます。", "reading": "あさごはんにサンドイッチをたべます。", "english": "I eat a sandwich for breakfast.", "nepali": "म बिहानको खाजामा स्यान्डविच खान्छु।" }] },
    { "id": "n5_11_21", "lesson": 11, "level": "N5", "word": "カレー［ライス］", "reading": "カレー［ライス］", "meaning": "Curry [and rice]", "meaningNepali": "करी र भात", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "辛いカレーライスを食べます。", "reading": "からいカレーライスをたべます。", "english": "I eat spicy curry rice.", "nepali": "म पिरो करी भात खान्छु।" }] },
    { "id": "n5_11_22", "lesson": 11, "level": "N5", "word": "アイスクリーム", "reading": "アイスクリーム", "meaning": "Ice cream", "meaningNepali": "आइसक्रिम", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "暑い日にアイスクリームを食べます。", "reading": "あついひにアイスクリームをたべます。", "english": "I eat ice cream on a hot day.", "nepali": "म गर्मीको दिनमा आइसक्रिम खान्छु।" }] },
    { "id": "n5_11_23", "lesson": 11, "level": "N5", "word": "切手", "reading": "きって", "meaning": "Postage stamp", "meaningNepali": "डाक टिकट", "kanjiCharacters": ["切", "手"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "はがきに切手をはります。", "reading": "はがきにきってをはります。", "english": "I put a stamp on the postcard.", "nepali": "म पोष्टकार्डमा टिकट टाँस्छु।" }] },
    { "id": "n5_11_24", "lesson": 11, "level": "N5", "word": "はがき", "reading": "はがき", "meaning": "Postcard", "meaningNepali": "पोष्टकार्ड", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "友達にはがきをおくります。", "reading": "ともだちにはがきをおくります。", "english": "I send a postcard to a friend.", "nepali": "म साथीलाई पोष्टकार्ड पठाउँछु।" }] },
    { "id": "n5_11_25", "lesson": 11, "level": "N5", "word": "封筒", "reading": "ふうとう", "meaning": "Envelope", "meaningNepali": "खाम / लफाफा", "kanjiCharacters": ["封", "筒"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "封筒に手紙を入れます。", "reading": "ふうとうにてがみをいれます。", "english": "I put the letter in an envelope.", "nepali": "म खाममा पत्र हाल्छु।" }] },
    { "id": "n5_11_26", "lesson": 11, "level": "N5", "word": "速達", "reading": "そくたつ", "meaning": "Special delivery / Express mail", "meaningNepali": "द्रुत हुलाक", "kanjiCharacters": ["速", "達"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "速達で送ります。", "reading": "そくたつでおくります。", "english": "I send it by express mail.", "nepali": "म द्रुत हुलाकबाट पठाउँछु।" }] },
    { "id": "n5_11_27", "lesson": 11, "level": "N5", "word": "書留", "reading": "かきとめ", "meaning": "Registered mail", "meaningNepali": "रजिस्टर्ड हुलाक", "kanjiCharacters": ["書", "留"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "書留で送ってください。", "reading": "かきとめでおくってください。", "english": "Please send it by registered mail.", "nepali": "कृपया रजिस्टर्ड हुलाकबाट पठाउनुहोस्।" }] },
    { "id": "n5_11_28", "lesson": 11, "level": "N5", "word": "エアメール", "reading": "エアメール", "meaning": "Airmail", "meaningNepali": "हवाई हुलाक", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "エアメールで外国へ送ります。", "reading": "エアメールでがいこくへおくります。", "english": "I send it abroad by airmail.", "nepali": "म हवाई हुलाकद्वारा विदेश पठाउँछु।" }] },
    { "id": "n5_11_29", "lesson": 11, "level": "N5", "word": "船便", "reading": "ふなびん", "meaning": "Sea mail / Surface mail", "meaningNepali": "समुद्री हुलाक", "kanjiCharacters": ["船", "便"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "船便は時間がかかります。", "reading": "ふなびんはじかんがかかります。", "english": "Sea mail takes time.", "nepali": "समुद्री हुलाकबाट पठाउँदा समय लाग्छ।" }] },
    { "id": "n5_11_30", "lesson": 11, "level": "N5", "word": "両親", "reading": "りょうしん", "meaning": "Parents", "meaningNepali": "अभिभावक / आमाबुबा", "kanjiCharacters": ["両", "親"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "国に両親がいます。", "reading": "くににりょうしんがいます。", "english": "My parents are in my home country.", "nepali": "मेरो देशमा आमाबुबा हुनुहुन्छ।" }] },
    { "id": "n5_11_31", "lesson": 11, "level": "N5", "word": "兄弟", "reading": "きょうだい", "meaning": "Brothers and sisters / Siblings", "meaningNepali": "दाजुभाइ तथा दिदीबहिनी", "kanjiCharacters": ["兄", "弟"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "兄弟は３人います。", "reading": "きょうだいはさんにんいます。", "english": "I have three siblings.", "nepali": "मेरो ३ जना दाजुभाइ तथा दिदीबहिनी हुनुहुन्छ।" }] },
    { "id": "n5_11_32", "lesson": 11, "level": "N5", "word": "兄", "reading": "あに", "meaning": "(my) Elder brother", "meaningNepali": "मेरो दाइ", "kanjiCharacters": ["兄"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "兄は会社員です。", "reading": "あにはかいしゃいんです。", "english": "My elder brother is a company employee.", "nepali": "मेरो दाइ कम्पनीको कर्मचारी हुनुहुन्छ।" }] },
    { "id": "n5_11_33", "lesson": 11, "level": "N5", "word": "お兄さん", "reading": "おにいさん", "meaning": "(someone's) Elder brother", "meaningNepali": "दाइ (सम्मानित)", "kanjiCharacters": ["兄"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お兄さんはお元気ですか。", "reading": "おにいさんはおげんきですか。", "english": "Is your elder brother well?", "nepali": "तपाईंको दाइ आरामै हुनुहुन्छ?" }] },
    { "id": "n5_11_34", "lesson": 11, "level": "N5", "word": "姉", "reading": "あね", "meaning": "(my) Elder sister", "meaningNepali": "मेरो दिदी", "kanjiCharacters": ["姉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "姉は看護師です。", "reading": "あねはかんごしです。", "english": "My elder sister is a nurse.", "nepali": "मेरो दिदी नर्स हुनुहुन्छ।" }] },
    { "id": "n5_11_35", "lesson": 11, "level": "N5", "word": "お姉さん", "reading": "おねえさん", "meaning": "(someone's) Elder sister", "meaningNepali": "दिदी (सम्मानित)", "kanjiCharacters": ["姉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お姉さんは何歳ですか。", "reading": "おねえさんはなんさいですか。", "english": "How old is your elder sister?", "nepali": "तपाईंको दिदी कति वर्ष हुनुभयो?" }] },
    { "id": "n5_11_36", "lesson": 11, "level": "N5", "word": "弟", "reading": "おとうと", "meaning": "(my) Younger brother", "meaningNepali": "मेरो भाइ", "kanjiCharacters": ["弟"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "弟は高校生です。", "reading": "おとうとはこうこうせいです。", "english": "My younger brother is a high school student.", "nepali": "मेरो भाइ उच्च माध्यमिक तहमा पढ्छ।" }] },
    { "id": "n5_11_37", "lesson": 11, "level": "N5", "word": "お弟さん", "reading": "おとうとさん", "meaning": "(someone's) Younger brother", "meaningNepali": "भाइ (सम्मानित)", "kanjiCharacters": ["弟"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お弟さんはお幾つですか。", "reading": "おとうとさんはおいくつですか。", "english": "How old is your younger brother?", "nepali": "तपाईंको भाइ कति वर्षको भयो?" }] },
    { "id": "n5_11_38", "lesson": 11, "level": "N5", "word": "妹", "reading": "いもうと", "meaning": "(my) Younger sister", "meaningNepali": "मेろ बहिनी", "kanjiCharacters": ["妹"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "妹は小学生です。", "reading": "いもうとはしょうがくせいです。", "english": "My younger sister is an elementary student.", "nepali": "मेरो बहिनी प्राथमिक विद्यालयमा पढ्छे।" }] },
    { "id": "n5_11_39", "lesson": 11, "level": "N5", "word": "お妹さん", "reading": "いもうとさん", "meaning": "(someone's) Younger sister", "meaningNepali": "बहिनी (सम्मानित)", "kanjiCharacters": ["妹"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お妹さんも一緒ですか。", "reading": "いもうとさんもいっしょですか。", "english": "Is your younger sister together with you?", "nepali": "तपाईंको बहिनी पनि सँगै हुनुहुन्छ?" }] },
    { "id": "n5_11_40", "lesson": 11, "level": "N5", "word": "外国", "reading": "がいこく", "meaning": "Foreign country", "meaningNepali": "विदेश", "kanjiCharacters": ["外", "国"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "外国へ行きたいです。", "reading": "がいこくへいきたいです。", "english": "I want to go abroad.", "nepali": "म विदेश जान चाहन्छु।" }] },
    { "id": "n5_11_41", "lesson": 11, "level": "N5", "word": "留学生", "reading": "りゅうがくせい", "meaning": "Foreign student", "meaningNepali": "विदेशी विद्यार्थी", "kanjiCharacters": ["留", "学", "生"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "留学生と話します。", "reading": "りゅうがくせいとはなします。", "english": "I speak with a foreign student.", "nepali": "म विदेशी विद्यार्थीसँग कुरा गर्छु।" }] },
    { "id": "n5_11_42", "lesson": 11, "level": "N5", "word": "クラス", "reading": "クラス", "meaning": "Class", "meaningNepali": "कक्षा", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "クラスに学生が20人います。", "reading": "クラスにがくせいがにじゅうにんいます。", "english": "There are 20 students in the class.", "nepali": "कक्षामा २० जना विद्यार्थी छन्।" }] },
    { "id": "n5_11_43", "lesson": 11, "level": "N5", "word": "〜時間", "reading": "〜じかん", "meaning": "~ hours", "meaningNepali": "~ घण्टा", "kanjiCharacters": ["時", "間"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "毎日８時間働きます。", "reading": "まいにちはちじかんはたらきます。", "english": "I work 8 hours every day.", "nepali": "म हरेक दिन ८ घण्टा काम गर्छु।" }] },
    { "id": "n5_11_44", "lesson": 11, "level": "N5", "word": "〜週間", "reading": "〜しゅうかん", "meaning": "~ weeks", "meaningNepali": "~ हप्ता", "kanjiCharacters": ["週", "間"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "２週間休みます。", "reading": "にしゅうかんやすみます。", "english": "I take a rest for two weeks.", "nepali": "म दुई हप्ता बिदा लिन्छु।" }] },
    { "id": "n5_11_45", "lesson": 11, "level": "N5", "word": "〜か月", "reading": "〜かけつ", "meaning": "~ months", "meaningNepali": "~ महिना", "kanjiCharacters": ["月"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "３か月日本語を勉強しました。", "reading": "さんかけつにほんごをべんきょうしました。", "english": "I studied Japanese for 3 months.", "nepali": "मैले ३ महिना जापानी भाषा पढेँ।" }] },
    { "id": "n5_11_46", "lesson": 11, "level": "N5", "word": "〜年", "reading": "〜ねん", "meaning": "~ years", "meaningNepali": "~ वर्ष", "kanjiCharacters": ["年"], "partOfSpeech": "Counter",
      "grammarSentences": [{ "japanese": "日本に１年います。", "reading": "にほんにいちねんいます。", "english": "I have been in Japan for 1 year.", "nepali": "म जापानमा १ वर्ष भयो।" }] },
    { "id": "n5_11_47", "lesson": 11, "level": "N5", "word": "〜ぐらい", "reading": "〜ぐらい", "meaning": "About ~", "meaningNepali": "लगभग ~", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "３時間ぐらいかかります。", "reading": "さんじかんぐらいかかります。", "english": "It takes about 3 hours.", "nepali": "लगभग ३ घण्टा लाग्छ।" }] },
    { "id": "n5_11_48", "lesson": 11, "level": "N5", "word": "どのくらい", "reading": "どのくらい", "meaning": "How long / How much", "meaningNepali": "कति समय / कति", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "どのくらいかかりますか。", "reading": "どのくらいかかりますか。", "english": "How long does it take?", "nepali": "कति समय लाग्छ?" }] },
    { "id": "n5_11_49", "lesson": 11, "level": "N5", "word": "全部で", "reading": "ぜんぶで", "meaning": "In total", "meaningNepali": "जम्मा गरेर", "kanjiCharacters": ["全", "部"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "全部で5000円です。", "reading": "ぜんぶでごせんえんです。", "english": "It is 5000 yen in total.", "nepali": "जम्मा गरेर ५००० येन भयो।" }] },
    { "id": "n5_11_50", "lesson": 11, "level": "N5", "word": "みんな", "reading": "みんな", "meaning": "Everyone / All", "meaningNepali": "सबै जना", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "みんなで歌いましょう。", "reading": "みんなでうたいましょう。", "english": "Let's sing together everyone.", "nepali": "सबै जना मिलेर गाऔँ।" }] },
    { "id": "n5_11_51", "lesson": 11, "level": "N5", "word": "〜だけ", "reading": "〜だけ", "meaning": "Only ~", "meaningNepali": "मात्र ~", "kanjiCharacters": [], "partOfSpeech": "Particle",
      "grammarSentences": [{ "japanese": "１枚だけ買いました。", "reading": "いちまいだけかいました。", "english": "I bought only one sheet.", "nepali": "मैले १ वटा मात्र किनेँ।" }] }
]

l12_data = [
    { "id": "n5_12_01", "lesson": 12, "level": "N5", "word": "簡単[な]", "reading": "かんたんな", "meaning": "Easy / Simple", "meaningNepali": "सजिलो / साधारण", "kanjiCharacters": ["簡", "単"], "partOfSpeech": "Na-Adjective",
      "grammarSentences": [{ "japanese": "この問題は簡単です。", "reading": "このもんだいはかんたんです。", "english": "This problem is simple.", "nepali": "यो प्रश्न सजिलो छ।" }] },
    { "id": "n5_12_02", "lesson": 12, "level": "N5", "word": "近い", "reading": "ちかい", "meaning": "Near / Close", "meaningNepali": "नजिक", "kanjiCharacters": ["近"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "家から駅まで近いです。", "reading": "うちからえきまでちかいです。", "english": "It is close from my house to the station.", "nepali": "घरबाट स्टेशन नजिक छ।" }] },
    { "id": "n5_12_03", "lesson": 12, "level": "N5", "word": "遠い", "reading": "とおい", "meaning": "Far / Distant", "meaningNepali": "टाढा", "kanjiCharacters": ["遠"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "学校は遠いです。", "reading": "がっこうはとおいです。", "english": "The school is far.", "nepali": "विद्यालय टाढा छ।" }] },
    { "id": "n5_12_04", "lesson": 12, "level": "N5", "word": "早い", "reading": "はやい", "meaning": "Fast / Early", "meaningNepali": "छिटो / चाँडो", "kanjiCharacters": ["早"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "新幹線は早いです。", "reading": "しんかんせんははやいです。", "english": "The bullet train is fast.", "nepali": "बुलेट ट्रेन छिटो छ।" }] },
    { "id": "n5_12_05", "lesson": 12, "level": "N5", "word": "遅い", "reading": "おそい", "meaning": "Slow / Late", "meaningNepali": "ढिला / सुस्त", "kanjiCharacters": ["遅"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "バスは遅いです。", "reading": "バスはおそいです。", "english": "The bus is slow.", "nepali": "बस ढिला छ।" }] },
    { "id": "n5_12_06", "lesson": 12, "level": "N5", "word": "多い", "reading": "おおい", "meaning": "Many / Much", "meaningNepali": "धेरै (मान्छेहरू)", "kanjiCharacters": ["多"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "東京は人が多いです。", "reading": "とうきょうはひとがおおいです。", "english": "There are many people in Tokyo.", "nepali": "टोक्योमा धेरै मान्छेहरू छन्।" }] },
    { "id": "n5_12_07", "lesson": 12, "level": "N5", "word": "少ない", "reading": "すくない", "meaning": "Few / Little", "meaningNepali": "थोरै / कम", "kanjiCharacters": ["少"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "今日は学生が少ないです。", "reading": "きょうはがくせいがすくないです。", "english": "There are few students today.", "nepali": "आज विद्यार्थीहरू थोरै छन्।" }] },
    { "id": "n5_12_08", "lesson": 12, "level": "N5", "word": "暖かい", "reading": "あたたかい", "meaning": "Warm", "meaningNepali": "न्यानो / तातो", "kanjiCharacters": ["暖"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "春は暖かいです。", "reading": "はるはあたたかいです。", "english": "Spring is warm.", "nepali": "वसन्त ऋतु न्यानो हुन्छ।" }] },
    { "id": "n5_12_09", "lesson": 12, "level": "N5", "word": "涼しい", "reading": "すずしい", "meaning": "Cool (weather)", "meaningNepali": "शीतल", "kanjiCharacters": ["涼"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "秋は涼しいです。", "reading": "あきはすずしいです。", "english": "Autumn is cool.", "nepali": "शरद ऋतु शीतल हुन्छ।" }] },
    { "id": "n5_12_10", "lesson": 12, "level": "N5", "word": "甘い", "reading": "あまい", "meaning": "Sweet", "meaningNepali": "गुलियो", "kanjiCharacters": ["甘"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "このケーキは甘いです。", "reading": "このケーキがあまいです。", "english": "This cake is sweet.", "nepali": "यो केक गुलियो छ।" }] },
    { "id": "n5_12_11", "lesson": 12, "level": "N5", "word": "辛い", "reading": "からい", "meaning": "Spicy / Hot", "meaningNepali": "पिरो", "kanjiCharacters": ["辛"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "カレーは辛いです。", "reading": "カレーはからいです。", "english": "The curry is spicy.", "nepali": "करी पिरो छ।" }] },
    { "id": "n5_12_12", "lesson": 12, "level": "N5", "word": "重い", "reading": "おもい", "meaning": "Heavy", "meaningNepali": "भारी / गरुङ्गो", "kanjiCharacters": ["重"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "この荷物は重いです。", "reading": "このにもつはおもいです。", "english": "This luggage is heavy.", "nepali": "यो सामान भारी छ।" }] },
    { "id": "n5_12_13", "lesson": 12, "level": "N5", "word": "軽い", "reading": "かるい", "meaning": "Light (weight)", "meaningNepali": "हल्का", "kanjiCharacters": ["軽"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "このカバンは軽いです。", "reading": "このかばんはかるいです。", "english": "This bag is light.", "nepali": "यो झोला हल्का छ।" }] },
    { "id": "n5_12_14", "lesson": 12, "level": "N5", "word": "いい", "reading": "いい", "meaning": "Preferable / Good", "meaningNepali": "राम्रो", "kanjiCharacters": [], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "コーヒーがいいです。", "reading": "コーヒーがいいです。", "english": "Coffee is fine.", "nepali": "कफी राम्रो हुन्छ।" }] },
    { "id": "n5_12_15", "lesson": 12, "level": "N5", "word": "季節", "reading": "きせつ", "meaning": "Season", "meaningNepali": "ऋतु", "kanjiCharacters": ["季", "節"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "どの季節がいちばん好きですか。", "reading": "どのきせつがいちばんすきですか。", "english": "Which season do you like best?", "nepali": "तपाईंलाई कुन ऋतु सबैभन्दा मनपर्छ?" }] },
    { "id": "n5_12_16", "lesson": 12, "level": "N5", "word": "春", "reading": "はる", "meaning": "Spring", "meaningNepali": "वसन्त ऋतु", "kanjiCharacters": ["春"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "春に花が咲きます。", "reading": "はるにはながさきます。", "english": "Flowers bloom in spring.", "nepali": "वसन्तमा फूल फुल्छ।" }] },
    { "id": "n5_12_17", "lesson": 12, "level": "N5", "word": "夏", "reading": "なつ", "meaning": "Summer", "meaningNepali": "गर्मी ऋतु", "kanjiCharacters": ["夏"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "夏は暑いです。", "reading": "なつはあついです。", "english": "Summer is hot.", "nepali": "गर्मी महिना तातो हुन्छ।" }] },
    { "id": "n5_12_18", "lesson": 12, "level": "N5", "word": "秋", "reading": "あき", "meaning": "Autumn / Fall", "meaningNepali": "शरद ऋतु", "kanjiCharacters": ["秋"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "秋は涼しいです。", "reading": "あきはすずしいです。", "english": "Autumn is cool.", "nepali": "शरद ऋतु शीतल हुन्छ।" }] },
    { "id": "n5_12_19", "lesson": 12, "level": "N5", "word": "冬", "reading": "ふゆ", "meaning": "Winter", "meaningNepali": "जाडो ऋतु", "kanjiCharacters": ["冬"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "冬に雪が降ります。", "reading": "ふゆにゆきがふります。", "english": "Snow falls in winter.", "nepali": "जाडोमा हिउँ पर्छ।" }] },
    { "id": "n5_12_20", "lesson": 12, "level": "N5", "word": "天気", "reading": "てんき", "meaning": "Weather", "meaningNepali": "मौसम", "kanjiCharacters": ["天", "気"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "今日の天気はいいです。", "reading": "きょうのてんきはいいです。", "english": "Today's weather is nice.", "nepali": "आजको मौसम राम्रो छ।" }] },
    { "id": "n5_12_21", "lesson": 12, "level": "N5", "word": "雨", "reading": "あめ", "meaning": "Rain", "meaningNepali": "पानी / वर्षा", "kanjiCharacters": ["雨"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "雨が降っています。", "reading": "あめがふっています。", "english": "It is raining.", "nepali": "पानी परिरहेको छ।" }] },
    { "id": "n5_12_22", "lesson": 12, "level": "N5", "word": "雪", "reading": "ゆき", "meaning": "Snow", "meaningNepali": "हिउँ", "kanjiCharacters": ["雪"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "雪が積もりました。", "reading": "ゆきがつもりました。", "english": "Snow has accumulated.", "nepali": "हिउँ जमेको छ।" }] },
    { "id": "n5_12_23", "lesson": 12, "level": "N5", "word": "曇り", "reading": "くもり", "meaning": "Cloudy weather", "meaningNepali": "बादल लागेको", "kanjiCharacters": ["曇"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "今日は曇りです。", "reading": "きょうはくもりです。", "english": "Today is cloudy.", "nepali": "आज बादल लागेको छ।" }] },
    { "id": "n5_12_24", "lesson": 12, "level": "N5", "word": "ホテル", "reading": "ホテル", "meaning": "Hotel", "meaningNepali": "होटल", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ホテルに泊まります。", "reading": "ホテルにとまります。", "english": "I stay at a hotel.", "nepali": "म होटलमा बास बस्छु।" }] },
    { "id": "n5_12_25", "lesson": 12, "level": "N5", "word": "空港", "reading": "くうこう", "meaning": "Airport", "meaningNepali": "विमानस्थल", "kanjiCharacters": ["空", "港"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "空港までタクシーで行きます。", "reading": "くうこうまでタクシーでいきます。", "english": "I go to the airport by taxi.", "nepali": "म ट्याक्सीमा विमानस्थल जान्छु।" }] },
    { "id": "n5_12_26", "lesson": 12, "level": "N5", "word": "海", "reading": "うみ", "meaning": "Sea / Ocean", "meaningNepali": "समुद्र", "kanjiCharacters": ["海"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "夏に海で泳ぎます。", "reading": "なつにうみでおよぎます。", "english": "I swim in the sea in summer.", "nepali": "म गर्मीमा समुद्रमा पौडी खेल्छु।" }] },
    { "id": "n5_12_27", "lesson": 12, "level": "N5", "word": "世界", "reading": "せかい", "meaning": "World", "meaningNepali": "संसार / विश्व", "kanjiCharacters": ["世", "界"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "世界旅行がしたいです。", "reading": "せかいりょこうがしたいです。", "english": "I want to travel around the world.", "nepali": "म विश्व भ्रमण गर्न चाहन्छु।" }] },
    { "id": "n5_12_28", "lesson": 12, "level": "N5", "word": "パーティー", "reading": "パーティー", "meaning": "Party", "meaningNepali": "पार्टी", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "今晩パーティーがあります。", "reading": "こんばんパーティーがあります。", "english": "There is a party tonight.", "nepali": "आज साँझ पार्टी छ।" }] },
    { "id": "n5_12_29", "lesson": 12, "level": "N5", "word": "祭り", "reading": "まつり", "meaning": "Festival", "meaningNepali": "उत्सव / चाड", "kanjiCharacters": ["祭"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "京都のお祭りは有名です。", "reading": "きょうとおまつりはゆうめいです。", "english": "Kyoto's festival is famous.", "nepali": "क्योटोको उत्सव प्रसिद्ध छ।" }] },
    { "id": "n5_12_30", "lesson": 12, "level": "N5", "word": "すき焼き", "reading": "すきやき", "meaning": "Sukiyaki", "meaningNepali": "सुकियाकी (जापानी परिकार)", "kanjiCharacters": ["焼"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "すき焼きを食べたことがあります。", "reading": "すきやきをたべたことがあります。", "english": "I have eaten sukiyaki before.", "nepali": "मैले पहिले सुकियाकी खाएको छु।" }] },
    { "id": "n5_12_31", "lesson": 12, "level": "N5", "word": "刺身", "reading": "さしみ", "meaning": "Sashimi (raw fish)", "meaningNepali": "सासिमी (काँचो माछा)", "kanjiCharacters": ["刺", "身"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "新鮮な刺身は美味しいです。", "reading": "しんせんなさしみはおいしいです。", "english": "Fresh sashimi is delicious.", "nepali": "ताजा सासिमी मीठो हुन्छ।" }] },
    { "id": "n5_12_32", "lesson": 12, "level": "N5", "word": "寿司", "reading": "すし", "meaning": "Sushi", "meaningNepali": "सुशी", "kanjiCharacters": ["寿", "司"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お寿司が好きです。", "reading": "おすしがすきです。", "english": "I like sushi.", "nepali": "मलाई सुशी मनपर्छ।" }] },
    { "id": "n5_12_33", "lesson": 12, "level": "N5", "word": "天ぷら", "reading": "てんぷら", "meaning": "Tempura", "meaningNepali": "तेम्पुरा (तारेको परिकार)", "kanjiCharacters": ["天"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "天ぷらを注文しました。", "reading": "てんぷらをちゅうもんしました。", "english": "I ordered tempura.", "nepali": "मैले तेम्पुरा अर्डर गरेँ।" }] },
    { "id": "n5_12_34", "lesson": 12, "level": "N5", "word": "豚肉", "reading": "ぶたにく", "meaning": "Pork", "meaningNepali": "सुँगुरको मासु", "kanjiCharacters": ["豚", "肉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "豚肉を食べます。", "reading": "ぶたにくをたべます。", "english": "I eat pork.", "nepali": "म सुँगुरको मासु खान्छु।" }] },
    { "id": "n5_12_35", "lesson": 12, "level": "N5", "word": "鶏肉", "reading": "とりにく", "meaning": "Chicken", "meaningNepali": "कुखुराको मासु", "kanjiCharacters": ["鶏", "肉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "鶏肉のカレーを作ります。", "reading": "とりにくのカレーをつくります。", "english": "I make chicken curry.", "nepali": "म कुखुराको मासुको करी बनाउँछु।" }] },
    { "id": "n5_12_36", "lesson": 12, "level": "N5", "word": "牛肉", "reading": "ぎゅうにく", "meaning": "Beef", "meaningNepali": "गाईको मासु", "kanjiCharacters": ["牛", "肉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "牛肉は高いです。", "reading": "ぎゅうにくはたかいです。", "english": "Beef is expensive.", "nepali": "गाईको मासु महँगो छ।" }] },
    { "id": "n5_12_37", "lesson": 12, "level": "N5", "word": "レモン", "reading": "レモン", "meaning": "Lemon", "meaningNepali": "कागती", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "レモンを絞ります。", "reading": "レモンをしぼります。", "english": "I squeeze a lemon.", "nepali": "म कागती निचोर्छु।" }] },
    { "id": "n5_12_38", "lesson": 12, "level": "N5", "word": "生け花", "reading": "いけばな", "meaning": "Flower arrangement", "meaningNepali": "फूल सजावट कला", "kanjiCharacters": ["生", "花"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "生け花を習っています。", "reading": "いけばなをならっています。", "english": "I am learning flower arrangement.", "nepali": "म फूल सजावट कला सिक्दैछु।" }] },
    { "id": "n5_12_39", "lesson": 12, "level": "N5", "word": "紅葉", "reading": "もみじ", "meaning": "Maple / Red autumn leaves", "meaningNepali": "रातो पात", "kanjiCharacters": ["紅", "葉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "山で紅葉を見ます。", "reading": "やまでもみじをみます。", "english": "I view red leaves on the mountain.", "nepali": "म पहाडमा रातो पातहरू हेर्छु।" }] },
    { "id": "n5_12_40", "lesson": 12, "level": "N5", "word": "どちら", "reading": "どちら", "meaning": "Which one (between two)", "meaningNepali": "कुन चाहिँ", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "どちらが好きですか。", "reading": "どちらがすきですか。", "english": "Which one do you like?", "nepali": "तपाईंलाई कुन चाहिँ मनपर्छ?" }] },
    { "id": "n5_12_41", "lesson": 12, "level": "N5", "word": "どちらも", "reading": "どちらも", "meaning": "Both", "meaningNepali": "दुवै", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "どちらも好きです。", "reading": "どちらもすきです。", "english": "I like both.", "nepali": "मलाई दुवै मनपर्छ।" }] },
    { "id": "n5_12_42", "lesson": 12, "level": "N5", "word": "ずっと", "reading": "ずっと", "meaning": "By far / Much more", "meaningNepali": "अझ धेरै", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "今日の方がずっと寒いです。", "reading": "きょうのほうがずっとさむいです。", "english": "Today is much colder.", "nepali": "आज अझ धेरै जाडो छ।" }] },
    { "id": "n5_12_43", "lesson": 12, "level": "N5", "word": "初めて", "reading": "はじめて", "meaning": "For the first time", "meaningNepali": "पहिलो पटक", "kanjiCharacters": ["初"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "初めて日本へ来ました。", "reading": "はじめてにほんへきました。", "english": "I came to Japan for the first time.", "nepali": "म पहिलो पटक जापान आएँ।" }] }
]

l13_data = [
    { "id": "n5_13_01", "lesson": 13, "level": "N5", "word": "遊びます", "reading": "あそびます", "meaning": "Enjoy oneself / Play", "meaningNepali": "खेल्नु / रमाइलो गर्नु", "kanjiCharacters": ["遊"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "公園で遊びます。", "reading": "こうえんであそびます。", "english": "I play in the park.", "nepali": "म पार्कमा खेल्छु।" }] },
    { "id": "n5_13_02", "lesson": 13, "level": "N5", "word": "泳ぎます", "reading": "およぎます", "meaning": "Swim", "meaningNepali": "पौडी खेल्नु", "kanjiCharacters": ["泳"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "プールで泳ぎます。", "reading": "プールでおよぎます。", "english": "I swim in the pool.", "nepali": "म स्विमिङ पुलमा पौडी खेल्छु।" }] },
    { "id": "n5_13_03", "lesson": 13, "level": "N5", "word": "迎えます", "reading": "むかえます", "meaning": "Go to meet / Welcome", "meaningNepali": "स्वागत गर्नु / लिन जानु", "kanjiCharacters": ["迎"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "空港へ友達を迎えます。", "reading": "くうこうへともだちをむかえます。", "english": "I go to the airport to meet a friend.", "nepali": "म साथीलाई लिन विमानस्थल जान्छु।" }] },
    { "id": "n5_13_04", "lesson": 13, "level": "N5", "word": "疲れます", "reading": "つかれます", "meaning": "Get tired", "meaningNepali": "थाक्नु", "kanjiCharacters": ["疲"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "仕事で疲れました。", "reading": "しごとでつかれました。", "english": "I got tired from work.", "nepali": "म कामले गर्दा थाकेँ।" }] },
    { "id": "n5_13_05", "lesson": 13, "level": "N5", "word": "結婚します", "reading": "けっこんします", "meaning": "Get married", "meaningNepali": "विवाह गर्नु", "kanjiCharacters": ["結", "婚"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "来年結婚します。", "reading": "らいねんけっこんします。", "english": "I will get married next year.", "nepali": "म अर्को वर्ष विवाह गर्छु।" }] },
    { "id": "n5_13_06", "lesson": 13, "level": "N5", "word": "買い物します", "reading": "かいものします", "meaning": "Do shopping", "meaningNepali": "किनमेल गर्नु", "kanjiCharacters": ["買", "物"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "デパートで買い物します。", "reading": "デパートであいものします。", "english": "I do shopping at the department store.", "nepali": "म डिपार्टमेन्ट स्टोरमा किनमेल गर्छु।" }] },
    { "id": "n5_13_07", "lesson": 13, "level": "N5", "word": "食事します", "reading": "しょくじします", "meaning": "Have a meal", "meaningNepali": "खाना खानु", "kanjiCharacters": ["食", "事"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "レストランで食事します。", "reading": "レストランでしょくじします。", "english": "I have a meal at a restaurant.", "nepali": "म रेस्टुरेन्टमा खाना खान्छु।" }] },
    { "id": "n5_13_08", "lesson": 13, "level": "N5", "word": "散歩します", "reading": "さんぽします", "meaning": "Take a walk", "meaningNepali": "घुम्नु / पैदल यात्रा", "kanjiCharacters": ["散", "歩"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "毎朝散歩します。", "reading": "まいあささんぽします。", "english": "I take a walk every morning.", "nepali": "म हरेक बिहान पैदल घुम्छु।" }] },
    { "id": "n5_13_09", "lesson": 13, "level": "N5", "word": "大変[な]", "reading": "たいへんな", "meaning": "Hard / Tough / Severe", "meaningNepali": "गाह्रो / कठिन", "kanjiCharacters": ["大", "変"], "partOfSpeech": "Na-Adjective",
      "grammarSentences": [{ "japanese": "毎日仕事が大変です。", "reading": "まいにちしごとがたいへんです。", "english": "Work is hard every day.", "nepali": "हरेक दिन काम गाह्रो छ।" }] },
    { "id": "n5_13_10", "lesson": 13, "level": "N5", "word": "欲しい", "reading": "ほしい", "meaning": "Want (something)", "meaningNepali": "चाहिनु / मन पर्नु", "kanjiCharacters": ["欲"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "新しい車が欲しいです。", "reading": "あたらしいくるまがほしいです。", "english": "I want a new car.", "nepali": "मलाई नयाँ कार चाहिन्छ।" }] },
    { "id": "n5_13_11", "lesson": 13, "level": "N5", "word": "広い", "reading": "ひろい", "meaning": "Wide / Spacious", "meaningNepali": "फराकिलो", "kanjiCharacters": ["広"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "この部屋は広いです。", "reading": "このへやはひろいです。", "english": "This room is spacious.", "nepali": "यो कोठा फराकिलो छ।" }] },
    { "id": "n5_13_12", "lesson": 13, "level": "N5", "word": "狭い", "reading": "せまい", "meaning": "Narrow / Small", "meaningNepali": "साँगुरो", "kanjiCharacters": ["狭"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "この道は狭いです。", "reading": "このみちはせまいです。", "english": "This road is narrow.", "nepali": "यो बाटो साँगुरो छ।" }] },
    { "id": "n5_13_13", "lesson": 13, "level": "N5", "word": "プール", "reading": "プール", "meaning": "Swimming pool", "meaningNepali": "पोखरी / स्विमिङ पुल", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "プールに行きましょう。", "reading": "プールにいきましょう。", "english": "Let's go to the pool.", "nepali": "स्विमिङ पुलमा जाऔँ।" }] },
    { "id": "n5_13_14", "lesson": 13, "level": "N5", "word": "川", "reading": "かわ", "meaning": "River", "meaningNepali": "खोला / नदी", "kanjiCharacters": ["川"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "川で魚を釣ります。", "reading": "かわでさかなをつります。", "english": "I catch fish in the river.", "nepali": "म खोलामा माछा मार्छु।" }] },
    { "id": "n5_13_15", "lesson": 13, "level": "N5", "word": "美術", "reading": "びじゅつ", "meaning": "Fine arts", "meaningNepali": "कला", "kanjiCharacters": ["美", "術"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "日本の美術を勉強します。", "reading": "にほんのびじゅつをべんきょうします。", "english": "I study Japanese fine arts.", "nepali": "म जापानी कला अध्ययन गर्छु।" }] },
    { "id": "n5_13_16", "lesson": 13, "level": "N5", "word": "釣り", "reading": "つり", "meaning": "Fishing", "meaningNepali": "माछा मार्नु", "kanjiCharacters": ["釣"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "休みの日に釣りに行きます。", "reading": "やすみのひにつりにいきます。", "english": "I go fishing on my day off.", "nepali": "म बिदाको दिन माछा मार्न जान्छु।" }] },
    { "id": "n5_13_17", "lesson": 13, "level": "N5", "word": "スキー", "reading": "スキー", "meaning": "Skiing", "meaningNepali": "स्की खेल", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "冬にスキーをします。", "reading": "ふゆにスキーをします。", "english": "I ski in winter.", "nepali": "म जाडोमा स्की खेल्छु।" }] },
    { "id": "n5_13_18", "lesson": 13, "level": "N5", "word": "週末", "reading": "しゅうまつ", "meaning": "Weekend", "meaningNepali": "हप्ताको अन्त्य / सप्ताहन्त", "kanjiCharacters": ["週", "末"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "週末何をしますか。", "reading": "しゅうまつなにをしますか。", "english": "What will you do on the weekend?", "nepali": "सप्ताहन्तमा के गर्नुहुन्छ?" }] },
    { "id": "n5_13_19", "lesson": 13, "level": "N5", "word": "お正月", "reading": "おしょうがつ", "meaning": "New Year's Day", "meaningNepali": "नयाँ वर्ष", "kanjiCharacters": ["正", "月"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お正月に国へ帰ります。", "reading": "おしょうがつにくにへかえります。", "english": "I return to my country on New Year's Day.", "nepali": "म नयाँ वर्षमा आफ्नो देश फर्किन्छु।" }] },
    { "id": "n5_13_20", "lesson": 13, "level": "N5", "word": "何か", "reading": "なにか", "meaning": "Something", "meaningNepali": "केही", "kanjiCharacters": ["何"], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "何か飲みたいてす。", "reading": "なにかのみたいです。", "english": "I want to drink something.", "nepali": "म केही पिउन चाहन्छु।" }] },
    { "id": "n5_13_21", "lesson": 13, "level": "N5", "word": "どこか", "reading": "どこか", "meaning": "Somewhere", "meaningNepali": "कहीं", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "どこかへ行きたいです。", "reading": "どこかへいきたいです。", "english": "I want to go somewhere.", "nepali": "म कहीं जान चाहन्छु।" }] },
    { "id": "n5_13_22", "lesson": 13, "level": "N5", "word": "喉が渇きます", "reading": "のどがかわきます", "meaning": "Get thirsty", "meaningNepali": "तिर्खा लाग्नु", "kanjiCharacters": ["渇"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "喉が渇きました。水をください。", "reading": "のどがかわきました。みずをください。", "english": "I got thirsty. Please give me water.", "nepali": "मलाई तिर्खा लाग्यो। कृपया पानी दिनुहोस्।" }] },
    { "id": "n5_13_23", "lesson": 13, "level": "N5", "word": "お腹が空きます", "reading": "おなかがすきます", "meaning": "Get hungry", "meaningNepali": "भोक लाग्नु", "kanjiCharacters": ["腹", "空"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "お腹が空きました。ご飯を食べましょう。", "reading": "おなかがすきました。ごはんをたべましょう。", "english": "I got hungry. Let's eat a meal.", "nepali": "मलाई भोक लाग्यो। खाना खाऔँ।" }] },
    { "id": "n5_13_24", "lesson": 13, "level": "N5", "word": "そうしましょう", "reading": "そうしましょう", "meaning": "Let's do so", "meaningNepali": "त्यसै गरौँ", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "はい、そうしましょう。", "reading": "はい、そうしましょう。", "english": "Yes, let's do so.", "nepali": "हो, त्यसै गरौँ।" }] }
]

l14_data = [
    { "id": "n5_14_01", "lesson": 14, "level": "N5", "word": "つけます", "reading": "つけます", "meaning": "Turn on (light, TV)", "meaningNepali": "बाल्नु / अन गर्नु", "kanjiCharacters": [], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "電気をつけます。", "reading": "でんきをつけます。", "english": "I turn on the light.", "nepali": "म बत्ती बाल्छु।" }] },
    { "id": "n5_14_02", "lesson": 14, "level": "N5", "word": "消します", "reading": "けします", "meaning": "Turn off / Extinguish", "meaningNepali": "निभाउनु / अफ गर्नु", "kanjiCharacters": ["消"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "エアコンを消します。", "reading": "エアコンをけします。", "english": "I turn off the air conditioner.", "nepali": "म एसी निभाउँछु।" }] },
    { "id": "n5_14_03", "lesson": 14, "level": "N5", "word": "開けます", "reading": "あけます", "meaning": "Open (door, window)", "meaningNepali": "खोल्नु", "kanjiCharacters": ["開"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "ドアを開けます。", "reading": "ドアをあけます。", "english": "I open the door.", "nepali": "म ढोका खोल्छु।" }] },
    { "id": "n5_14_04", "lesson": 14, "level": "N5", "word": "閉めます", "reading": "しめます", "meaning": "Close / Shut", "meaningNepali": "ढोका बन्द गर्नु", "kanjiCharacters": ["閉"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "窓を閉めます。", "reading": "まどをしめます。", "english": "I close the window.", "nepali": "म झ्याल बन्द गर्छु।" }] },
    { "id": "n5_14_05", "lesson": 14, "level": "N5", "word": "急ぎます", "reading": "いそぎます", "meaning": "Hurry", "meaningNepali": "हतार गर्नु", "kanjiCharacters": ["急"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "急いでください。", "reading": "いそいでください。", "english": "Please hurry.", "nepali": "कृपया हतार गर्नुहोस्।" }] },
    { "id": "n5_14_06", "lesson": 14, "level": "N5", "word": "待ちます", "reading": "まちます", "meaning": "Wait", "meaningNepali": "पर्खनु", "kanjiCharacters": ["待"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ここで待ってください。", "reading": "ここてまってください。", "english": "Please wait here.", "nepali": "कृपया यहाँ पर्खनुहोस्।" }] },
    { "id": "n5_14_07", "lesson": 14, "level": "N5", "word": "持ちます", "reading": "もちます", "meaning": "Hold / Carry", "meaningNepali": "समात्नु / बोक्नु", "kanjiCharacters": ["持"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "荷物を持ちましょうか。", "reading": "にもつをもちましょうか。", "english": "Shall I carry your luggage?", "nepali": "म तपाईंको सामान बोकिदिऊँ?" }] },
    { "id": "n5_14_08", "lesson": 14, "level": "N5", "word": "取ります", "reading": "とります", "meaning": "Take / Pass (salt)", "meaningNepali": "लिनु / टिप्नु", "kanjiCharacters": ["取"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "塩を取ってください。", "reading": "しおをとってください。", "english": "Please pass the salt.", "nepali": "कृपया नुन दिनुहोस्।" }] },
    { "id": "n5_14_09", "lesson": 14, "level": "N5", "word": "手伝います", "reading": "てつだいます", "meaning": "Help / Assist", "meaningNepali": "सहयोग गर्नु / सघाउनु", "kanjiCharacters": ["手", "伝"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "仕事を手伝います。", "reading": "しごとをつだいます。", "english": "I will help with work.", "nepali": "म काममा सघाउँछु।" }] },
    { "id": "n5_14_10", "lesson": 14, "level": "N5", "word": "呼びます", "reading": "よびます", "meaning": "Call (taxi, person)", "meaningNepali": "बोलाउनु", "kanjiCharacters": ["呼"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "タクシーを呼びます。", "reading": "タクシーをよびます。", "english": "I will call a taxi.", "nepali": "म ट्याक्सी बोलाउँछु।" }] },
    { "id": "n5_14_11", "lesson": 14, "level": "N5", "word": "話します", "reading": "はなします", "meaning": "Speak / Talk", "meaningNepali": "बोल्नु / कुरा गर्नु", "kanjiCharacters": ["話"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "日本語で話します。", "reading": "にほんごではなします。", "english": "I speak in Japanese.", "nepali": "म जापानी भाषामा बोल्छु।" }] },
    { "id": "n5_14_12", "lesson": 14, "level": "N5", "word": "使います", "reading": "つかいます", "meaning": "Use", "meaningNepali": "प्रयोग गर्नु", "kanjiCharacters": ["使"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "辞書を使います。", "reading": "じしょをつかいます。", "english": "I use a dictionary.", "nepali": "म शब्दकोश प्रयोग गर्छु।" }] },
    { "id": "n5_14_13", "lesson": 14, "level": "N5", "word": "止めます", "reading": "とめます", "meaning": "Stop / Park", "meaningNepali": "रोक्नु", "kanjiCharacters": ["止"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "ここに車を止めないでください。", "reading": "ここにくるまをとめないでください。", "english": "Please do not park the car here.", "nepali": "कृपया यहाँ गाडी नरोक्नुहोस्।" }] },
    { "id": "n5_14_14", "lesson": 14, "level": "N5", "word": "見せます", "reading": "みせます", "meaning": "Show", "meaningNepali": "देखाउनु", "kanjiCharacters": ["見"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "パスポートを見せてください。", "reading": "パスポートをみせてください。", "english": "Please show your passport.", "nepali": "कृपया पासपोर्ट देखाउनुहोस्।" }] },
    { "id": "n5_14_15", "lesson": 14, "level": "N5", "word": "教えます", "reading": "おしえます", "meaning": "Tell / Teach", "meaningNepali": "सिकाउनु / भन्नु", "kanjiCharacters": ["教"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "住所を教えてください。", "reading": "じゅうしょをおしえてください。", "english": "Please tell me your address.", "nepali": "कृपया आफ्नो ठेगाना भन्नुहोस्।" }] },
    { "id": "n5_14_16", "lesson": 14, "level": "N5", "word": "座ります", "reading": "すわります", "meaning": "Sit down", "meaningNepali": "बस्नु", "kanjiCharacters": ["座"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "椅子に座ってください。", "reading": "いすにすわってください。", "english": "Please sit on the chair.", "nepali": "कृपया कुर्सीमा बस्नुहोस्।" }] },
    { "id": "n5_14_17", "lesson": 14, "level": "N5", "word": "立ちます", "reading": "たちます", "meaning": "Stand up", "meaningNepali": "उभिनु", "kanjiCharacters": ["立"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "立ち上がってください。", "reading": "たちあがってください。", "english": "Please stand up.", "nepali": "कृपया उभिनुहोस्।" }] },
    { "id": "n5_14_18", "lesson": 14, "level": "N5", "word": "入ります", "reading": "はいります", "meaning": "Enter (coffee shop)", "meaningNepali": "छिर्नु", "kanjiCharacters": ["入"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "喫茶店に入りましょう。", "reading": "きっさてんにはいりましょう。", "english": "Let's enter the coffee shop.", "nepali": "कफी पसलमा छिरौँ।" }] },
    { "id": "n5_14_19", "lesson": 14, "level": "N5", "word": "出ます", "reading": "でます", "meaning": "Exit / Leave", "meaningNepali": "निस्कनु", "kanjiCharacters": ["出"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "部屋を出ます。", "reading": "へやをでます。", "english": "I exit the room.", "nepali": "म कोठाबाट निस्कन्छु।" }] },
    { "id": "n5_14_20", "lesson": 14, "level": "N5", "word": "雨が降ります", "reading": "あめがふります", "meaning": "Rain", "meaningNepali": "पानी पर्छ", "kanjiCharacters": ["雨", "降"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "雨が降っています。", "reading": "あめがふっています。", "english": "It is raining.", "nepali": "पानी परिरहेको छ।" }] },
    { "id": "n5_14_21", "lesson": 14, "level": "N5", "word": "コピーします", "reading": "コピーします", "meaning": "Copy", "meaningNepali": "कपी गर्नु", "kanjiCharacters": [], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "資料をコピーします。", "reading": "しりょうをコピーします。", "english": "I copy the document.", "nepali": "म कागजपत्र कपी गर्छु।" }] },
    { "id": "n5_14_22", "lesson": 14, "level": "N5", "word": "電気", "reading": "でんき", "meaning": "Electricity / Light", "meaningNepali": "बत्ती / विद्युत", "kanjiCharacters": ["電", "気"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "電気を消してください。", "reading": "でんきをけしてください。", "english": "Please turn off the light.", "nepali": "कृपया बत्ती निभाउनुहोस्।" }] },
    { "id": "n5_14_23", "lesson": 14, "level": "N5", "word": "エアコン", "reading": "エアコン", "meaning": "Air conditioner", "meaningNepali": "एयर कन्डिसनर", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "エアコンをつけます。", "reading": "エアコンをつけます。", "english": "I turn on the air conditioner.", "nepali": "म एसी अन गर्छु।" }] },
    { "id": "n5_14_24", "lesson": 14, "level": "N5", "word": "パスポート", "reading": "パスポート", "meaning": "Passport", "meaningNepali": "राहदानी / पासपोर्ट", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "パスポートを持っています。", "reading": "パスポートをもっています。", "english": "I have my passport.", "nepali": "मसँग पासपोर्ट छ।" }] },
    { "id": "n5_14_25", "lesson": 14, "level": "N5", "word": "名前", "reading": "なまえ", "meaning": "Name", "meaningNepali": "नाम", "kanjiCharacters": ["名", "前"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ここに名前を書いてください。", "reading": "ここになまえをかいてください。", "english": "Please write your name here.", "nepali": "कृपया यहाँ आफ्नो नाम लेख्नुहोस्।" }] },
    { "id": "n5_14_26", "lesson": 14, "level": "N5", "word": "住所", "reading": "じゅうしょ", "meaning": "Address", "meaningNepali": "ठेगाना", "kanjiCharacters": ["住", "所"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "住所を教えてください。", "reading": "じゅうしょをおしえてください。", "english": "Please tell me your address.", "nepali": "कृपया आफ्नो ठेगाना भन्नुहोस्।" }] },
    { "id": "n5_14_27", "lesson": 14, "level": "N5", "word": "地図", "reading": "ちず", "meaning": "Map", "meaningNepali": "नक्सा", "kanjiCharacters": ["地", "図"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "地図を見ます。", "reading": "ちずをみます。", "english": "I look at the map.", "nepali": "म नक्सा हेर्छु।" }] },
    { "id": "n5_14_28", "lesson": 14, "level": "N5", "word": "塩", "reading": "しお", "meaning": "Salt", "meaningNepali": "नुन", "kanjiCharacters": ["塩"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "塩を少しいれます。", "reading": "しおをすこしいれます。", "english": "I put in a little salt.", "nepali": "म अलि नुन हाल्छु।" }] },
    { "id": "n5_14_29", "lesson": 14, "level": "N5", "word": "砂糖", "reading": "さとう", "meaning": "Sugar", "meaningNepali": "चिनी", "kanjiCharacters": ["砂", "糖"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "コーヒーに砂糖を入れますか。", "reading": "コーヒーにさとうをいれますか。", "english": "Do you put sugar in coffee?", "nepali": "कफीमा चिनी हाल्नुहुन्छ?" }] },
    { "id": "n5_14_30", "lesson": 14, "level": "N5", "word": "問題", "reading": "もんだい", "meaning": "Problem / Question", "meaningNepali": "समस्या / प्रश्न", "kanjiCharacters": ["問", "題"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "テストの問題を解きます。", "reading": "テストのもんだいをときまし。", "english": "I solve the test problem.", "nepali": "म परीक्षाको प्रश्न हल गर्छु।" }] },
    { "id": "n5_14_31", "lesson": 14, "level": "N5", "word": "答え", "reading": "こたえ", "meaning": "Answer", "meaningNepali": "उत्तर", "kanjiCharacters": ["答"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "答えを書きます。", "reading": "こたえをかきます。", "english": "I write the answer.", "nepali": "म उत्तर लेख्छु।" }] },
    { "id": "n5_14_32", "lesson": 14, "level": "N5", "word": "読み方", "reading": "よみかた", "meaning": "Reading manner / How to read", "meaningNepali": "पढ्ने तरिका", "kanjiCharacters": ["読", "方"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "漢字の読み方を調べます。", "reading": "かんじのよみかたをしらべます。", "english": "I look up how to read kanji.", "nepali": "म काञ्जी पढ्ने तरिका खोज्छु।" }] },
    { "id": "n5_14_33", "lesson": 14, "level": "N5", "word": "まっすぐ", "reading": "まっすぐ", "meaning": "Straight ahead", "meaningNepali": "सीधा", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "まっすぐ行ってください。", "reading": "まっすぐいってください。", "english": "Please go straight ahead.", "nepali": "कृपया सीधा जानुहोस्।" }] },
    { "id": "n5_14_34", "lesson": 14, "level": "N5", "word": "ゆっくり", "reading": "ゆっくり", "meaning": "Slowly / Leisurely", "meaningNepali": "बिस्तारै", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "ゆっくり話してください。", "reading": "ゆっくりはなしてください。", "english": "Please speak slowly.", "nepali": "कृपया बिस्तारै बोल्नुहोस्।" }] },
    { "id": "n5_14_35", "lesson": 14, "level": "N5", "word": "すぐ", "reading": "すぐ", "meaning": "Immediately / Right away", "meaningNepali": "तुरन्तै", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "すぐ行きます。", "reading": "すぐいきます。", "english": "I will go right away.", "nepali": "म तुरन्तै जान्छु।" }] },
    { "id": "n5_14_36", "lesson": 14, "level": "N5", "word": "また", "reading": "また", "meaning": "Again", "meaningNepali": "फेरि", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "また明日。", "reading": "またあした。", "english": "See you again tomorrow.", "nepali": "फेरि भोलि भेटौँला।" }] },
    { "id": "n5_14_37", "lesson": 14, "level": "N5", "word": "あとで", "reading": "あとで", "meaning": "Later", "meaningNepali": "पछि", "kanjiCharacters": ["後"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "あとで電話します。", "reading": "あとででんわします。", "english": "I will call you later.", "nepali": "म पछि फोन गर्छु।" }] },
    { "id": "n5_14_38", "lesson": 14, "level": "N5", "word": "もう少し", "reading": "もうすこし", "meaning": "A little more", "meaningNepali": "अझ अलि", "kanjiCharacters": ["少"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "もう少し待ってください。", "reading": "もうすこしまってください。", "english": "Please wait a little more.", "nepali": "कृपया अझ अलि पर्खनुहोस्।" }] },
    { "id": "n5_14_39", "lesson": 14, "level": "N5", "word": "もう〜", "reading": "もう〜", "meaning": "~ more", "meaningNepali": "अझ ~", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "もう一杯いかがですか。", "reading": "もういっぱいいかがですか。", "english": "Would you like one more cup?", "nepali": "अझ एक कप लिनुहुन्छ?" }] }
]

l15_data = [
    { "id": "n5_15_01", "lesson": 15, "level": "N5", "word": "置きます", "reading": "おきます", "meaning": "Put / Place", "meaningNepali": "राख्नु", "kanjiCharacters": ["置"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "机の上に本を置きます。", "reading": "つくえのうえにほんをおきます。", "english": "I put the book on the desk.", "nepali": "म डेस्कमाथि किताब राख्छु।" }] },
    { "id": "n5_15_02", "lesson": 15, "level": "N5", "word": "作ります", "reading": "つくります", "meaning": "Make / Produce", "meaningNepali": "बनाउनु", "kanjiCharacters": ["作"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "昼ごはんを作ります。", "reading": "ひるごはんをつくります。", "english": "I make lunch.", "nepali": "म दिउँसोको खाना बनाउँछु।" }] },
    { "id": "n5_15_03", "lesson": 15, "level": "N5", "word": "売ります", "reading": "うります", "meaning": "Sell", "meaningNepali": "बेच्नु", "kanjiCharacters": ["売"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "野菜を売ります。", "reading": "やさいをうります。", "english": "I sell vegetables.", "nepali": "म तरकारी बेच्छु।" }] },
    { "id": "n5_15_04", "lesson": 15, "level": "N5", "word": "知ります", "reading": "しります", "meaning": "Know / Get to know", "meaningNepali": "थाहा पाउनु", "kanjiCharacters": ["知"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "田中さんの電話番号を知っていますか。", "reading": "たなかさんのでんわばんごうをしっていますか。", "english": "Do you know Mr. Tanaka's phone number?", "nepali": "के तपाईंलाई तानाका-जीको फोन नम्बर थाहा छ?" }] },
    { "id": "n5_15_05", "lesson": 15, "level": "N5", "word": "住みます", "reading": "すみま", "meaning": "Live / Reside", "meaningNepali": "बस्नु (बसोबास)", "kanjiCharacters": ["住"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "東京に住んでいます。", "reading": "とうきょうにすんでいます。", "english": "I live in Tokyo.", "nepali": "म टोक्योमा बस्छु।" }] },
    { "id": "n5_15_06", "lesson": 15, "level": "N5", "word": "研究します", "reading": "けんきゅうします", "meaning": "Research", "meaningNepali": "अनुसन्धान गर्नु", "kanjiCharacters": ["研", "究"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "大学で経済を研究します。", "reading": "だいがくでけいざいをけんきゅうします。", "english": "I research economics at university.", "nepali": "म विश्वविद्यालयमा अर्थतन्त्र अनुसन्धान गर्छु।" }] },
    { "id": "n5_15_07", "lesson": 15, "level": "N5", "word": "資料", "reading": "しりょう", "meaning": "Materials / Data", "meaningNepali": "सामग्री / विवरण", "kanjiCharacters": ["資", "料"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "資料を集めます。", "reading": "しりょうをあつめます。", "english": "I collect research materials.", "nepali": "म सामग्रीहरू जम्मा गर्छु।" }] },
    { "id": "n5_15_08", "lesson": 15, "level": "N5", "word": "カタログ", "reading": "カタログ", "meaning": "Catalog", "meaningNepali": "क्याटलग", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "カタログを見ます。", "reading": "カタログをみます。", "english": "I look at the catalog.", "nepali": "म क्याटलग हेर्छु।" }] },
    { "id": "n5_15_09", "lesson": 15, "level": "N5", "word": "時刻表", "reading": "じこくひょう", "meaning": "Timetable", "meaningNepali": "समय तालिका", "kanjiCharacters": ["時", "刻", "表"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "電車の時刻表を調べます。", "reading": "でんしゃのじこくひょうをしらべます。", "english": "I check the train timetable.", "nepali": "म ट्रेनको समय तालिका हेर्छु।" }] },
    { "id": "n5_15_10", "lesson": 15, "level": "N5", "word": "服", "reading": "ふく", "meaning": "Clothes", "meaningNepali": "लुगा", "kanjiCharacters": ["服"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "新しい服を買いました。", "reading": "あたらしいふくをかいました。", "english": "I bought new clothes.", "nepali": "मैले नयाँ लुगा किनें।" }] },
    { "id": "n5_15_11", "lesson": 15, "level": "N5", "word": "製品", "reading": "せいひん", "meaning": "Products / Goods", "meaningNepali": "उत्पादनहरू", "kanjiCharacters": ["製", "品"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "日本の製品は品質がいいです。", "reading": "にほんのせいひんはひんしつがいいです。", "english": "Japanese products have good quality.", "nepali": "जापानी उत्पादनहरूको गुणस्तर राम्रो हुन्छ।" }] },
    { "id": "n5_15_12", "lesson": 15, "level": "N5", "word": "ソフト", "reading": "ソフト", "meaning": "Software", "meaningNepali": "सफ्टवेयर", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "パソコンのソフトを買います。", "reading": "パソコンのソフトをかいます。", "english": "I buy computer software.", "nepali": "म कम्प्युटरको सफ्टवेयर किन्छु।" }] },
    { "id": "n5_15_13", "lesson": 15, "level": "N5", "word": "電子辞書", "reading": "でんしじしょ", "meaning": "Electronic dictionary", "meaningNepali": "इलेक्ट्रोनिक शब्दकोश", "kanjiCharacters": ["電", "子", "辞", "書"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "電子辞書は便利です。", "reading": "でんしじしょはべんりです。", "english": "Electronic dictionaries are convenient.", "nepali": "इलेक्ट्रोनिक शब्दकोश सुविधाजनक हुन्छ।" }] },
    { "id": "n5_15_14", "lesson": 15, "level": "N5", "word": "経済", "reading": "けいざい", "meaning": "Economy", "meaningNepali": "अर्थतन्त्र", "kanjiCharacters": ["経", "済"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "世界の経済を勉強します。", "reading": "せかいのけいざいをべんきょうします。", "english": "I study world economics.", "nepali": "म विश्वको अर्थतन्त्र पढ्छु।" }] },
    { "id": "n5_15_15", "lesson": 15, "level": "N5", "word": "市役所", "reading": "しやくしょ", "meaning": "City hall", "meaningNepali": "नगरपालिका कार्यालय", "kanjiCharacters": ["市", "役", "所"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "市役所へ手続きに行きます。", "reading": "しやくしょへてつづきにいきます。", "english": "I go to city hall for procedures.", "nepali": "म प्रशासनिक कामको लागि नगरपालिका कार्यालय जान्छु।" }] },
    { "id": "n5_15_16", "lesson": 15, "level": "N5", "word": "高校", "reading": "こうこう", "meaning": "Senior high school", "meaningNepali": "उच्च माध्यमिक विद्यालय", "kanjiCharacters": ["高", "校"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "高校の先生です。", "reading": "こうこうのせんせいです。", "english": "I am a high school teacher.", "nepali": "म उच्च माध्यमिक विद्यालयको शिक्षक हूँ।" }] },
    { "id": "n5_15_17", "lesson": 15, "level": "N5", "word": "歯医者", "reading": "はいしゃ", "meaning": "Dentist", "meaningNepali": "दन्त चिकित्सक", "kanjiCharacters": ["歯", "医", "者"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "歯医者に行きます。", "reading": "はいしゃにいきます。", "english": "I go to the dentist.", "nepali": "म दन्त चिकित्सककहाँ जान्छु।" }] },
    { "id": "n5_15_18", "lesson": 15, "level": "N5", "word": "独身", "reading": "どくしん", "meaning": "Single / Unmarried", "meaningNepali": "अविवाहित", "kanjiCharacters": ["独", "身"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "兄はまだ独身です。", "reading": "あにはまだどくしんです。", "english": "My elder brother is still single.", "nepali": "मेरो दाइ अझै अविवाहित हुनुहुन्छ।" }] },
    { "id": "n5_15_19", "lesson": 15, "level": "N5", "word": "思い出します", "reading": "おもいだします", "meaning": "Remember / Recall", "meaningNepali": "याद गर्नु", "kanjiCharacters": ["思", "出"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "子供のころを思い出します。", "reading": "こどものころをおもいだします。", "english": "I remember my childhood.", "nepali": "म बाल्यकाल याद गर्छु।" }] },
    { "id": "n5_15_20", "lesson": 15, "level": "N5", "word": "皆さん", "reading": "みなさん", "meaning": "Everyone", "meaningNepali": "सबै जना", "kanjiCharacters": ["皆"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "皆さん、おはようございます。", "reading": "みなさん、おはようございます。", "english": "Good morning everyone.", "nepali": "सबै जनालाई शुभ प्रभात।" }] }
]

ts11_15_header = """// ============================================================
// MINNA NO NIHONGO N5 — Complete Vocabulary & Grammar
// SOURCE: Minna no Nihongo I (Translations & Grammar Notes)
// LESSONS 11–15 (Full coverage, no omissions)
// English + Nepali meanings · Grammar sentences per word
// ============================================================

import type { VocabItem } from './nihongo-vocab';

export const N5_LESSONS_11TO15: VocabItem[] = [
"""

all_11_15 = l11_data + l12_data + l13_data + l14_data + l15_data

ts11_15_body = ""
for item in all_11_15:
    ts11_15_body += "  " + json.dumps(item, ensure_ascii=False) + ",\n"

with open("lib/n5-lessons-11to15.ts", "w", encoding="utf-8") as f:
    f.write(ts11_15_header + ts11_15_body + "];\n")

print(f"Updated lib/n5-lessons-11to15.ts with {len(all_11_15)} complete entries for Lessons 11-15!")
