import json

# ============================================================
# LESSONS 16 - 20 VOCABULARY
# ============================================================
l16_data = [
    { "id": "n5_16_01", "lesson": 16, "level": "N5", "word": "乗ります", "reading": "のります", "meaning": "Ride / Get on (train)", "meaningNepali": "चढ्नु (ट्रेन)", "kanjiCharacters": ["乗"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "電車に乗ります。", "reading": "でんしゃにのります。", "english": "I get on the train.", "nepali": "म ट्रेनमा चढ्छु।" }] },
    { "id": "n5_16_02", "lesson": 16, "level": "N5", "word": "降ります", "reading": "おります", "meaning": "Get off (train)", "meaningNepali": "ओर्लिनु", "kanjiCharacters": ["降"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "東京駅で降ります。", "reading": "とうきょうえきでおります。", "english": "I get off at Tokyo station.", "nepali": "म टोक्यो स्टेशनमा ओर्लिन्छु।" }] },
    { "id": "n5_16_03", "lesson": 16, "level": "N5", "word": "乗り換えます", "reading": "のりかえます", "meaning": "Change trains", "meaningNepali": "गाडी फेर्नु", "kanjiCharacters": ["乗", "換"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "新宿で乗り換えます。", "reading": "しんじゅくでのりかえます。", "english": "I change trains at Shinjuku.", "nepali": "म शिन्जुकुमा गाडी फेर्छु।" }] },
    { "id": "n5_16_04", "lesson": 16, "level": "N5", "word": "浴びます", "reading": "あびます", "meaning": "Take a shower", "meaningNepali": "नुहाउनु (शावर)", "kanjiCharacters": ["浴"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "シャワーを浴びます。", "reading": "シャワーをあびます。", "english": "I take a shower.", "nepali": "म शावरमा नुहाउँछु।" }] },
    { "id": "n5_16_05", "lesson": 16, "level": "N5", "word": "入れます", "reading": "いれます", "meaning": "Put in / Insert", "meaningNepali": "हाल्नु", "kanjiCharacters": ["入"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "カバンに本を入れます。", "reading": "カバンにほんをいれます。", "english": "I put the book in the bag.", "nepali": "म झोलामा किताब हाल्छु।" }] },
    { "id": "n5_16_06", "lesson": 16, "level": "N5", "word": "出します", "reading": "だします", "meaning": "Take out / Withdraw", "meaningNepali": "झिक्नु / निकाल्नु", "kanjiCharacters": ["出"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ポケットから鍵を出します。", "reading": "ポケットからかぎをだします。", "english": "I take the key out of my pocket.", "nepali": "म खल्तीबाट साँचो झिक्छु।" }] },
    { "id": "n5_16_07", "lesson": 16, "level": "N5", "word": "下ろします", "reading": "おろします", "meaning": "Withdraw (money)", "meaningNepali": "पैसा झिक्नु", "kanjiCharacters": ["下"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "銀行でお金を下ろします。", "reading": "ぎんこうでおかねをおろします。", "english": "I withdraw money from the bank.", "nepali": "म बैंकबाट पैसा झिक्छु।" }] },
    { "id": "n5_16_08", "lesson": 16, "level": "N5", "word": "入ります", "reading": "はいります", "meaning": "Enter (university)", "meaningNepali": "भर्ना हुनु / प्रवेश गर्नु", "kanjiCharacters": ["入"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "大学に入ります。", "reading": "だいがくにはいります。", "english": "I enter university.", "nepali": "म विश्वविद्यालयमा भर्ना हुन्छु।" }] },
    { "id": "n5_16_09", "lesson": 16, "level": "N5", "word": "出ます", "reading": "でます", "meaning": "Graduate from", "meaningNepali": "ग्रेजुएट हुनु", "kanjiCharacters": ["出"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "今年大学を出ます。", "reading": "ことしだいがくをでます。", "english": "I graduate from university this year.", "nepali": "म यस वर्ष विश्वविद्यालयबाट ग्रेसुएट हुन्छु।" }] },
    { "id": "n5_16_10", "lesson": 16, "level": "N5", "word": "押します", "reading": "おします", "meaning": "Push / Press", "meaningNepali": "थिच्नु", "kanjiCharacters": ["押"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ボタンを押してください。", "reading": "ボタンをおしてください。", "english": "Please press the button.", "nepali": "कृपया बटन थिच्नुहोस्।" }] },
    { "id": "n5_16_11", "lesson": 16, "level": "N5", "word": "飲みます", "reading": "のみます", "meaning": "Drink (alcohol)", "meaningNepali": "पिउनु", "kanjiCharacters": ["飲"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "友達とお酒を飲みます。", "reading": "ともだちとおさけをのみます。", "english": "I drink alcohol with a friend.", "nepali": "म साथीसँग रक्सी पिउँछु।" }] },
    { "id": "n5_16_12", "lesson": 16, "level": "N5", "word": "始めます", "reading": "はじめます", "meaning": "Start / Begin", "meaningNepali": "शुरू गर्नु", "kanjiCharacters": ["始"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "会議を始めます。", "reading": "かいぎをはじめます。", "english": "I start the meeting.", "nepali": "म बैठक सुरू गर्छु।" }] },
    { "id": "n5_16_13", "lesson": 16, "level": "N5", "word": "見学します", "reading": "けんがくします", "meaning": "Tour / Visit for study", "meaningNepali": "अवलोकन गर्नु", "kanjiCharacters": ["見", "学"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "工場を見学します。", "reading": "こうじょうをけんがくします。", "english": "I visit a factory for study.", "nepali": "म कारखाना अवलोकन गर्छु।" }] },
    { "id": "n5_16_14", "lesson": 16, "level": "N5", "word": "連絡します", "reading": "れんらくします", "meaning": "Contact", "meaningNepali": "सम्पर्क गर्नु", "kanjiCharacters": ["連", "絡"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "後で連絡します。", "reading": "あとでれんらくします。", "english": "I will contact you later.", "nepali": "म पछि सम्पर्क गर्छु।" }] },
    { "id": "n5_16_15", "lesson": 16, "level": "N5", "word": "若い", "reading": "わかい", "meaning": "Young", "meaningNepali": "जवान / उमेर कम", "kanjiCharacters": ["若"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "先生は若いです。", "reading": "せんせいはわかいです。", "english": "The teacher is young.", "nepali": "शिक्षक जवान हुनुहुन्छ।" }] },
    { "id": "n5_16_16", "lesson": 16, "level": "N5", "word": "長い", "reading": "ながい", "meaning": "Long", "meaningNepali": "लामो", "kanjiCharacters": ["長"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "髪が長いです。", "reading": "かみがながいです。", "english": "Her hair is long.", "nepali": "उहाँको कपाल लामो छ।" }] },
    { "id": "n5_16_17", "lesson": 16, "level": "N5", "word": "短い", "reading": "みじかい", "meaning": "Short", "meaningNepali": "छोटो", "kanjiCharacters": ["短"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "このペンは短いです。", "reading": "このペンはみじかいです。", "english": "This pen is short.", "nepali": "यो कलम छोटो छ।" }] },
    { "id": "n5_16_18", "lesson": 16, "level": "N5", "word": "明るい", "reading": "あかるい", "meaning": "Bright / Cheerful", "meaningNepali": "उज्यालो", "kanjiCharacters": ["明"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "この部屋は明るいです。", "reading": "このへやにあかるいです。", "english": "This room is bright.", "nepali": "यो कोठा उज्यालो छ।" }] },
    { "id": "n5_16_19", "lesson": 16, "level": "N5", "word": "暗い", "reading": "くらい", "meaning": "Dark", "meaningNepali": "अध्यारो", "kanjiCharacters": ["暗"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "外は暗いです。", "reading": "そとはくらいです。", "english": "Outside is dark.", "nepali": "बाहिर अध्यारो छ।" }] },
    { "id": "n5_16_20", "lesson": 16, "level": "N5", "word": "体", "reading": "からだ", "meaning": "Body", "meaningNepali": "शरीर", "kanjiCharacters": ["体"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "体に気をつけてください。", "reading": "からだにきをつけてください。", "english": "Please take care of your body/health.", "nepali": "कृपया आफ्नो स्वास्थ्यको ख्याल राख्नुहोस्।" }] },
    { "id": "n5_16_21", "lesson": 16, "level": "N5", "word": "頭", "reading": "あたま", "meaning": "Head", "meaningNepali": "टाउको", "kanjiCharacters": ["頭"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "頭が痛いです。", "reading": "あたまがいたいです。", "english": "I have a headache.", "nepali": "मेरो टाउको दुखिरहेको छ।" }] },
    { "id": "n5_16_22", "lesson": 16, "level": "N5", "word": "髪", "reading": "かみ", "meaning": "Hair", "meaningNepali": "कपाल", "kanjiCharacters": ["髪"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "髪を切りました。", "reading": "かみをきりました。", "english": "I cut my hair.", "nepali": "मैले कपाल काटेँ।" }] },
    { "id": "n5_16_23", "lesson": 16, "level": "N5", "word": "顔", "reading": "かお", "meaning": "Face", "meaningNepali": "अनुहार", "kanjiCharacters": ["顔"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "顔を洗います。", "reading": "かおをあ洗います。", "english": "I wash my face.", "nepali": "म अनुहार धुन्छु।" }] },
    { "id": "n5_16_24", "lesson": 16, "level": "N5", "word": "目", "reading": "め", "meaning": "Eye", "meaningNepali": "आँखा", "kanjiCharacters": ["目"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "目が大きいです。", "reading": "めがおおきいです。", "english": "Her eyes are big.", "nepali": "उहाँको आँखा ठूलो छ।" }] },
    { "id": "n5_16_25", "lesson": 16, "level": "N5", "word": "耳", "reading": "みみ", "meaning": "Ear", "meaningNepali": "कान", "kanjiCharacters": ["耳"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "耳が遠いです。", "reading": "みみがとおいです。", "english": "Hard of hearing.", "nepali": "कान कम सुन्ने।" }] },
    { "id": "n5_16_26", "lesson": 16, "level": "N5", "word": "鼻", "reading": "はな", "meaning": "Nose", "meaningNepali": "नाक", "kanjiCharacters": ["鼻"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "鼻が高いです。", "reading": "はながたかいです。", "english": "Has a high-bridged nose.", "nepali": "नाक अग्लो छ।" }] },
    { "id": "n5_16_27", "lesson": 16, "level": "N5", "word": "口", "reading": "くち", "meaning": "Mouth", "meaningNepali": "मुख", "kanjiCharacters": ["口"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "口を開けてください。", "reading": "くちをあけてください。", "english": "Please open your mouth.", "nepali": "कृपया मुख खोल्नुहोस्।" }] },
    { "id": "n5_16_28", "lesson": 16, "level": "N5", "word": "歯", "reading": "は", "meaning": "Tooth", "meaningNepali": "दाँत", "kanjiCharacters": ["歯"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "毎朝歯を磨きます。", "reading": "まいあさはをみがきます。", "english": "I brush my teeth every morning.", "nepali": "म हरेक बिहान दाँत माझ्छु।" }] },
    { "id": "n5_16_29", "lesson": 16, "level": "N5", "word": "お腹", "reading": "おなか", "meaning": "Stomach", "meaningNepali": "पेट", "kanjiCharacters": ["腹"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お腹が痛いです。", "reading": "おなかがいたいです。", "english": "My stomach hurts.", "nepali": "मेरो पेट दुखिरहेको छ।" }] },
    { "id": "n5_16_30", "lesson": 16, "level": "N5", "word": "足", "reading": "あし", "meaning": "Leg / Foot", "meaningNepali": "खुट्टा", "kanjiCharacters": ["足"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "足が速いです。", "reading": "あしがはやいです。", "english": "He runs fast.", "nepali": "उहाँ छिटो कुद्नुहुन्छ।" }] },
    { "id": "n5_16_31", "lesson": 16, "level": "N5", "word": "背が高い", "reading": "せがたかい", "meaning": "Tall (height)", "meaningNepali": "अग्लो (उचाइ)", "kanjiCharacters": ["背", "高"], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "ミラーさんは背が高いです。", "reading": "ミラーさんはせがたかいです。", "english": "Mr. Miller is tall.", "nepali": "मिलर-जी अग्लो हुनुहुन्छ।" }] },
    { "id": "n5_16_32", "lesson": 16, "level": "N5", "word": "サービス", "reading": "サービス", "meaning": "Service", "meaningNepali": "सेवा", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "このホテルのサービスは素晴らしいです。", "reading": "このホテルのサービスはすばらしいです。", "english": "This hotel's service is wonderful.", "nepali": "यो होटलको सेवा उत्कृष्ट छ।" }] },
    { "id": "n5_16_33", "lesson": 16, "level": "N5", "word": "ジョギング", "reading": "ジョギング", "meaning": "Jogging", "meaningNepali": "जगिङ", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "毎朝ジョギングをします。", "reading": "まいあさジョギングをします。", "english": "I go jogging every morning.", "nepali": "म हरेक बिहान जगिङ गर्छु।" }] },
    { "id": "n5_16_34", "lesson": 16, "level": "N5", "word": "シャワー", "reading": "シャワー", "meaning": "Shower", "meaningNepali": "शावर / नुहाउने", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "シャワーを浴びてから出かけます。", "reading": "シャワーをあびてからでかけます。", "english": "I go out after taking a shower.", "nepali": "म नुहाएपछि बाहिर जान्छु।" }] },
    { "id": "n5_16_35", "lesson": 16, "level": "N5", "word": "緑", "reading": "みどり", "meaning": "Green / Greenery", "meaningNepali": "हरियाली / हरियो", "kanjiCharacters": ["緑"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "この町は緑が多いです。", "reading": "この打ちはみどりがおおいです。", "english": "This town has a lot of greenery.", "nepali": "यो शहरमा धेरै हरियाली छ।" }] },
    { "id": "n5_16_36", "lesson": 16, "level": "N5", "word": "お寺", "reading": "おてら", "meaning": "Buddhist temple", "meaningNepali": "गुम्बा / मन्दिर", "kanjiCharacters": ["寺"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "京都でお寺を見ました。", "reading": "きょうとでおてらをみました。", "english": "I visited temples in Kyoto.", "nepali": "मैले क्योटोमा गुम्बा हेरेँ।" }] },
    { "id": "n5_16_37", "lesson": 16, "level": "N5", "word": "神社", "reading": "じんじゃ", "meaning": "Shinto shrine", "meaningNepali": "शिन्तो मन्दिर", "kanjiCharacters": ["神", "社"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "神社でお参りをします。", "reading": "じんじゃでおまいりをします。", "english": "I pray at the Shinto shrine.", "nepali": "म मन्दिरमा पुजा गर्छु।" }] }
]

l17_data = [
    { "id": "n5_17_01", "lesson": 17, "level": "N5", "word": "覚えます", "reading": "おぼえます", "meaning": "Memorize / Learn", "meaningNepali": "कण्ठ गर्नु / सम्झनु", "kanjiCharacters": ["覚"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "漢字を覚えます。", "reading": "かんじをおぼえます。", "english": "I memorize kanji.", "nepali": "म काञ्जी कण्ठ गर्छु।" }] },
    { "id": "n5_17_02", "lesson": 17, "level": "N5", "word": "忘れます", "reading": "わすれます", "meaning": "Forget", "meaningNepali": "बिर्सनु", "kanjiCharacters": ["忘"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "宿題を忘れないでください。", "reading": "しゅくだいをわすれないでください。", "english": "Please do not forget your homework.", "nepali": "कृपया गृहकार्य नबिर्सनुहोस्।" }] },
    { "id": "n5_17_03", "lesson": 17, "level": "N5", "word": "なくします", "reading": "なくします", "meaning": "Lose (something)", "meaningNepali": "हराउनु", "kanjiCharacters": [], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "財布をなくしました。", "reading": "さいふをなくしました。", "english": "I lost my wallet.", "nepali": "मैले मेरो वालेट हराएँ।" }] },
    { "id": "n5_17_04", "lesson": 17, "level": "N5", "word": "払います", "reading": "はらいます", "meaning": "Pay", "meaningNepali": "तिर्नु", "kanjiCharacters": ["払"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "現金で払います。", "reading": "げんきんではらいます。", "english": "I pay in cash.", "nepali": "म नगदमा तिर्छु।" }] },
    { "id": "n5_17_05", "lesson": 17, "level": "N5", "word": "返します", "reading": "かえします", "meaning": "Return / Give back", "meaningNepali": "फर्ता गर्नु", "kanjiCharacters": ["返"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "本を返します。", "reading": "ほんをかえします。", "english": "I return the book.", "nepali": "म किताब फर्ता गर्छु।" }] },
    { "id": "n5_17_06", "lesson": 17, "level": "N5", "word": "出かけます", "reading": "でかけます", "meaning": "Go out", "meaningNepali": "बाहिर निस्कनु", "kanjiCharacters": ["出"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "休みの日に出かけます。", "reading": "やすみのひにでかけます。", "english": "I go out on my day off.", "nepali": "म बिदाको दिन बाहिर जान्छु।" }] },
    { "id": "n5_17_07", "lesson": 17, "level": "N5", "word": "脱ぎます", "reading": "ぬぎます", "meaning": "Take off (clothes, shoes)", "meaningNepali": "खोल्नु (लुगा/जुत्ता)", "kanjiCharacters": ["脱"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "靴を脱いでください。", "reading": "くつをぬいでください。", "english": "Please take off your shoes.", "nepali": "कृपया जुत्ता खोल्नुहोस्।" }] },
    { "id": "n5_17_08", "lesson": 17, "level": "N5", "word": "持って行きます", "reading": "もっていきます", "meaning": "Take (something) along", "meaningNepali": "साथमा लैजानु", "kanjiCharacters": ["持", "行"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "傘を持って行きます。", "reading": "かさをもっていきます。", "english": "I take an umbrella along.", "nepali": "म छाता साथमा लैजान्छु।" }] },
    { "id": "n5_17_09", "lesson": 17, "level": "N5", "word": "持って来ます", "reading": "もってきます", "meaning": "Bring (something) along", "meaningNepali": "साथमा ल्याउनु", "kanjiCharacters": ["持", "来"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "辞書を持って来てください。", "reading": "じしょをもんてきてください。", "english": "Please bring your dictionary.", "nepali": "कृपया शब्दकोश साथमा ल्याउनुहोस्।" }] },
    { "id": "n5_17_10", "lesson": 17, "level": "N5", "word": "心配します", "reading": "しんぱいします", "meaning": "Worry", "meaningNepali": "चिन्ता गर्नु", "kanjiCharacters": ["心", "配"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "心配しないでください。", "reading": "しんぱいしないでください。", "english": "Please do not worry.", "nepali": "कृपया चिन्ता नगर्नुहोस्।" }] },
    { "id": "n5_17_11", "lesson": 17, "level": "N5", "word": "残業します", "reading": "ざんぎょうします", "meaning": "Work overtime", "meaningNepali": "ओभरटाइम काम गर्नु", "kanjiCharacters": ["残", "業"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "今晩残業します。", "reading": "こんばんざんぎょうします。", "english": "I work overtime tonight.", "nepali": "म आज साँझ ओभरटाइम काम गर्छु।" }] },
    { "id": "n5_17_12", "lesson": 17, "level": "N5", "word": "出張します", "reading": "しゅっちょうします", "meaning": "Go on a business trip", "meaningNepali": "व्यापारिक भ्रमणमा जानु", "kanjiCharacters": ["出", "張"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "大阪へ出張します。", "reading": "おおさかへしゅっちょうします。", "english": "I go on a business trip to Osaka.", "nepali": "म ओसाकामा व्यापारिक भ्रमणमा जान्छु।" }] },
    { "id": "n5_17_13", "lesson": 17, "level": "N5", "word": "薬を飲みます", "reading": "くすりをのみます", "meaning": "Take medicine", "meaningNepali": "औषधि खानु", "kanjiCharacters": ["薬", "飲"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ご飯の後に薬を飲みます。", "reading": "ごはんのあとにくすりをのみます。", "english": "I take medicine after meals.", "nepali": "म खाना खाएपछि औषधि खान्छु।" }] },
    { "id": "n5_17_14", "lesson": 17, "level": "N5", "word": "お風呂に入ります", "reading": "おふろにはいります", "meaning": "Take a bath", "meaningNepali": "बाथटबमा नुहाउनु", "kanjiCharacters": ["風", "呂", "入"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "毎晩お風呂に入ります。", "reading": "まいばんおふろにはいります。", "english": "I take a bath every night.", "nepali": "म हरेक राति बाथटबमा नुहाउँछु।" }] },
    { "id": "n5_17_15", "lesson": 17, "level": "N5", "word": "大切[な]", "reading": "たいせつな", "meaning": "Important / Precious", "meaningNepali": "महत्त्वपूर्ण / बहुमूल्य", "kanjiCharacters": ["大", "切"], "partOfSpeech": "Na-Adjective",
      "grammarSentences": [{ "japanese": "大切な書類です。", "reading": "たいせつなしょるいです。", "english": "It is an important document.", "nepali": "यो महत्त्वपूर्ण कागजात हो।" }] },
    { "id": "n5_17_16", "lesson": 17, "level": "N5", "word": "大丈夫[な]", "reading": "だいじょうぶな", "meaning": "All right / OK", "meaningNepali": "ठिकै छ / समस्या छैन", "kanjiCharacters": ["大", "丈", "夫"], "partOfSpeech": "Na-Adjective",
      "grammarSentences": [{ "japanese": "大丈夫ですか。", "reading": "だいじょうぶですか。", "english": "Are you all right?", "nepali": "तपाईंलाई ठिकै छ?" }] },
    { "id": "n5_17_17", "lesson": 17, "level": "N5", "word": "危ない", "reading": "あぶない", "meaning": "Dangerous", "meaningNepali": "खतरनाक / जोखिमपूर्ण", "kanjiCharacters": ["危"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "ここは危ないです。", "reading": "ここはあぶないです。", "english": "Here is dangerous.", "nepali": "यहाँ खतरनाक छ।" }] },
    { "id": "n5_17_18", "lesson": 17, "level": "N5", "word": "禁煙", "reading": "きんえん", "meaning": "No smoking", "meaningNepali": "धूम्रपान निषेध", "kanjiCharacters": ["禁", "煙"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ここは禁煙です。", "reading": "ここはきんえんです。", "english": "No smoking here.", "nepali": "यहाँ धूम्रपान निषेध छ।" }] },
    { "id": "n5_17_19", "lesson": 17, "level": "N5", "word": "保険証", "reading": "ほけんしょう", "meaning": "Health insurance card", "meaningNepali": "स्वास्थ्य बीमा कार्ड", "kanjiCharacters": ["保", "険", "証"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "保険証を見せてください。", "reading": "ほけんしょうをみせてください。", "english": "Please show your health insurance card.", "nepali": "कृपया आफ्नो स्वास्थ्य बीमा कार्ड देखाउनुहोस्।" }] },
    { "id": "n5_17_20", "lesson": 17, "level": "N5", "word": "熱", "reading": "ねつ", "meaning": "Fever / Temperature", "meaningNepali": "ज्वरो", "kanjiCharacters": ["熱"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "熱があります。", "reading": "ねつがあります。", "english": "I have a fever.", "nepali": "मलाई ज्वरो आएको छ।" }] },
    { "id": "n5_17_21", "lesson": 17, "level": "N5", "word": "病気", "reading": "びょうき", "meaning": "Illness / Sickness", "meaningNepali": "बिरामी / रोग", "kanjiCharacters": ["病", "気"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "病気で休みます。", "reading": "びょうきでやすみます。", "english": "I take a rest due to illness.", "nepali": "म बिरामी भएर बिदा लिन्छु।" }] },
    { "id": "n5_17_22", "lesson": 17, "level": "N5", "word": "薬", "reading": "くすり", "meaning": "Medicine", "meaningNepali": "औषधि", "kanjiCharacters": ["薬"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "薬局で薬を買います。", "reading": "やっきょくでくすりをかいます。", "english": "I buy medicine at the pharmacy.", "nepali": "म औषधि पसलबाट औषधि किन्छु।" }] },
    { "id": "n5_17_23", "lesson": 17, "level": "N5", "word": "上着", "reading": "うわぎ", "meaning": "Jacket / Outerwear", "meaningNepali": "कोट / बाहिरी लुगा", "kanjiCharacters": ["上", "着"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "上着を着ます。", "reading": "うわぎをきます。", "english": "I put on a jacket.", "nepali": "म बाहिरी कोट लगाउँछु।" }] },
    { "id": "n5_17_24", "lesson": 17, "level": "N5", "word": "下着", "reading": "したぎ", "meaning": "Underwear", "meaningNepali": "भित्री लुगा", "kanjiCharacters": ["下", "着"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "下着を洗います。", "reading": "したぎをあ洗います。", "english": "I wash underwear.", "nepali": "म भित्री लुगा धुन्छु।" }] },
    { "id": "n5_17_25", "lesson": 17, "level": "N5", "word": "２、３日", "reading": "にさんち", "meaning": "2 or 3 days", "meaningNepali": "२-३ दिन", "kanjiCharacters": ["日"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "２、３日休んでください。", "reading": "にさんちやすんでください。", "english": "Please rest for 2 or 3 days.", "nepali": "कृपया २-३ दिन आराम गर्नुहोस्।" }] },
    { "id": "n5_17_26", "lesson": 17, "level": "N5", "word": "〜までに", "reading": "〜までに", "meaning": "By ~ / Before ~", "meaningNepali": "~ सम्ममा", "kanjiCharacters": [], "partOfSpeech": "Particle",
      "grammarSentences": [{ "japanese": "５時までに来てください。", "reading": "ごじまでにきてください。", "english": "Please come by 5 o'clock.", "nepali": "कृपया ५ बजेसम्ममा आउनुहोस्।" }] },
    { "id": "n5_17_27", "lesson": 17, "level": "N5", "word": "ですから", "reading": "ですから", "meaning": "Therefore / So", "meaningNepali": "त्यसैले", "kanjiCharacters": [], "partOfSpeech": "Conjunction",
      "grammarSentences": [{ "japanese": "雨です。ですからタクシーで行きます。", "reading": "あめです。ですからタクシーでいきます。", "english": "It is raining. So I will go by taxi.", "nepali": "पानी परिरहेको छ। त्यसैले म ट्याक्सीमा जान्छु।" }] }
]

l18_data = [
    { "id": "n5_18_01", "lesson": 18, "level": "N5", "word": "できます", "reading": "できます", "meaning": "Can do / Be able to", "meaningNepali": "गर्न सक्नु", "kanjiCharacters": [], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "日本語を話すことができます。", "reading": "にほんごをはなすことができます。", "english": "I can speak Japanese.", "nepali": "म जापानी भाषा बोल्न सक्छु।" }] },
    { "id": "n5_18_02", "lesson": 18, "level": "N5", "word": "洗います", "reading": "あ洗います", "meaning": "Wash", "meaningNepali": "धुने", "kanjiCharacters": ["洗"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "手を洗います。", "reading": "てをあ洗います。", "english": "I wash my hands.", "nepali": "म हात धुन्छु।" }] },
    { "id": "n5_18_03", "lesson": 18, "level": "N5", "word": "弾きます", "reading": "ひきます", "meaning": "Play (piano, string inst)", "meaningNepali": "बजाउनु (पियानो)", "kanjiCharacters": ["弾"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ピアノを弾きます。", "reading": "ピアノをひきます。", "english": "I play the piano.", "nepali": "म पियानो बजाउँछु।" }] },
    { "id": "n5_18_04", "lesson": 18, "level": "N5", "word": "歌います", "reading": "うたいます", "meaning": "Sing", "meaningNepali": "गाउनु", "kanjiCharacters": ["歌"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "歌を歌います。", "reading": "うたをうたいます。", "english": "I sing a song.", "nepali": "म गीत गाउँछु।" }] },
    { "id": "n5_18_05", "lesson": 18, "level": "N5", "word": "集めます", "reading": "あつめます", "meaning": "Collect / Gather", "meaningNepali": "जम्मा गर्नु", "kanjiCharacters": ["集"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "切手を集めています。", "reading": "きってをあつめています。", "english": "I am collecting stamps.", "nepali": "म टिकटहरू जम्मा गर्दैछु।" }] },
    { "id": "n5_18_06", "lesson": 18, "level": "N5", "word": "捨てます", "reading": "すてます", "meaning": "Throw away / Discard", "meaningNepali": "फाल्नु", "kanjiCharacters": ["捨"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "ゴミを捨てます。", "reading": "ゴミをすてます。", "english": "I throw away garbage.", "nepali": "म फोहर फाल्छु।" }] },
    { "id": "n5_18_07", "lesson": 18, "level": "N5", "word": "換えます", "reading": "かえます", "meaning": "Exchange / Change", "meaningNepali": "साट्नु", "kanjiCharacters": ["換"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "お金を換えます。", "reading": "おかねをかえます。", "english": "I exchange money.", "nepali": "म पैसा साट्छु।" }] },
    { "id": "n5_18_08", "lesson": 18, "level": "N5", "word": "運転します", "reading": "うんてんします", "meaning": "Drive", "meaningNepali": "गाडी चलाउनु", "kanjiCharacters": ["運", "転"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "車を運転します。", "reading": "くるまをうんてんします。", "english": "I drive a car.", "nepali": "म गाडी चलाउँछु।" }] },
    { "id": "n5_18_09", "lesson": 18, "level": "N5", "word": "予約します", "reading": "よやくします", "meaning": "Reserve / Book", "meaningNepali": "बुकिङ गर्नु", "kanjiCharacters": ["予", "約"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "ホテルを予約します。", "reading": "ホテルをよやくします。", "english": "I reserve a hotel.", "nepali": "म होटल बुकिङ गर्छु।" }] },
    { "id": "n5_18_10", "lesson": 18, "level": "N5", "word": "ピアノ", "reading": "ピアノ", "meaning": "Piano", "meaningNepali": "पियानो", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ピアノの練習をします。", "reading": "ピアノのれんしゅうをします。", "english": "I practice the piano.", "nepali": "म पियानो अभ्यास गर्छु।" }] },
    { "id": "n5_18_11", "lesson": 18, "level": "N5", "word": "メートル", "reading": "メートル", "meaning": "Meter", "meaningNepali": "मिटर", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "100メートル泳ぎます。", "reading": "ひゃくメートルおよぎます。", "english": "I swim 100 meters.", "nepali": "म १०० मिटर पौडी खेल्छु।" }] },
    { "id": "n5_18_12", "lesson": 18, "level": "N5", "word": "現金", "reading": "げんきん", "meaning": "Cash", "meaningNepali": "नगद", "kanjiCharacters": ["現", "金"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "現金で払います。", "reading": "げんきんではらいます。", "english": "I will pay with cash.", "nepali": "म नगदमा तिर्छु।" }] },
    { "id": "n5_18_13", "lesson": 18, "level": "N5", "word": "趣味", "reading": "しゅみ", "meaning": "Hobby / Interest", "meaningNepali": "रुचि / शौक", "kanjiCharacters": ["趣", "味"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "私の趣味は映画を見ることです。", "reading": "わたしのしゅみはおいがをみることです。", "english": "My hobby is watching movies.", "nepali": "मेरो रुचि फिल्म हेर्नु हो।" }] },
    { "id": "n5_18_14", "lesson": 18, "level": "N5", "word": "日記", "reading": "にっき", "meaning": "Diary / Journal", "meaningNepali": "डायरी", "kanjiCharacters": ["日", "記"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "毎晩日記を書きます。", "reading": "まいばんにっきをかきます。", "english": "I write a diary every evening.", "nepali": "म हरेक साँझ डायरी लेख्छु।" }] },
    { "id": "n5_18_15", "lesson": 18, "level": "N5", "word": "お祈り", "reading": "おいのり", "meaning": "Prayer", "meaningNepali": "प्रार्थना", "kanjiCharacters": ["祈"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "お祈りをします。", "reading": "おいのりをします。", "english": "I pray.", "nepali": "म प्रार्थना गर्छु।" }] },
    { "id": "n5_18_16", "lesson": 18, "level": "N5", "word": "課長", "reading": "かちょう", "meaning": "Section manager", "meaningNepali": "शाखा प्रमुख", "kanjiCharacters": ["課", "長"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "課長に相談します。", "reading": "かちょうにそうだんします。", "english": "I consult the section manager.", "nepali": "म शाखा प्रमुखसँग सल्लाह गर्छु।" }] },
    { "id": "n5_18_17", "lesson": 18, "level": "N5", "word": "部長", "reading": "ぶちょう", "meaning": "Department manager", "meaningNepali": "विभाग प्रमुख", "kanjiCharacters": ["部", "長"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "部長は出張中です。", "reading": "ぶちょうにしゅっちょうちゅうです。", "english": "The department manager is on a business trip.", "nepali": "विभाग प्रमुख व्यापारिक भ्रमणमा हुनुहुन्छ।" }] },
    { "id": "n5_18_18", "lesson": 18, "level": "N5", "word": "社長", "reading": "しゃちょう", "meaning": "Company president", "meaningNepali": "कम्पनी अध्यक्ष", "kanjiCharacters": ["社", "長"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "社長に挨拶します。", "reading": "しゃちょうにあいさつします。", "english": "I greet the company president.", "nepali": "म कम्पनी अध्यक्षलाई नमस्कार गर्छु।" }] },
    { "id": "n5_18_19", "lesson": 18, "level": "N5", "word": "動物", "reading": "どうぶつ", "meaning": "Animal", "meaningNepali": "जनावर", "kanjiCharacters": ["動", "物"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "動物園で動物を見ます。", "reading": "どうぶつえんでどうぶつをみます。", "english": "I see animals at the zoo.", "nepali": "म चिडियाखानामा जनावरहरू हेर्छु।" }] },
    { "id": "n5_18_20", "lesson": 18, "level": "N5", "word": "馬", "reading": "うま", "meaning": "Horse", "meaningNepali": "घोडा", "kanjiCharacters": ["馬"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "馬に乗ったことがあります。", "reading": "うまにのったことがあります。", "english": "I have ridden a horse before.", "nepali": "म पहिले घोडामा चढेको छु।" }] },
    { "id": "n5_18_21", "lesson": 18, "level": "N5", "word": "インターネット", "reading": "インターネット", "meaning": "Internet", "meaningNepali": "इन्टरनेट", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "インターネットで調べます。", "reading": "インターネットにしらべます。", "english": "I look up on the internet.", "nepali": "म इन्टरनेटमा खोज्छु।" }] },
    { "id": "n5_18_22", "lesson": 18, "level": "N5", "word": "特に", "reading": "とくに", "meaning": "Specially / Particularly", "meaningNepali": "खासगरी", "kanjiCharacters": ["特"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "日本料理、特にすしが好きです。", "reading": "にほんりょうり、とくにすしがすきです。", "english": "I like Japanese food, particularly sushi.", "nepali": "मलाई जापानी खाना, खासगरी सुशी मनपर्छ।" }] },
    { "id": "n5_18_23", "lesson": 18, "level": "N5", "word": "かならず", "reading": "かならず", "meaning": "Certainly / By all means", "meaningNepali": "जरुर / अवश्य", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "かならず行きます。", "reading": "かならずいきます。", "english": "I will certainly go.", "nepali": "म अवश्य जान्छु।" }] }
]

l19_data = [
    { "id": "n5_19_01", "lesson": 19, "level": "N5", "word": "登ります", "reading": "のぼります", "meaning": "Climb / Ascend (mountain)", "meaningNepali": "चढ्नु (पहाड)", "kanjiCharacters": ["登"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "富士山に登ったことがあります。", "reading": "ふじさんにのぼったことがあります。", "english": "I have climbed Mt. Fuji before.", "nepali": "म पहिले फूजी पर्वत चढेको छु।" }] },
    { "id": "n5_19_02", "lesson": 19, "level": "N5", "word": "泊まります", "reading": "とまります", "meaning": "Stay at (a hotel)", "meaningNepali": "बस्नु / बास बस्नु (होटलमा)", "kanjiCharacters": ["泊"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "ホテルに泊まります。", "reading": "ホテルにとまります。", "english": "I stay at a hotel.", "nepali": "म होटलमा बास बस्छु।" }] },
    { "id": "n5_19_03", "lesson": 19, "level": "N5", "word": "掃除します", "reading": "そうじします", "meaning": "Clean (a room)", "meaningNepali": "सफा गर्नु (कोठा)", "kanjiCharacters": ["掃", "除"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "日曜日に部屋を掃除します。", "reading": "にちようびにへやをそうじします。", "english": "I clean my room on Sunday.", "nepali": "म आइतबार कोठा सफा गर्छु।" }] },
    { "id": "n5_19_04", "lesson": 19, "level": "N5", "word": "洗濯します", "reading": "せんたくします", "meaning": "Wash clothes / Do laundry", "meaningNepali": "लुगा धुनु", "kanjiCharacters": ["洗", "濯"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "休みの日に洗濯をします。", "reading": "やすみのひにせんたくをします。", "english": "I do laundry on my day off.", "nepali": "म बिदाको दिन लुगा धुन्छु।" }] },
    { "id": "n5_19_05", "lesson": 19, "level": "N5", "word": "なります", "reading": "なります", "meaning": "Become", "meaningNepali": "बन्नु / हुनु", "kanjiCharacters": [], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "寒くなります。", "reading": "さむくなります。", "english": "It gets cold.", "nepali": "जाडो हुन्छ।" }] },
    { "id": "n5_19_06", "lesson": 19, "level": "N5", "word": "眠い", "reading": "ねむい", "meaning": "Sleepy", "meaningNepali": "निद्रालु / निन्द्रा लागेको", "kanjiCharacters": ["眠"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "とても眠いです。", "reading": "とてもねむいです。", "english": "I am very sleepy.", "nepali": "मलाई धेरै निन्द्रा लागेको छ।" }] },
    { "id": "n5_19_07", "lesson": 19, "level": "N5", "word": "強い", "reading": "つよい", "meaning": "Strong", "meaningNepali": "बलियो / बलवान", "kanjiCharacters": ["強"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "彼は体が強いです。", "reading": "かれはからだがつよいです。", "english": "He is physically strong.", "nepali": "उहाँको शरीर बलियो छ।" }] },
    { "id": "n5_19_08", "lesson": 19, "level": "N5", "word": "弱い", "reading": "よわい", "meaning": "Weak", "meaningNepali": "कमजोर", "kanjiCharacters": ["弱"], "partOfSpeech": "I-Adjective",
      "grammarSentences": [{ "japanese": "私はお酒に弱いです。", "reading": "わたしはおさけによわいです。", "english": "I am weak to alcohol.", "nepali": "मलाई रक्सी लाग्छ (कमजोर छु)।" }] },
    { "id": "n5_19_09", "lesson": 19, "level": "N5", "word": "練習", "reading": "れんしゅう", "meaning": "Practice", "meaningNepali": "अभ्यास", "kanjiCharacters": ["練", "習"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "毎日にほんごの練習をします。", "reading": "まいにちにほんごのれんしゅうをします。", "english": "I practice Japanese every day.", "nepali": "म हरेक दिन जापानी भाषाको अभ्यास गर्छु।" }] },
    { "id": "n5_19_10", "lesson": 19, "level": "N5", "word": "ゴルフ", "reading": "ゴルフ", "meaning": "Golf", "meaningNepali": "गोल्फ", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ゴルフを練習します。", "reading": "ゴルフをれんしゅうします。", "english": "I practice golf.", "nepali": "म गोल्फ अभ्यास गर्छु।" }] },
    { "id": "n5_19_11", "lesson": 19, "level": "N5", "word": "相撲", "reading": "すもう", "meaning": "Sumo wrestling", "meaningNepali": "सुमो कुस्ती", "kanjiCharacters": ["相", "撲"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "相撲を見たことがありますか。", "reading": "すもうをみたことがありますか。", "english": "Have you ever watched sumo wrestling?", "nepali": "के तपाईंले कहिल्यै सुमो कुस्ती हेर्नुभएको छ?" }] },
    { "id": "n5_19_12", "lesson": 19, "level": "N5", "word": "お茶", "reading": "おちゃ", "meaning": "Tea / Tea ceremony", "meaningNepali": "चिया / चिया समारोह", "kanjiCharacters": ["茶"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "温かいお茶を飲みます。", "reading": "あたたかいおちゃをのみます。", "english": "I drink warm tea.", "nepali": "म न्यानो चिया पिउँछु।" }] },
    { "id": "n5_19_13", "lesson": 19, "level": "N5", "word": "日", "reading": "ひ", "meaning": "Day / Date", "meaningNepali": "दिन", "kanjiCharacters": ["日"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "休みの日に買い物をします。", "reading": "やすみのひにかいものをします。", "english": "I do shopping on my day off.", "nepali": "म बिदाको दिन किनमेल गर्छु।" }] },
    { "id": "n5_19_14", "lesson": 19, "level": "N5", "word": "調子", "reading": "ちょうし", "meaning": "Condition / Health state", "meaningNepali": "अवस्था / स्वास्थ्य", "kanjiCharacters": ["調", "子"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "体の調子がいいです。", "reading": "からだのちょうしがいいです。", "english": "My physical condition is good.", "nepali": "मेरो स्वास्थ्यको अवस्था राम्रो छ।" }] },
    { "id": "n5_19_15", "lesson": 19, "level": "N5", "word": "一度", "reading": "いちど", "meaning": "Once / One time", "meaningNepali": "एक पटक", "kanjiCharacters": ["一", "度"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "一度日本へ行きたいです。", "reading": "いちどにほんへいきたいです。", "english": "I want to go to Japan once.", "nepali": "म एक पटक जापान जान चाहन्छु।" }] },
    { "id": "n5_19_16", "lesson": 19, "level": "N5", "word": "一度も", "reading": "いちども", "meaning": "Not once / Never", "meaningNepali": "एक पटक पनि (नकारात्मक)", "kanjiCharacters": ["一", "度"], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "一度もスキーをしたことがありません。", "reading": "いちどもスキーをしたことがありません。", "english": "I have never skied even once.", "nepali": "मैले एक पटक पनि स्की खेलेको छैन।" }] },
    { "id": "n5_19_17", "lesson": 19, "level": "N5", "word": "だんだん", "reading": "だんだん", "meaning": "Gradually", "meaningNepali": "बिस्तारै बिस्तारै", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "だんだん暖かくなります。", "reading": "だんだんあたたかくなります。", "english": "It gradually gets warmer.", "nepali": "बिस्तारै बिस्तारै न्यानो हुन्छ।" }] },
    { "id": "n5_19_18", "lesson": 19, "level": "N5", "word": "もうすぐ", "reading": "もうすぐ", "meaning": "Soon", "meaningNepali": "चाँडै नै", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "もうすぐ春ですね。", "reading": "もうすぐはるですね。", "english": "It will be spring soon, won't it?", "nepali": "चाँडै नै वसन्त आउँछ है।" }] },
    { "id": "n5_19_19", "lesson": 19, "level": "N5", "word": "おかげさまで", "reading": "おかげさまで", "meaning": "Thank you (by your grace)", "meaningNepali": "तपाईंको कृपाले", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "おかげさまで元気です。", "reading": "おかげさまでげんきです。", "english": "Thanks to you, I am doing well.", "nepali": "तपाईंको कृपाले सञ्चै छु।" }] },
    { "id": "n5_19_20", "lesson": 19, "level": "N5", "word": "乾杯", "reading": "かんぱい", "meaning": "Toast / Cheers!", "meaningNepali": "चियर्स!", "kanjiCharacters": ["乾", "杯"], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "みなさん、乾杯！", "reading": "みなさん、かんぱい！", "english": "Everyone, cheers!", "nepali": "सबै जना, चियर्स!" }] }
]

l20_data = [
    { "id": "n5_20_01", "lesson": 20, "level": "N5", "word": "要ります", "reading": "いります", "meaning": "Need / Require (a visa)", "meaningNepali": "चाहिनु / आवश्यकता हुनु", "kanjiCharacters": ["要"], "partOfSpeech": "Verb (Group 1)",
      "grammarSentences": [{ "japanese": "日本へ行くのにビザが要ります。", "reading": "にほんへいくのにビザがいります。", "english": "I need a visa to go to Japan.", "nepali": "जापान जान भिसा चाहिन्छ।" }] },
    { "id": "n5_20_02", "lesson": 20, "level": "N5", "word": "調べます", "reading": "しらべます", "meaning": "Investigate / Check / Look up", "meaningNepali": "जाँच गर्नु / खोजी गर्नु", "kanjiCharacters": ["調"], "partOfSpeech": "Verb (Group 2)",
      "grammarSentences": [{ "japanese": "辞書で意味を調べます。", "reading": "じしょでいみをしらべます。", "english": "I look up the meaning in a dictionary.", "nepali": "म शब्दकोशमा अर्थ खोज्छु।" }] },
    { "id": "n5_20_03", "lesson": 20, "level": "N5", "word": "修理します", "reading": "しゅうりします", "meaning": "Repair / Fix", "meaningNepali": "मर्मत गर्नु", "kanjiCharacters": ["修", "理"], "partOfSpeech": "Verb (Irregular)",
      "grammarSentences": [{ "japanese": "壊れた自転車を修理します。", "reading": "こわれたじてんしゃをしゅうりします。", "english": "I repair the broken bicycle.", "nepali": "म बिग्रिएको साइकल मर्मत गर्छु।" }] },
    { "id": "n5_20_04", "lesson": 20, "level": "N5", "word": "僕", "reading": "ぼく", "meaning": "I (used by males informally)", "meaningNepali": "म (पुरुषहरूको प्रयोग)", "kanjiCharacters": ["僕"], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "僕も一緒に行くよ。", "reading": "ぼくもいっしょにいくよ。", "english": "I'll go together too.", "nepali": "म पनि सँगै जान्छु।" }] },
    { "id": "n5_20_05", "lesson": 20, "level": "N5", "word": "君", "reading": "きみ", "meaning": "You (informal)", "meaningNepali": "तिमी (साथी/सानालाई)", "kanjiCharacters": ["君"], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "君はどこへ行くの？", "reading": "きみはどこへいくの？", "english": "Where are you going?", "nepali": "तिमी कहाँ जाँदैछौ?" }] },
    { "id": "n5_20_06", "lesson": 20, "level": "N5", "word": "〜君", "reading": "〜くん", "meaning": "Mr. / Boy suffix", "meaningNepali": "~ बाबु / साथी (केटाहरूको लागि)", "kanjiCharacters": ["君"], "partOfSpeech": "Suffix",
      "grammarSentences": [{ "japanese": "山田君、元気？", "reading": "やまだくん、げんき？", "english": "Yamada-kun, how are you?", "nepali": "यामादा बाबु, कस्तो छ?" }] },
    { "id": "n5_20_07", "lesson": 20, "level": "N5", "word": "うん", "reading": "うん", "meaning": "Yes (casual)", "meaningNepali": "अँ / हो (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "うん、わかった。", "reading": "うん、わかった。", "english": "Yeah, I understood.", "nepali": "अँ, मैले बुझें।" }] },
    { "id": "n5_20_08", "lesson": 20, "level": "N5", "word": "うーん", "reading": "うーん", "meaning": "Well / Let me see...", "meaningNepali": "अँ... (सोच्दा)", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "うーん、どうしようかな。", "reading": "うーん、どうしようかな。", "english": "Hmm, what should I do...", "nepali": "अँ... के गरौँ त होला।" }] },
    { "id": "n5_20_09", "lesson": 20, "level": "N5", "word": "ううん", "reading": "ううん", "meaning": "No (casual)", "meaningNepali": "अहँ / होइन (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "ううん、行かない。", "reading": "ううん、いかない。", "english": "No, I'm not going.", "nepali": "अहँ, जान्न।" }] },
    { "id": "n5_20_10", "lesson": 20, "level": "N5", "word": "言葉", "reading": "ことば", "meaning": "Word / Language", "meaningNepali": "शब्द / भाषा", "kanjiCharacters": ["言", "葉"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "日本の言葉を勉強します。", "reading": "にほんのことばをべんきょうします。", "english": "I study the Japanese language.", "nepali": "म जापानी भाषा पढ्छु।" }] },
    { "id": "n5_20_11", "lesson": 20, "level": "N5", "word": "物価", "reading": "ぶっか", "meaning": "Commodity prices", "meaningNepali": "वस्तुको मूल्य / महँगी", "kanjiCharacters": ["物", "価"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "東京は物価が高いです。", "reading": "とうきょうはぶっかがたかいです。", "english": "Prices in Tokyo are high.", "nepali": "टोकियोमा महँगी छ।" }] },
    { "id": "n5_20_12", "lesson": 20, "level": "N5", "word": "着物", "reading": "きもの", "meaning": "Kimono (Japanese traditional clothes)", "meaningNepali": "किमोनो (जापानी पोशाक)", "kanjiCharacters": ["着", "物"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "きれいな着物を着ています。", "reading": "きれいなきものをきています。", "english": "She is wearing a beautiful kimono.", "nepali": "उहाँले सुन्दर किमोनो लगाउनुभएको छ।" }] },
    { "id": "n5_20_13", "lesson": 20, "level": "N5", "word": "ビザ", "reading": "ビザ", "meaning": "Visa", "meaningNepali": "भिसा", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "ビザを申請しました。", "reading": "ビザをしんせいしました。", "english": "I applied for a visa.", "nepali": "मैले भिसा आवेदन दिएँ।" }] },
    { "id": "n5_20_14", "lesson": 20, "level": "N5", "word": "始まり", "reading": "はじまり", "meaning": "Beginning / Start", "meaningNepali": "शुरुवात", "kanjiCharacters": ["始"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "映画の始まりに間に合いました。", "reading": "えいがのはじまりにまにあいました。", "english": "I made it in time for the start of the movie.", "nepali": "म फिल्मको सुरुवातमा समयमै पुगें।" }] },
    { "id": "n5_20_15", "lesson": 20, "level": "N5", "word": "終わり", "reading": "おわり", "meaning": "End / Finish", "meaningNepali": "अन्त्य / समाप्ति", "kanjiCharacters": ["終"], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "仕事の終わりに飲みに行きます。", "reading": "しごとのおわりにのみにいきます。", "english": "I go for a drink at the end of work.", "nepali": "म कामको अन्त्यमा पिउन जान्छु।" }] },
    { "id": "n5_20_16", "lesson": 20, "level": "N5", "word": "こっち", "reading": "こっち", "meaning": "This way / Here (casual)", "meaningNepali": "यता / यहाँ (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "こっちへ来て！", "reading": "こっちへきて！", "english": "Come over here! (casual)", "nepali": "यता आऊ!" }] },
    { "id": "n5_20_17", "lesson": 20, "level": "N5", "word": "そっち", "reading": "そっち", "meaning": "That way / There (casual)", "meaningNepali": "उता / त्यहाँ (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "そっちは危ないよ。", "reading": "そっちはあぶないよ。", "english": "That way is dangerous. (casual)", "nepali": "उता खतरा छ।" }] },
    { "id": "n5_20_18", "lesson": 20, "level": "N5", "word": "あっち", "reading": "あっち", "meaning": "That way over there (casual)", "meaningNepali": "उता टाढा (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "あっちへ行こう。", "reading": "あっちへいこう。", "english": "Let's go over there. (casual)", "nepali": "उता टाढा जाऔँ।" }] },
    { "id": "n5_20_19", "lesson": 20, "level": "N5", "word": "どっち", "reading": "どっち", "meaning": "Which way / Which one (casual)", "meaningNepali": "कुन / कता (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Pronoun",
      "grammarSentences": [{ "japanese": "どっちがいい？", "reading": "どっちがいい？", "english": "Which one do you prefer?", "nepali": "कुन राम्रो छ?" }] },
    { "id": "n5_20_20", "lesson": 20, "level": "N5", "word": "みんなで", "reading": "みんなで", "meaning": "All together / Everyone", "meaningNepali": "सबै जना मिलेर", "kanjiCharacters": [], "partOfSpeech": "Adverb",
      "grammarSentences": [{ "japanese": "みんなで写真を撮りました。", "reading": "みんなでしゃしんをとりました。", "english": "We took a photo all together.", "nepali": "हामी सबै जना मिलेर फोटो खिच्यौँ।" }] },
    { "id": "n5_20_21", "lesson": 20, "level": "N5", "word": "〜けど", "reading": "〜けど", "meaning": "..., but (casual)", "meaningNepali": "..., तर (अनौपचारिक)", "kanjiCharacters": [], "partOfSpeech": "Conjunction",
      "grammarSentences": [{ "japanese": "高いけど、美味しいよ。", "reading": "たかいけど、おいしいよ。", "english": "It's expensive, but delicious.", "nepali": "महँगो छ तर मिठो छ।" }] },
    { "id": "n5_20_22", "lesson": 20, "level": "N5", "word": "お腹がいっぱいです", "reading": "おなかがいっぱいです", "meaning": "Full (stomach)", "meaningNepali": "पेट भरियो", "kanjiCharacters": ["腹"], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "もうお腹がいっぱいです。", "reading": "もうおなかがいっぱいです。", "english": "I'm already full.", "nepali": "अहिले मेरो पेट भरिसक्यो।" }] },
    { "id": "n5_20_23", "lesson": 20, "level": "N5", "word": "よかったら", "reading": "よかったら", "meaning": "If you like", "meaningNepali": "मन परेमा / सम्भव भए", "kanjiCharacters": [], "partOfSpeech": "Expression",
      "grammarSentences": [{ "japanese": "よかったら一緒に行きませんか。", "reading": "よかったらいっしょにいきませんか。", "english": "If you like, would you like to go together?", "nepali": "मन परेमा सँगै जाने हो?" }] },
    { "id": "n5_20_24", "lesson": 20, "level": "N5", "word": "いろいろ[な]", "reading": "いろいろ[な]", "meaning": "Various / Diverse", "meaningNepali": "विभिन्न / थरीथरीका", "kanjiCharacters": [], "partOfSpeech": "Na-Adjective",
      "grammarSentences": [{ "japanese": "いろいろな国へ行きたいです。", "reading": "いろいろなくにへいきたいです。", "english": "I want to go to various countries.", "nepali": "म विभिन्न देशहरूमा जान चाहन्छु।" }] },
    { "id": "n5_20_25", "lesson": 20, "level": "N5", "word": "サラリーマン", "reading": "サラリーマン", "meaning": "Company worker / Salaryman", "meaningNepali": "जागिरे / कम्पनी कर्मचारी", "kanjiCharacters": [], "partOfSpeech": "Noun",
      "grammarSentences": [{ "japanese": "父は日本のサラリーマンです。", "reading": "ちちはにほんのサラリーマンです。", "english": "My father is a Japanese company worker.", "nepali": "मेरो बुबा जापानी कम्पनीको कर्मचारी हुनुहुन्छ।" }] }
]

ts16_20_header = """// ============================================================
// MINNA NO NIHONGO N5 — Complete Vocabulary & Grammar
// SOURCE: Minna no Nihongo I (Translations & Grammar Notes)
// LESSONS 16–20 (Full coverage, no omissions)
// English + Nepali meanings · Grammar sentences per word
// ============================================================

import type { VocabItem } from './nihongo-vocab';

export const N5_LESSONS_16TO20: VocabItem[] = [
"""

all_16_20 = l16_data + l17_data + l18_data + l19_data + l20_data

ts16_20_body = ""
for item in all_16_20:
    ts16_20_body += "  " + json.dumps(item, ensure_ascii=False) + ",\n"

with open("lib/n5-lessons-16to20.ts", "w", encoding="utf-8") as f:
    f.write(ts16_20_header + ts16_20_body + "];\n")

print(f"Updated lib/n5-lessons-16to20.ts with {len(all_16_20)} complete entries for Lessons 16-20!")
