import json
import re
import sys
import docx

sys.stdout.reconfigure(encoding='utf-8')

with open("scratch/docx_lessons_13_20.json", "r", encoding="utf-8") as f:
    docx_data = json.load(f)

# Helper function to generate clean Nepali translations for vocabulary
def get_nepali_vocab_meaning(eng):
    eng_lower = eng.lower().strip()
    
    # Common vocabulary translations
    mappings = {
        "enjoy oneself, play": "रमाइलो गर्नु / खेल्नु",
        "swim": "पौडी खेल्नु",
        "go to meet, welcome": "भेट्न जानु / स्वागत गर्नु",
        "get tired": "थाक्नु",
        "marry, get married": "विवाह गर्नु",
        "shopping": "किनमेल",
        "meal, dining": "खाना",
        "walk, stroll [in a park]": "पैदल हिँड्नु / घुम्नु",
        "hard, terrible, severe": "कठिन / गाह्रो",
        "want (something)": "चाहिनु / इच्छा हुनु",
        "wide, spacious": "फराकिलो",
        "narrow, small (room, etc.)": "साँघुरो / साँघुरो ठाउँ",
        "municipal office, city hall": "नगरपालिका कार्यालय",
        "river": "नदी",
        "fine art": "कला",
        "fishing": "माछा मार्ने कार्य",
        "skiing": "स्किइङ",
        "surfing": "सर्फिङ",
        "new year's eve": "नयाँ वर्षको पूर्वसन्ध्या",
        "about (time, degree)": "लगभग / करिब",
        "something": "केही",
        "somewhere, any place": "कतै / कुनै ठाउँ",
        "thirsty": "प्यासी / तिर्खा लाग्नु",
        "hungry": "भोको / भोक लाग्नु",
        "let's do that (agreeing)": "त्यसै गरौँ",
        "may I help you? (at a shop)": "के म सहयोग गर्न सक्छु?",
        
        # Lesson 14
        "turn on": "बाल्नु / अन गर्नु",
        "turn off": "निभाउनु / अफ गर्नु",
        "open": "खोल्नु",
        "close, shut": "बन्द गर्नु",
        "hurry": "हतार गर्नु",
        "wait": "पर्खनु",
        "hold, carry": "समात्नु / बोक्नु",
        "take, pass": "लिऊनु / दिनु",
        "help (with a task)": "सहयोग गर्नु",
        "call": "बोलाउनु",
        "speak, talk": "बोल्नु",
        "use": "प्रयोग गर्नु",
        "stop, park": "रोक्नु / पार्क गर्नु",
        "show": "देखाउनु",
        "tell [an address]": "भन्नु / ठेगाना भन्नु",
        "sit down": "बस्नु",
        "stand up": "उभिनु",
        "enter [a coffee shop]": "छिर्नु",
        "go out [of a coffee shop]": "बाहिर निस्कनु",
        "rain [fall]": "पानी पर्नु",
        "copy": "प्रतिलिपि गर्नु",
        "electricity, light": "बिजुली / बत्ती",
        "air conditioner": "एयर कन्डिसनर",
        "passport": "राहदानी / पासपोर्ट",
        "name": "नाम",
        "address": "ठेगाना",
        "map": "नक्सा",
        "salt": "नुन",
        "sugar": "चिनी",
        "problem, trouble, question": "समस्या / प्रश्न",
        "answer": "उत्तर",
        "reading (how to read)": "उच्चारण / पढ्ने तरिका",
        "straight": "सिधा",
        "slowly, leisurely": "बिस्तारै / आरामले",
        "immediately, right away": "तुरन्तै / तुरुन्त",
        "again": "फेरि",
        "later": "पछि",
        "a little more": "अझ अलि",
        "more, another": "अझै",
        "surely, certainly": "निश्चय नै",
        "is that so?": "हो र?",
        
        # Lesson 15
        "stand up": "उभिनु",
        "sit down": "बस्नु",
        "use": "प्रयोग गर्नु",
        "put, place": "राख्नु",
        "make, produce": "बनाउनु / उत्पादन गर्नु",
        "sell": "बेच्नु",
        "know": "जान्नु / थाहा पाउनु",
        "live, reside": "बस्नु / निवास गर्नु",
        "research": "अनुसन्धान गर्नु",
        "materials, data": "सामग्री / डाटा",
        "catalog": "क्याटलग",
        "timetable": "समय तालिका",
        "clothes": "कपडा",
        "products, goods": "उत्पादन / सामान",
        "software": "सफ्टवेयर",
        "electronic dictionary": "इलेक्ट्रोनिक शब्दकोश",
        "single, unmarried": "अविवाहित",
        "special": "विशेष",
        "remember, recall": "सम्झनु",
        "your family": "तपाईंको परिवार",
        
        # Lesson 16
        "ride, get on [a train]": "चढ्नु [रेलमा]",
        "get off [a train]": "ओर्लनु [रेलबाट]",
        "change (trains, etc.)": "फेर्नु / परिवर्तन गर्नु",
        "take [a shower]": "नुहाउनु [शावर]",
        "put in, insert": "हाल्नु / छिराउनु",
        "withdraw [money]": "झिक्नु [पैसा]",
        "enter [university]": "भर्ना हुनु [विश्वविद्यालयमा]",
        "graduate [from university]": "स्नातक हुनु",
        "quit, retire": "छाड्नु / अवकाश लिनु",
        "push, press": "थिच्नु / दबाउनु",
        "drink alcohol": "रक्सी पिउनु",
        "start, begin": "सुरु गर्नु",
        "tour, visit (place of interest)": "भ्रमण गर्नु",
        "call (on the telephone)": "फोन गर्नु",
        "young": "जवान / कान्छो",
        "long": "लामो",
        "short": "छोटो",
        "bright, light": "उज्यालो",
        "dark": "अध्यारो",
        "body, health": "शरीर / स्वास्थ्य",
        "head, brain": "टाउको",
        "hair": "कपाल",
        "face": "अनुहार",
        "eyes": "आँखा",
        "ears": "कान",
        "mouth": "मुख",
        "teeth": "दाँत",
        "stomach": "पेट",
        "leg, foot": "खुट्टा",
        "height": "उचाइ",
        "service": "सेवा",
        "jogging": "जगिङ",
        "shower": "शावर",
        "green, greenery": "हरियाली",
        "temple (Buddhist)": "बौद्ध मन्दिर",
        "shrine (Shinto)": "शिन्तो मन्दिर",
        "how, in what way": "कसरी",
        "which (among three or more)": "कुन",
        
        # Lesson 17
        "memorize": "याद गर्नु / घोक्नु",
        "forget": "बिर्सनु",
        "lose": "हराउनु",
        "pay": "तिर्नु",
        "return, give back": "फिर्ता गर्नु",
        "go out": "बाहिर निस्कनु",
        "take off [clothes, shoes]": "खोल्नु [लुगा/जुत्ता]",
        "take [something along]": "साथमा लैजानु",
        "bring [something along]": "साथमा ल्याउनु",
        "worry": "चिन्ता गर्नु",
        "overtime work": "ओभरटाइम काम गर्नु",
        "business trip": "व्यापारिक भ्रमण",
        "take [medicine]": "औषधि खानु",
        "take [a bath]": "नुहाउनु [बाथटब]",
        "important, precious": "महत्वपूर्ण",
        "all right, okay": "ठिकै छ / समस्या छैन",
        "dangerous": "खतरनाक",
        "health insurance card": "स्वास्थ्य बीमा कार्ड",
        "fever": "ज्वरो",
        "illness, sickness": "बिरामी / रोग",
        "medicine": "औषधि",
        "jacket, outerwear": "ज्याकेट / कोट",
        "undergarments, underwear": "भित्री वस्त्र",
        "2 or 3 days": "२ वा ३ दिन",
        "before, by (time limit)": "अघि / भित्रमा",
        "therefore, so": "त्यसैले",
        
        # Lesson 18
        "be able to, can": "सक्नु / सम्भव हुनु",
        "wash": "पखाल्नु / धुनु",
        "play (stringed instrument or piano, etc.)": "बजाउनु [बाजा/पियानो]",
        "sing": "गाउनु",
        "collect, gather": "संकलन गर्नु / जम्मा गर्नु",
        "throw away": "फ्याँक्नु / फाल्नु",
        "exchange, change": "साट्नु / परिवर्तन गर्नु",
        "drive": "गाडी चलाउनु",
        "reserve, book": "आरक्षित गर्नु / बुक गर्नु",
        "piano": "पियानो",
        "meter": "मिटर",
        "cash": "नगद",
        "hobby": "रुचि / हबी",
        "diary": "डायरी",
        "prayer": "प्रार्थना",
        "section head": "शाखा प्रमुख",
        "department manager": "विभाग प्रमुख",
        "company president": "कम्पनी अध्यक्ष",
        "animal": "जनावर",
        "horse": "घोडा",
        "really, by all means": "निश्चय नै / अवश्य",
        "not easily, not readily": "सजिलैसँग होइन",
        
        # Lesson 19
        "climb [a mountain]": "चढ्नु [पहाड]",
        "stay [at a hotel]": "बस्नु [होटलमा]",
        "clean (a room)": "सरसफाइ गर्नु",
        "wash (clothes)": "धुलाई गर्नु",
        "become": "हुनु / बन्नु",
        "sleepy": "निद्रा लाग्नु",
        "strong": "बलियो / बलियो",
        "weak": "कमजोर",
        "golf": "गोल्फ",
        "wrestling": "कुश्ती / रेसलिङ",
        "tea ceremony": "चिया समारोह",
        "day, date": "दिन / मिति",
        "condition, state": "अवस्था / स्थिति",
        "once": "एक पटक",
        "not once, never": "एक पटक पनि होइन",
        "gradually": "बिस्तारै / क्रमैसँग",
        "soon": "छिट्टै",
        "thanks to you": "तपाईंको कृपाले",
        
        # Lesson 20
        "need, require [a visa]": "चाहिनु [भिसा]",
        "check, investigate": "जाँच गर्नु / अनुसन्धान गर्नु",
        "repair, correct": "मर्मत गर्नु / सच्याउनु",
        "I (informal, male)": "म (पुरुषहरूले प्रयोग गर्ने)",
        "you (informal)": "तिमी (साथी/सानालाई)",
        "Mr. / Ms. (informal suffix)": "जी (छोटो/आत्मीय रूप)",
        "yes (informal)": "उम् / अँ (हो)",
        "no (informal)": "उँऊन् (होइन)",
        "word, language": "शब्द / भाषा",
        "kimono": "किमोनो (जापानी परम्परागत लुगा)",
        "visa": "भिसा",
        "beginning, start": "शुरुवात / सुरु",
        "end": "अन्त्य / समाप्त",
        "this way, here": "यता / यो दिशा",
        "that way, there": "उता / त्यो दिशा",
        "which one (between two)": "कुन चाहिँ (दुईमध्ये)",
        "both": "दुवै",
        "regarding..., about...": "बारेमा",
        "full": "भरिपूर्ण / पेट भरिनु",
    }
    
    for k, v in mappings.items():
        if k in eng_lower:
            return v
            
    return eng  # Fallback to English text if no mapping

print("Testing helper...")
print(get_nepali_vocab_meaning("ride, get on [a train]"))
